force-app/main/default/objects/blng__CreditNote__c/fields/blng__Balance__c.field-meta.xml
<CustomField>
    <fullName>blng__Balance__c</fullName>
    <formula>blng__TotalAmount__c -  blng__Allocations__c +  blng__Unallocations__c - blng__Debits__c - blng__Refunds__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Montant de la note de crédit qui n’a pas été alloué ou remboursé</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__Status__c.field-meta.xml
<CustomField>
    <fullName>blng__Status__c</fullName>
    <inlineHelpText>Statut actuel de la note de crédit. Cela peut être : Brouillon Publié Annulé</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__PostingStatus</valueSetName>
    </valueSet>
</CustomField>

mdapiEYH/objects/blng__CreditNoteLine__c.object
<CustomObject>
    <label>Credit Note Line</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Note Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__Balance__c</fullName>
        <formula>blng__TotalAmount__c - blng__Allocations__c + blng__Unallocations__c -  blng__Refunds__c - blng__Debits__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount that has not yet been allocated</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__InvoiceLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Line</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Draft Invoice Lines would not be available</errorMessage>
            <filterItems>
                <field>blng__InvoiceLine__c.blng__InvoiceLineStatus__c</field>
                <operation>notEqual</operation>
                <value>Draft</value>
            </filterItems>
            <infoMessage>Draft Invoice Lines would not be available</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__InvoiceLine__c</referenceTo>
        <relationshipLabel>Credit Note Lines</relationshipLabel>
        <relationshipName>InvoiceLineCreditNoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__Status__c</fullName>
        <inlineHelpText>Status of the credit memo. Can be: Draft Posted Canceled</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__PostingStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

mdapiEYH/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_StatutFacture__c</fullName>
        <label>Statut De La Facture</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brouillon</fullName>
                </value>
                <value>
                    <fullName>A Envoyer</fullName>
                </value>
                <value>
                    <fullName>Envoyée</fullName>
                </value>
                <value>
                    <fullName>Signée</fullName>
                </value>
                <value>
                    <fullName>Annulée</fullName>
                </value>
                <value>
                    <fullName>Terminée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__Account__c</fullName>
        <inlineHelpText>Rechercher dans le compte la facturation de cette facture.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>AccountInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__Balance__c</fullName>
        <formula>blng__TotalAmount__c - blng__Payments__c - blng__Credits__c + blng__Debits__c + blng__NegativeLineConversion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Solde = montant total - paiements nets totaux - notes de crédit appliquées + notes de débit appliquées + conversions de ligne négatives</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__InvoiceStatus__c</fullName>
        <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__InvoiceStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_CongesPrisPeriode__c.field-meta.xml
<CustomField>
    <fullName>LPCR_CongesPrisPeriode__c</fullName>
    <label>Conges Pris Periode</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_Quantite__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Quantite__c</fullName>
    <label>Quantité</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_StatutPaiement__c.field-meta.xml
<CustomField>
    <fullName>LPCR_StatutPaiement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Statut Paiement</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/blng__InvoiceLine__c.object
<CustomObject>
    <description>The line items on Invoices, such as products etc.</description>
    <label>Invoice Line</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__Balance__c</fullName>
        <formula>blng__TotalAmount__c - blng__Payments__c - blng__Credits__c + blng__Debits__c + blng__NegativeLineConversion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount (with tax) - Payments - Credits + Debits + Negative Line Conversion</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>blng__Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>InvoiceInvoiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>OrderProductInvoiceLines</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>SBQQ__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/LPCR_ModificationEntrante__c.object
<CustomObject>
    <description>Cet objet nous permettra de collecter les données en provenance d&apos;Intranet et de la GTA  concernant des événements et liés à de l&apos;usage sur SF (absences, heures déduites, maladie ...)</description>
    <label>Modification Entrante</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modifications Entrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Evenement__c</fullName>
        <label>Evènement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Modification Adresse Contact Parent</fullName>
                </value>
                <value>
                    <fullName>Modification Autorité Parentale</fullName>
                </value>
                <value>
                    <fullName>Modification Numéro Allocataire</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Handicapé Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Type Accueil</fullName>
                </value>
                <value>
                    <fullName>Modification Type Planning</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Montant Ressource</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Jour Congé</fullName>
                </value>
                <value>
                    <fullName>Date Fin Contrat</fullName>
                </value>
                <value>
                    <fullName>Modification Section</fullName>
                </value>
                <value>
                    <fullName>Date Naissance Enfant</fullName>
                </value>
                <value>
                    <fullName>Modification Mode Garde</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Familiale</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Mois Mensualisé</fullName>
                </value>
                <value>
                    <fullName>Modification Traitement Jour férié</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Modification Délai Carence</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Supplémentaire MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Occasionnel MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Congés MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Déduite MAC</fullName>
                </value>
                <value>
                    <fullName>Validation Contrat Directrice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_Quantite__c</fullName>
        <label>Quantité</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SM015_InvoiceServices.cls
/**
* @author Saurabh
* @created 15/06/2020
* @description Service class for Invoice Object
*/
public class SM015_InvoiceServices {
    
    /*
* 	@Author : Ayoub Ouarti
* 	@Created 10/07/2020
*	@Description : this method create Payment And Payment Allocation for Invoice with changed LPCR_StatutPaiement__c 
* 	@Inputs	List<blng__Invoice__c> newInvoiceList, Map<Id, blng__Invoice__c> oldInvoiceMap
*/
    public static void createPaymentAndPaymentAllocation(List<blng__Invoice__c> newInvoiceList, Map<Id, blng__Invoice__c> oldInvoiceMap){
        Map<Id, blng__Payment__c> paymentByInvoiceMap = new Map<Id, blng__Payment__c>();
        Map<Id,blng__Invoice__c> mapInvocieLineStatutPaiement = new Map<Id,blng__Invoice__c>();
        List<blng__PaymentAllocationInvoiceLine__c> listPaymentAlloInvoiceLine = new  List<blng__PaymentAllocationInvoiceLine__c>();
        Map<String,Decimal> mapInvoiceSumBalanceInvoicelines = new Map<String,Decimal>();
        
        for(blng__Invoice__c eachInvoice : newInvoiceList){
            // If a status of payment has been received
            if(eachInvoice.LPCR_StatutPaiement__c && eachInvoice.LPCR_StatutPaiement__c != oldInvoiceMap.get(eachInvoice.id).LPCR_StatutPaiement__c){
                mapInvocieLineStatutPaiement.put(eachInvoice.Id,eachInvoice);
            }                
        }
        
        List<blng__InvoiceLine__c > listInvoiceline = [SELECT blng__Invoice__c, blng__Balance__c FROM blng__InvoiceLine__c WHERE blng__Balance__c > 0 AND blng__Invoice__c IN :mapInvocieLineStatutPaiement.keySet() ];
        for(blng__InvoiceLine__c eachInvoiceLine : listInvoiceline){
            mapInvoiceSumBalanceInvoicelines.put(String.valueOf(eachInvoiceLine.blng__Invoice__c),
                                                 !mapInvoiceSumBalanceInvoicelines.containsKey(eachInvoiceLine.blng__Invoice__c)? eachInvoiceLine.blng__Balance__c
                                                 :eachInvoiceLine.blng__Balance__c+mapInvoiceSumBalanceInvoicelines.get(eachInvoiceLine.blng__Invoice__c));
        }
        for(blng__Invoice__c eachInvoice : mapInvocieLineStatutPaiement.values()){
            if(mapInvoiceSumBalanceInvoicelines.containsKey(eachInvoice.Id))  paymentByInvoiceMap.put(eachInvoice.Id, new blng__Payment__c(blng__Account__c = eachInvoice.blng__Account__c, blng__Amount__c = mapInvoiceSumBalanceInvoicelines.get(eachInvoice.Id), blng__Status__c = 'Posted' ));
        }
        if(paymentByInvoiceMap.size() > 0){
            //Create a blng__Payment__c record
            insert paymentByInvoiceMap.values();
        }
        
        
        for(blng__InvoiceLine__c eachInvoiceLine : listInvoiceline){
            listPaymentAlloInvoiceLine.add(new blng__PaymentAllocationInvoiceLine__c(blng__InvoiceLine__c =eachInvoiceLine.Id,
                                                                                     blng__Payment__c =paymentByInvoiceMap.get(eachInvoiceLine.blng__Invoice__c).Id,
                                                                                     blng__Amount__c=eachInvoiceLine.blng__Balance__c,
                                                                                     blng__Type__c='Allocation')); 
        }
        
        if(listPaymentAlloInvoiceLine.size() > 0){
            //Create a Payment Allocation record blng__PaymentAllocationInvoice__c
            insert listPaymentAlloInvoiceLine;
        }
    }
    
    public static void setStatutFacture(List<blng__Invoice__c> newInvoiceList, Map<Id, blng__Invoice__c> oldInvoiceMap){
        for(blng__Invoice__c eachNewInvoice : newInvoiceList){
            System.debug('eachNewInvoice => ' + eachNewInvoice);
            if(String.isNotBlank(eachNewInvoice.blng__InvoiceStatus__c) 
               && !eachNewInvoice.blng__InvoiceStatus__c.equals(oldInvoiceMap.get(eachNewInvoice.Id).blng__InvoiceStatus__c)
               &&  'Posted'.equals(eachNewInvoice.blng__InvoiceStatus__c)){
                   eachNewInvoice.LPCR_StatutFacture__c = 'Prêt à valider';
               }
        }
    }
    
    
    public static void setCongePrisPeriode(List<blng__Invoice__c> newInvoiceList, Map<Id, blng__Invoice__c> newInvoiceMap){
        
        
        Id familleRecTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account,Label.LPCR_Famille);
        
        List<blng__Invoice__c> invoiceList = [Select Id, LPCR_StatutFacture__c  , LPCR_CongesPrisPeriode__c, blng__Account__c,blng__Account__r.recordTypeId FROM blng__Invoice__c WHERE Id IN: newInvoiceList AND blng__Account__r.recordTypeId =: familleRecTypeId AND LPCR_StatutFacture__c = 'A Envoyer'];
        List<blng__InvoiceLine__c> invoiceLines = [Select Id, blng__OrderProduct__r.OrderId, blng__Invoice__c  From blng__InvoiceLine__c WHERE blng__Invoice__c  IN:invoiceList Limit 1];
        if(invoiceLines.size()>0){
            blng__InvoiceLine__c invoiceLine = invoiceLines.get(0);
            List<Contract> contractList =[select Id,SBQQ__Order__c from Contract where SBQQ__Order__c = :invoiceLine.blng__OrderProduct__r.OrderId];
            
            LPCR_ModificationEntrante__c modificationEntrante = [SELECT Id, LPCR_Quantite__c, LPCR_Evenement__c,LPCR_Contract__c  From LPCR_ModificationEntrante__c Where LPCR_Evenement__c='Conges_Pris_Periode' AND LPCR_Contract__c IN:contractList  order by createdDate DESC limit 1];
            
            Decimal modificationQuantity = modificationEntrante.LPCR_Quantite__c;
            
            for(blng__Invoice__c eachNewInvoice : invoiceList){
                
                newInvoiceMap.get(eachNewInvoice.Id).LPCR_CongesPrisPeriode__c = modificationQuantity;
                
            }
        }
        
    }

    // added by saurabh IS-1529
    public static void afterUpdateCreateCreditNoteAllocation(List<blng__Invoice__c> newInvoiceList){
        Pad.log('SM015_InvoiceServices','afterUpdateCreateCreditNoteAllocation(List<blng__Invoice__c> newInvoiceList)','newInvoiceList size '+newInvoiceList.size());
        
        Set<Id> invoiceIdsSet = UM003_TypeManager.getIdsOfListObjects(newInvoiceList);
        Set<Id> creditNoteIdsSet = new Set<Id>();
        List<blng__CreditNoteAllocation__c> insertCreditNoteAllocationList = new List<blng__CreditNoteAllocation__c>();
        
        for(blng__CreditNote__c creditNote : [select id from blng__CreditNote__c where blng__RelatedInvoice__c in: invoiceIdsSet and blng__Status__c = 'Posted' and blng__CreditNoteSourceAction__c = 'Manual' ]){
            creditNoteIdsSet.add(creditNote.id);
        }
        
        if(creditNoteIdsSet.size() > 0){
            for(blng__CreditNoteLine__c eachCNLine : [select id, blng__Balance__c, blng__InvoiceLine__c, blng__InvoiceLine__r.blng__Balance__c from blng__CreditNoteLine__c where blng__Status__c = 'Posted' and blng__Balance__c > 0 Order By CreatedDate]){
                blng__CreditNoteAllocation__c newCreditNoteAllocation = new blng__CreditNoteAllocation__c();
                newCreditNoteAllocation.blng__Amount__c = eachCNLine.blng__InvoiceLine__r.blng__Balance__c;
                newCreditNoteAllocation.blng__InvoiceLine__c = eachCNLine.blng__InvoiceLine__c;
                newCreditNoteAllocation.blng__Notes__c = 'Automatic Credit Note Allocation';
                newCreditNoteAllocation.blng__Type__c = 'Allocation';
                newCreditNoteAllocation.blng__CreditNoteLine__c = eachCNLine.id;
                
                if(eachCNLine.blng__InvoiceLine__r.blng__Balance__c >= eachCNLine.blng__Balance__c){
                    newCreditNoteAllocation.blng__Amount__c = eachCNLine.blng__Balance__c;
                }else{
                    newCreditNoteAllocation.blng__Amount__c = eachCNLine.blng__InvoiceLine__r.blng__Balance__c;
                }
                insertCreditNoteAllocationList.add(newCreditNoteAllocation);
            }
        }
        
        if(insertCreditNoteAllocationList.size() > 0){
            try{
				insert insertCreditNoteAllocationList;                
            }catch(Exception ex){
                PAD.log('SM015_InvoiceServices', 'afterUpdateCreateCreditNoteAllocation', 'Exception: ' + ex.getMessage());
            }
        }
    }
}