mdapiEYH/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/SBQQ__RenewalModel__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalModel__c</fullName>
    <description>The option to distinguish between Subscription or Asset based renewal.</description>
    <inlineHelpText>Sélectionnez Basé sur les ressources pour générer les renouvellements en fonction des ressources d&apos;un compte ou Basé sur le contrat pour générer les renouvellements en fonction du contrat créé à partir d&apos;un devis.</inlineHelpText>
    <label>Renewal Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Based</fullName>
            </value>
            <value>
                <fullName>Contract Based</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Debut</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_MethodeRenouvellement__c</fullName>
        <label>Méthode Renouvellement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tacite</fullName>
                </value>
                <value>
                    <fullName>Express</fullName>
                </value>
                <value>
                    <fullName>Sans renouvellement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_DureeContratJour__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DureeContratJour__c</fullName>
    <label>Durée du contrat en jours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/APB008_ResetStartEndDatesOnContract_Test.cls
/**
* @author Ayoub Ouarti
* @date 08/06/2020
* @Description Testt class for APB008_ResetStartEndDatesOnContract
*/
@isTest
public class APB008_ResetStartEndDatesOnContract_Test {
    private static final Id B2B_RT_ID = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Entreprise);
	private static final Date todayDate = Date.toDay();
    private static final String methodeRenouvellementValue='Tacite';
    @testsetup
    static void setup() {
        
        
        Map<String, Object> defaultVal = new Map<String, Object> {
            'RecordTypeId' => B2B_RT_ID,
            'Name' => 'Test-B2B',
            'SBQQ__RenewalModel__c' => 'Contract Based'
        };
        Account b2bAccount = (Account) UM002_TestDataFactory.createSObject('Account', defaultVal);
        insert b2bAccount;

        Contract contract = UM002_TestDataFactory.createContract(b2bAccount.Id);
        contract.LPCR_MethodeRenouvellement__c=methodeRenouvellementValue;
        contract.LPCR_DateFin__c=todayDate;
        contract.LPCR_DureeContratJour__c=100;
        insert contract;
       
    }
    
    @isTest
    private static void testAPB008ResetStartEndDatesOnContract(){
        System.runAs(UM002_TestDataFactory.createUser()){
           
            Account acc = [SELECT Id, name from Account where name ='Test-B2B' LIMIT 1];
           
            Contract contract = [SELECT Id, LPCR_DureeContratJour__c ,LPCR_DateFin__c ,LPCR_DateDebut__c ,LPCR_MethodeRenouvellement__c, Account.RecordTypeId FROM Contract
                                 WHERE AccountId =:acc.Id ];
           
            Test.startTest();
            APB008_ResetStartEndDatesOnContract resetStartEndDatesOnContract = new APB008_ResetStartEndDatesOnContract();
            resetStartEndDatesOnContract.execute(null);
           
            Test.stopTest();
            contract = [SELECT Id, LPCR_DureeContratJour__c ,LPCR_DateFin__c ,LPCR_DateDebut__c ,LPCR_MethodeRenouvellement__c, Account.RecordTypeId FROM Contract
                                 WHERE AccountId =:acc.Id ];
           System.assertEquals(todayDate.addDays(1), contract.LPCR_DateDebut__c,'LPCR_DateDebut__c is not today');
           System.assertEquals(contract.LPCR_DateDebut__c.addDays(Integer.valueOf(contract.LPCR_DureeContratJour__c)), contract.LPCR_DateFin__c,'LPCR_DateFin__c is not LPCR_DateDebut__c +LPCR_DureeContratJour__c ');
           
        }
    }
}