mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Ancien client</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
                <value>
                    <fullName>Ex-adhérent</fullName>
                </value>
                <value>
                    <fullName>Fournisseur</fullName>
                </value>
                <value>
                    <fullName>Rachat LPCR</fullName>
                </value>
                <value>
                    <fullName>Ne souhaite pas adhérer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Creche</fullName>
        <active>true</active>
        <label>Crèche</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/LPCR_Preinscription__c.object
<CustomObject>
    <description>Objet servant à stocker les réponses aux formulaires de préinscription remplis par les familles par l&apos;intermédiare de FormAssembly</description>
    <label>Préinscription</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Numéro de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Préinscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Préinscriptions (Crèche)</relationshipLabel>
        <relationshipName>PreinscriptionsCreche</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateEntreeCreche__c</fullName>
        <label>Date d&apos;entrée en crèche</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_PrenomEnfant__c</fullName>
        <label>Prénom de l&apos;enfant</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nouveau</fullName>
                    <default>true</default>
                    <label>Nouveau</label>
                </value>
                <value>
                    <fullName>Liste d’attente</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Recommandation</fullName>
                </value>
                <value>
                    <fullName>Recommandation validée</fullName>
                </value>
                <value>
                    <fullName>Proposition</fullName>
                </value>
                <value>
                    <fullName>Confirmé</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NomEnfant__c</fullName>
        <label>Nom de l&apos;enfant</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/LPCR_StatutInscription.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nouveau</fullName>
        <default>true</default>
        <label>Nouveau</label>
    </customValue>
    <customValue>
        <fullName>Liste attente</fullName>
        <label>Liste d’attente</label>
    </customValue>
    <customValue>
        <fullName>Option</fullName>
    </customValue>
    <customValue>
        <fullName>Recommandation</fullName>
    </customValue>
    <customValue>
        <fullName>Recommandation validée</fullName>
    </customValue>
    <customValue>
        <fullName>Attribuée</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmé</fullName>
    </customValue>
    <customValue>
        <fullName>Inscrit</fullName>
    </customValue>
    <customValue>
        <fullName>Annulé</fullName>
    </customValue>
    <masterLabel>Statut Inscription</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/APC005_PreinscriptionsEnCoursController.cls
/**
* @author Achraf ABOUL
* @date 12/03/2020
* @Description PreinscriptionsEnCours component controller
*/
public with sharing class APC005_PreinscriptionsEnCoursController {
    public APC005_PreinscriptionsEnCoursController() {

    }
    @AuraEnabled(cacheable=true)
    public static String getPreInscriptionsByAcc(Id accId){
        system.debug('Hello from backend');
        System.debug('accId : ' + accId);
        List<WRP001_PreinscriptionWrapper> preinscWrapperList = new List<WRP001_PreinscriptionWrapper>();
        for(LPCR_Preinscription__c eachPreInsc :  EM007_PreinscriptionEntity.getPreinscriptionsByAccId(accId)){
                preinscWrapperList.add(new WRP001_PreinscriptionWrapper(
                    eachPreInsc.Id,
                    eachPreInsc.LPCR_Statut__c, 
                    eachPreInsc.LPCR_Creche__r.Name, 
                    eachPreInsc.NomEnfant__c + ' ' + eachPreInsc.LPCR_PrenomEnfant__c,
                    eachPreInsc.LPCR_DateEntreeCreche__c));
        }
        return JSON.serialize(preinscWrapperList);
    }
    public class WRP001_PreinscriptionWrapper{
        private String recId;
        private String statut;
        private String creche;
        private String nomEnfant;
        private Date dateEntree;
        WRP001_PreinscriptionWrapper(String recId, String statut, String creche, String nomEnfant, Date dateEntree){
          this.recId = recId;
          this.statut = statut;
          this.creche = creche;
          this.nomEnfant = nomEnfant;
          this.dateEntree = dateEntree;
        }
    }
}