mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_IDCompteFamille__c</fullName>
        <label>ID compte famille</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <label>Type de crèche</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ALSH</fullName>
                </value>
                <value>
                    <fullName>MAF</fullName>
                </value>
                <value>
                    <fullName>MICRO</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>Halte-Garderie</fullName>
                </value>
                <value>
                    <fullName>Jardin d’enfants</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeFacturation__c</fullName>
        <label>Type de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingType</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Creche</fullName>
        <active>true</active>
        <label>Crèche</label>
    </recordTypes>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_RenouvellementAutomatique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renouvellement Automatique</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LPCR_TypeFacturation__c</fullName>
        <label>Type de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_TypeCreche__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeCreche__c</fullName>
    <label>Type de crèche</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LPCR_TypeCreche</valueSetName>
    </valueSet>
</CustomField>

mdapiEYH/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeFacturation__c</fullName>
        <label>Type de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingType</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <businessProcess>Opportunité Famille</businessProcess>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/SBQQ__Contracted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Internal flag used to kick off automatic asset and subscription conversion.</description>
    <inlineHelpText>Salesforce CPQ utilise ce champ pour convertir automatiquement les ressources et les abonnements.</inlineHelpText>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__Ordered__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Internal flag that drives automatic order creation.</description>
    <inlineHelpText>Sélectionnez cette case pour créer automatiquement une commande à partir du devis principal.</inlineHelpText>
    <label>Ordered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBQQ__PrimaryQuote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Points to primary quote on this opportunity.</description>
    <inlineHelpText>Salesforce CPQ l&apos;utilise pour pointer vers le devis principal de cette opportunité.</inlineHelpText>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>SBQQ__Quote__c.SBQQ__Opportunity2__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>PrimaryOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/Order.object
<CustomObject>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <description>Valeurs de Type de Creche recoupere depuis Account Creche</description>
        <label>Type de crèche</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LPCR_TypeCreche</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Order/fields/SBQQ__Contracted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the order is contracted.</description>
    <inlineHelpText>Indique si la commande est contractée.</inlineHelpText>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__RenewalUpliftRate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalUpliftRate__c</fullName>
    <description>Rate of renewal price increases.</description>
    <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
    <label>Renewal Uplift (%)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <description>Valeurs de Type de Creche recoupere depuis Account Creche</description>
        <label>Type de crèche</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LPCR_TypeCreche</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeFacturation__c</fullName>
        <label>Type de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Defines the billing frequency.</description>
        <inlineHelpText>Defines the billing frequency.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingFrequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag to drive automatic order creation.</description>
        <inlineHelpText>Select this checkbox to automatically create an order from this quote, if it is a primary quote.</inlineHelpText>
        <label>Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Rate of renewal price increases.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Defines the billing frequency.</description>
        <inlineHelpText>Defines the billing frequency.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingFrequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionPricing__c</fullName>
        <description>Determines how the subscription on this line item is priced. Blank value means this line contains product that&apos;s not a subscription.</description>
        <inlineHelpText>Indicates how the subscription price is calculated. If this is blank, the line items is not a subscription product.</inlineHelpText>
        <label>Subscription Pricing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>Percent Of Total</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/LPCR_TypeCreche.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALSH</fullName>
    </customValue>
    <customValue>
        <fullName>MAF</fullName>
    </customValue>
    <customValue>
        <fullName>MAC</fullName>
    </customValue>
    <customValue>
        <fullName>MICRO</fullName>
    </customValue>
    <customValue>
        <fullName>Halte-Garderie</fullName>
    </customValue>
    <customValue>
        <fullName>Jardin d’enfants</fullName>
    </customValue>
    <customValue>
        <fullName>RAM</fullName>
    </customValue>
    <customValue>
        <fullName>Partenaire</fullName>
    </customValue>
    <customValue>
        <fullName>PAJE</fullName>
    </customValue>
    <masterLabel>Type de crèche</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SBQQ__BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arrieree</fullName>
        <label>Arriérée</label>
    </customValue>
    <customValue>
        <fullName>Anticipee</fullName>
        <label>Anticipée</label>
    </customValue>
    <description>Billing type</description>
    <masterLabel>Billing Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/APB006_PrepaRenewalContract_Test.cls
/**
* @author Dario Correnti
* @date 06/05/2020
* @Description Test Class for APB006_PrepaRenewalContract
*/
@isTest
public class APB006_PrepaRenewalContract_Test {
    
    private static final Integer NUMBER_OF_B2C = 3;
    private static final Integer NUMBER_OF_B2B = 0; // we set this to 0 due to the lookupfilter on Contract.AccountId which force the RT of the related account to (and just to) Famille
    private static final Integer NUMBER_OF_CRECHE = 3;
    private static final Id B2B_RT_ID = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Entreprise);
    private static final Id B2C_RT_ID = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Famille);
    private static final Id CRECHE_RT_ID = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Creche);
        
    @testsetup
    static void setup() {
        List<Account> accountsCreche = new List<Account>();
        List<Account> accounts = new List<Account>();

        for (Integer i = 0; i < NUMBER_OF_B2C; i++) {
            Account tmpAccount = UM002_TestDataFactory.createAccByRT('Customer B2C ' + i, B2C_RT_ID);
            tmpAccount.LPCR_IDCompteFamille__c = 'extId-' + i;
            accounts.add(tmpAccount);
        }

        for (Integer i = 0; i < NUMBER_OF_B2B; i++) {
            Account tmpAccount = UM002_TestDataFactory.createAccByRT('Customer B2B ' + i, B2B_RT_ID);
            accounts.add(tmpAccount);
        }

        for (Integer i = 0; i < NUMBER_OF_CRECHE; i++) {
            Account tmpAccount = UM002_TestDataFactory.createAccByRT('Creche' + i, CRECHE_RT_ID);
            tmpAccount.LPCR_TypeCreche__c = Math.mod(i, 2) == 0
                ? 'MAC'
                : 'MICRO';
            
            accountsCreche.add(tmpAccount);
        }
        //accounts.addAll(accountsCreche);
        insert accounts;
        insert accountsCreche;

        Id standardPricebookId = Test.getStandardPricebookId();
        UM002_TestDataFactory.insertBillingCustomSettings();
        blng__LegalEntity__c billingLegalEntity = UM002_TestDataFactory.setupLegalEntity();
        blng__RevenueRecognitionRule__c revRecRule = UM002_TestDataFactory.setupRevRec(billingLegalEntity.Id);
        blng__BillingRule__c billingRule = UM002_TestDataFactory.setupBillingRule(billingLegalEntity.Id);
        blng__TaxRule__c taxRule = UM002_TestDataFactory.setupTaxRule(billingLegalEntity.Id);

        Product2 prod = UM002_TestDataFactory.createProduct('test', billingRule.Id, revRecRule.Id,taxRule.Id );
        prod.SBQQ__SubscriptionPricing__c ='Fixed Price';
        insert prod;
        
        PricebookEntry priceBookEntry1 = UM002_TestDataFactory.createPricebookEntry(standardPricebookId,prod.Id);
        insert priceBookEntry1;
        
        //create 2 oppty for each customer
        List<Opportunity> opps = UM002_TestDataFactory.createOpportunities((NUMBER_OF_B2C + NUMBER_OF_B2B) * 2, 'test', 'Prospecting');
        insert opps;

        List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
        Integer counter = 0;
        for (Integer i = 0; i < accounts.size(); i++) {
            if (accounts.get(i).recordTypeId != CRECHE_RT_ID) {
                SBQQ__Quote__c tmpPrimaryQuote1 = UM002_TestDataFactory.createQuote('test', opps.get(counter++).Id, accounts.get(i).Id, standardPricebookId, 'Quote');
                tmpPrimaryQuote1.SBQQ__Primary__c = true;
                quotes.add(tmpPrimaryQuote1);

                SBQQ__Quote__c tmpPrimaryQuote2 = UM002_TestDataFactory.createQuote('test', opps.get(counter++).Id, accounts.get(i).Id, standardPricebookId, 'Quote');
                tmpPrimaryQuote2.SBQQ__Primary__c = true;
                quotes.add(tmpPrimaryQuote2);
            }
        }
        insert quotes;
        
        List<SBQQ__QuoteLine__c> qlines = new List<SBQQ__QuoteLine__c> ();
        List<Opportunity> opptToUpdate = new List<Opportunity> ();
        for (SBQQ__Quote__c q : quotes) {
            qlines.add(UM002_TestDataFactory.createQuoteLine(prod.Id, q.Id, priceBookEntry1.Id, 200, 1));
            opptToUpdate.add(new Opportunity(id = q.SBQQ__Opportunity2__c, SBQQ__PrimaryQuote__c = q.Id));

            q.SBQQ__Ordered__c = true; 
            q.LPCR_IndexationConvenue__c = 'Oui';
            q.LPCR_TypeFacturation__c = 'Arrears';
            q.SBQQ__BillingFrequency__c = 'Invoice Plan';
            q.SBQQ__RenewalUpliftRate__c = 2;
        }
        insert qlines;
        update opptToUpdate;
        update quotes;
        
        List<Order> orders = [SELECT Id , SBQQ__Contracted__c, Status, OpportunityId, EffectiveDate, AccountId, SBQQ__Quote__c FROM Order];
        System.debug('### check 000 orders : ' + orders.size());
        for (Order order : orders) {
            order.status = 'Activated';
            //order.SBQQ__Contracted__c=true; 
        }
        update orders;

        List<Contract> contracts = new List<Contract>();
        Map<Id, Id> crecheByCustomer = new Map<Id, Id>();
        counter = 0;
        for (Order order : orders) {
            Contract tmpContract = UM002_TestDataFactory.createContract(order.AccountId, order.SBQQ__Quote__c, order.Id);
            tmpContract.LPCR_RenouvellementAutomatique__c = true;
            tmpContract.StartDate = System.today().addMonths(-1);
            tmpContract.SBQQ__RenewalQuoted__c = false;
            tmpContract.ContractTerm = 1;
            if (!crecheByCustomer.containsKey(order.AccountId)) {
                crecheByCustomer.put(order.AccountId, accountsCreche.get(Math.mod(counter++, 2)).Id);
            } 

            tmpContract.LPCR_Creche__c = crecheByCustomer.get(order.AccountId);
            //tmpContract.Status='Activated';

            contracts.add(tmpContract);
        }
        insert contracts; 

        // adjust contract LPCR_JoursAvance__c
        contracts = [SELECT Id, LPCR_JoursAvance__c, EndDate FROM Contract];
        for (Contract c : contracts) {
            Integer diffEndDate = c.EndDate.daysBetween(System.today());
            c.LPCR_JoursAvance__c = c.EndDate < System.today()
                ? diffEndDate
                : -1 * diffEndDate;
        }

        update contracts;

        for (Contract c : contracts) {
            c.Status='Activated';
        }
        update contracts;
    }

    @isTest
    private static void testAPB006PrepaRenewalContract(){
        System.runAs(UM002_TestDataFactory.createUser()){
            Test.startTest();
            APB006_PrepaRenewalContract btch = new APB006_PrepaRenewalContract();
            Database.executeBatch(btch, 2000);
            Test.stopTest();

            List<Contract> listAllContracts = [SELECT Id, SBQQ__Order__c, TECH_AjoutFraisGestion__c, LPCR_TypeFacturation__c, Status, StartDate, ContractTerm,LPCR_DateRenouvellement__c,LPCR_RenouvellementAutomatique__c, SBQQ__RenewalQuoted__c, LPCR_JoursAvance__c, SBQQ__RenewalForecast__c, EndDate FROM Contract];
            List<Contract> listContractsWithFees = [SELECT Id, SBQQ__Order__c, TECH_AjoutFraisGestion__c, LPCR_TypeFacturation__c, Status, StartDate, ContractTerm,LPCR_DateRenouvellement__c,LPCR_RenouvellementAutomatique__c, SBQQ__RenewalQuoted__c, LPCR_JoursAvance__c, SBQQ__RenewalForecast__c, EndDate FROM Contract WHERE TECH_AjoutFraisGestion__c = true];

            // Assert to verify that just a subset of contract (50% - 1 for each pair customer / creche) have been updated by the batch 
            System.assertEquals((NUMBER_OF_B2C + NUMBER_OF_B2B) * 2, listAllContracts.size());
            System.assertEquals(NUMBER_OF_B2C + NUMBER_OF_B2B, listContractsWithFees.size());
        }
    }
}