mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_PasDeSIRET__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pas de numéro de SIRET</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/LPCR_ContactAEnvoyer__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactAEnvoyer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact A Envoyer</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/LPCR_Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Nom de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Purgé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TargetObject__c</fullName>
        <label>Target Object</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SM025_SendContact_Callout_Test.cls
@isTest
public with sharing class SM025_SendContact_Callout_Test {
    @isTest
    private static void SM025_SendContact_Callout_Test() {

        Test.setMock(HttpCalloutMock.class, new MCK001_LPCRHttpCalloutMockImpl());

        Id entrepriseRecTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Entreprise);
        //Id entrepriseRecTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Famille);
        Account  acc1 = new Account(Name = 'name1z',recordtypeid=entrepriseRecTypeId,LPCR_PASDESIRET__C=true);
        insert acc1;

        Contact c = new Contact(    FirstName = 'first',
                        	Lastname = 'last',
                        	AccountId = acc1.id,
                        	Email = 'firstlast@gmail.com');
        Test.startTest();
        insert c;
        Test.stopTest();

        LPCR_Log__c log = [SELECT id,LPCR_Result__c from LPCR_Log__c where LPCR_TargetObject__c =: c.id limit 1];
        System.assertEquals(UM010_Constant.SUCCESS, log.LPCR_Result__c);
        System.assertEquals(c.LPCR_ContactAEnvoyer__c, false);
        
    }
}