mdapiEYH/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/LPCR_Commentaire__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Commentaire__c</fullName>
    <label>Commentaire</label>
    <type>TextArea</type>
</CustomField>

mdapiEYH/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_StatutFacture__c</fullName>
        <label>Statut De La Facture</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brouillon</fullName>
                </value>
                <value>
                    <fullName>A Envoyer</fullName>
                </value>
                <value>
                    <fullName>Envoyée</fullName>
                </value>
                <value>
                    <fullName>Signée</fullName>
                </value>
                <value>
                    <fullName>Annulée</fullName>
                </value>
                <value>
                    <fullName>Terminée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__InvoiceRunCreatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship to the Invoice Run.Invoice is child of  Invoice Run.
This field tells from which Invoice Run the Invoice is generated.</description>
        <label>Invoice Run (Created By)</label>
        <referenceTo>blng__InvoiceRun__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>InvoiceRunInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__InvoiceStatus__c</fullName>
        <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__InvoiceStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_Commentaire__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Commentaire__c</fullName>
    <label>Commentaire</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/blng__InvoiceRun__c/blng__InvoiceRun__c.object-meta.xml
<CustomObject>
    <description>Stores the details of how many Invoices generated,how many Accounts processed &amp; Credit Notes generated.</description>
    <label>Invoice Run</label>
    <nameField>
        <label>Invoice Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__InvoiceRun__c/fields/LPCR_EnvoyerFaitPar__c.field-meta.xml
<CustomField>
    <fullName>LPCR_EnvoyerFaitPar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action Envoyer fait par</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoice_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/APB011_SetInvoiceCommentaire_Test.cls
/**
* @author Hanae Makboub
* @date 29/06/2020
* @Description test class for Batch for filling the "commentaire" field each time the button "A envoyer" is clicked
*/
@isTest
public class APB011_SetInvoiceCommentaire_Test {
	@testsetup
    static void setup() {
        Account acc = UM002_TestDataFactory.createAccount('testAccount');
        insert acc;
        List<blng__InvoiceRun__c> invoiceRunsList = UM002_TestDataFactory.createInvoiceRuns(1,'Execution de Facture',date.newInstance(System.Today().year(), 10, 02));
        insert invoiceRunsList;
        blng__InvoiceRun__c invoiceRun = invoiceRunsList.get(0);
        List<blng__Invoice__c> invoicesList = UM002_TestDataFactory.createInvoices(10,acc.id,invoiceRun.id,'Posted','Brouillon' );
        insert invoicesList;
        List<blng__Invoice__c> pretInvoicesList = UM002_TestDataFactory.createInvoices(10,acc.id,invoiceRun.id,'Posted','A Envoyer' );
        insert pretInvoicesList;
    }
    
    @isTest
    private static void testAPB011_SetInvoiceCommentaire(){
        System.runAs(UM002_TestDataFactory.createUser()){
            Test.startTest();
            APB011_SetInvoiceCommentaire InvoiceRunBatch0 = new APB011_SetInvoiceCommentaire();
            APB011_SetInvoiceCommentaire InvoiceRunBatch = new APB011_SetInvoiceCommentaire('SELECT Id, Name, OwnerId, LPCR_EnvoyerFaitPar__c FROM blng__InvoiceRun__c');
            InvoiceRunBatch.execute(null);
            Test.stopTest();
            List<blng__Invoice__c> invoices = [SELECT Id, blng__InvoiceStatus__c,LPCR_Commentaire__c ,blng__InvoiceRunCreatedBy__c , Name , LPCR_StatutFacture__c FROM blng__Invoice__c 
                                                WHERE blng__InvoiceStatus__c = 'Posted' AND LPCR_StatutFacture__c = 'Brouillon' ];
            for(blng__Invoice__c eachInvoice : invoices){
            	System.assertEquals(eachInvoice.LPCR_Commentaire__c, 'Le statut des factures devrait être Prêt à valider pour pouvoir les envoyer', 'Le commentaire est incorrecte');
            }
            List<blng__Invoice__c> pretInvoices = [SELECT Id, blng__InvoiceStatus__c,LPCR_Commentaire__c ,blng__InvoiceRunCreatedBy__c , Name , LPCR_StatutFacture__c FROM blng__Invoice__c 
                                                WHERE blng__InvoiceStatus__c = 'Posted' AND LPCR_StatutFacture__c = 'Prêt à valider' ];
            for(blng__Invoice__c eachInvoice : pretInvoices){
            	System.assertEquals(eachInvoice.LPCR_StatutFacture__c, 'A Envoyer', 'le statut de la facture ne change pas');
            }
            
        }
        
    }
}