mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Ancien client</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
                <value>
                    <fullName>Ex-adhérent</fullName>
                </value>
                <value>
                    <fullName>Fournisseur</fullName>
                </value>
                <value>
                    <fullName>Rachat LPCR</fullName>
                </value>
                <value>
                    <fullName>Ne souhaite pas adhérer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ContactEnfant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactEnfant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Enfant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact Enfant)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/LPCR_ModificationEntrante__c.object
<CustomObject>
    <description>Cet objet nous permettra de collecter les données en provenance d&apos;Intranet et de la GTA  concernant des événements et liés à de l&apos;usage sur SF (absences, heures déduites, maladie ...)</description>
    <label>Modification Entrante</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modifications Entrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Compte__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteCompte</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enfant, Parent 1 et 2</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contrat Salesforce</description>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteContrat</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Devis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Devis</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteDevis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Evenement__c</fullName>
        <label>Evènement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Modification Adresse Contact Parent</fullName>
                </value>
                <value>
                    <fullName>Modification Autorité Parentale</fullName>
                </value>
                <value>
                    <fullName>Modification Numéro Allocataire</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Handicapé Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Type Accueil</fullName>
                </value>
                <value>
                    <fullName>Modification Type Planning</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Montant Ressource</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Jour Congé</fullName>
                </value>
                <value>
                    <fullName>Date Fin Contrat</fullName>
                </value>
                <value>
                    <fullName>Modification Section</fullName>
                </value>
                <value>
                    <fullName>Date Naissance Enfant</fullName>
                </value>
                <value>
                    <fullName>Modification Mode Garde</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Familiale</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Mois Mensualisé</fullName>
                </value>
                <value>
                    <fullName>Modification Traitement Jour férié</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Modification Délai Carence</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Supplémentaire MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Occasionnel MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Congés MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Déduite MAC</fullName>
                </value>
                <value>
                    <fullName>Validation Contrat Directrice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_Quantite__c</fullName>
        <label>Quantité</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LPCR_RessourceFamille__c</fullName>
        <label>Ressource Famille</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A valider</fullName>
                    <default>true</default>
                    <label>A valider</label>
                </value>
                <value>
                    <fullName>Validée</fullName>
                </value>
                <value>
                    <fullName>Refusée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/LPCR_ModificationEntrante__c/fields/LPCR_DateEffet__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateEffet__c</fullName>
    <label>DateEffet</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LPCR_ModificationEntrante__c/fields/LPCR_EtatTraitement__c.field-meta.xml
<CustomField>
    <fullName>LPCR_EtatTraitement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LPCR EtatTraitement</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/LPCR_RessourceFamille__c.object
<CustomObject>
    <label>Ressource Famille</label>
    <nameField>
        <label>Ressource Famille Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ressources Familles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_CompteFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte Famille</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ressources Familles</relationshipLabel>
        <relationshipName>Ressources_Familles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Enfant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ressources Familles</relationshipLabel>
        <relationshipName>Ressources_Familles</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <businessProcess>Opportunité Famille</businessProcess>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Enfant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Devis (Contact Enfant)</relationshipLabel>
        <relationshipName>Devis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Envoi directrice</fullName>
                </value>
                <value>
                    <fullName>Validé directrice</fullName>
                </value>
                <value>
                    <fullName>Prêt à envoyer</fullName>
                </value>
                <value>
                    <fullName>Envoyé pour signature</fullName>
                </value>
                <value>
                    <fullName>Signé</fullName>
                </value>
                <value>
                    <fullName>Actif</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/APB014_ModificationEntrante_Test.cls
@isTest
public class APB014_ModificationEntrante_Test {

    @isTest
    static void APB014_TraitementModificationEntrante_Test() {

        Account acc = UM002_TestDataFactory.createAccount('test acc');
        insert acc;
        Account acc2 = UM002_TestDataFactory.createAccount('test2 acc');
        insert acc2;
        Contract contract = UM002_TestDataFactory.createContract(acc.id);	
        insert contract;

        List<Opportunity> oppties = UM002_TestDataFactory.createOpportunities(1, 'test opp', 'Prospecting');
        insert oppties;

        SBQQ__Quote__c quote = UM002_TestDataFactory.createQuotes(1, new List<Account>{acc}, oppties).get(0);
        insert quote;

        contract.SBQQ__Quote__c = quote.id;
        update contract;

        Id rtContactFamille = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName('Contact', 'Famille' );
        Contact contact = UM002_TestDataFactory.createContact('test contact', rtContactFamille);
        insert contact;

        LPCR_RessourceFamille__c rf = new LPCR_RessourceFamille__c();
        rf.LPCR_CompteFamille__c = acc2.id;
        rf.LPCR_ContactEnfant__c = contact.id;
        insert rf;

        LPCR_ModificationEntrante__c tempModif = new LPCR_ModificationEntrante__c(LPCR_Devis__c  = quote.Id,LPCR_Contract__c = contract.Id,LPCR_Evenement__c  = 'Validation Contrat Directrice');
        tempModif.LPCR_DateEffet__c = Date.today().addDays(-1);
        tempModif.LPCR_EtatTraitement__c = false;
        tempModif.LPCR_Statut__c = 'Validée';
        tempModif.LPCR_Quantite__c = 1;
        tempModif.LPCR_Compte__c = acc2.id ;
        tempModif.LPCR_Contact__c = contact.id;
        insert tempModif;

        Test.startTest();
        APB014_TraitementModificationEntrante sc1 = new APB014_TraitementModificationEntrante();
        sc1.execute(null);
        Test.stopTest();


        LPCR_ModificationEntrante__c afterModif = [SELECT id,LPCR_EtatTraitement__c FROM LPCR_ModificationEntrante__c WHERE LPCR_Evenement__c='Validation Contrat Directrice'];
        SBQQ__Quote__c afterQuote = [SELECT id,SBQQ__Status__c FROM SBQQ__Quote__c WHERE SBQQ__Account__c=:acc.id];

        System.assertEquals(true, afterModif.LPCR_EtatTraitement__c);
        System.assertEquals(afterQuote.SBQQ__Status__c, 'Validé directrice');

    }
}