mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Ancien client</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
                <value>
                    <fullName>Ex-adhérent</fullName>
                </value>
                <value>
                    <fullName>Fournisseur</fullName>
                </value>
                <value>
                    <fullName>Rachat LPCR</fullName>
                </value>
                <value>
                    <fullName>Ne souhaite pas adhérer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Enfant</fullName>
        <active>true</active>
        <label>Enfant</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutJeudi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutJeudi__c</fullName>
    <label>Heure de début jeudi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutLundi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutLundi__c</fullName>
    <label>Heure de début lundi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutMardi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutMardi__c</fullName>
    <label>Heure de début mardi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutMercredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutMercredi__c</fullName>
    <label>Heure de début mercredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutVendredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutVendredi__c</fullName>
    <label>Heure de début vendredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinJeudi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinJeudi__c</fullName>
    <label>Heure de fin jeudi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinLundi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinLundi__c</fullName>
    <label>Heure de fin lundi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinMardi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinMardi__c</fullName>
    <label>Heure de fin mardi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinMercredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinMercredi__c</fullName>
    <label>Heure de fin mercredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinVendredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinVendredi__c</fullName>
    <label>Heure de fin vendredi</label>
    <type>Time</type>
</CustomField>

mdapiEYH/objects/LPCR_ParametrageScore__c.object
<CustomObject>
    <label>Paramétrage Score</label>
    <nameField>
        <label>Nom de Paramétrage Score</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paramétrages Score</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_ReponseCrecheMunicipale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Réponse crèche municipale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LPCR_Revenu__c</fullName>
        <label>Revenu</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LPCR_Score__c</fullName>
        <label>Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapiEYH/objects/LPCR_Preinscription__c.object
<CustomObject>
    <description>Objet servant à stocker les réponses aux formulaires de préinscription remplis par les familles par l&apos;intermédiare de FormAssembly</description>
    <label>Préinscription</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Numéro de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Préinscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_CompteFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte Famille</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Préinscriptions (Compte Famille)</relationshipLabel>
        <relationshipName>PreinscriptionsFamille</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateEntreeCreche__c</fullName>
        <label>Date d&apos;entrée en crèche</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateEntreeEntreprise__c</fullName>
        <label>Date d&apos;entrée dans l&apos;entreprise</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutJeudi__c</fullName>
        <label>Heure de début jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutLundi__c</fullName>
        <label>Heure de début lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMardi__c</fullName>
        <label>Heure de début mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMercredi__c</fullName>
        <label>Heure de début mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutVendredi__c</fullName>
        <label>Heure de début vendredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinJeudi__c</fullName>
        <label>Heure de fin jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinLundi__c</fullName>
        <label>Heure de fin lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMardi__c</fullName>
        <label>Heure de fin mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMercredi__c</fullName>
        <label>Heure de fin mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinVendredi__c</fullName>
        <label>Heure de fin vendredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_PrenomEnfant__c</fullName>
        <label>Prénom de l&apos;enfant</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_ReponseCrecheMunicipale__c</fullName>
        <label>Reponse crèche municipale</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_Revenu__c</fullName>
        <label>Revenu</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LPCR_Score__c</fullName>
        <description>score obtenu suivant les critères définis pour l&apos;entreprise</description>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nouveau</fullName>
                    <default>true</default>
                    <label>Nouveau</label>
                </value>
                <value>
                    <fullName>Liste d’attente</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Recommandation</fullName>
                </value>
                <value>
                    <fullName>Recommandation validée</fullName>
                </value>
                <value>
                    <fullName>Proposition</fullName>
                </value>
                <value>
                    <fullName>Confirmé</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NomEnfant__c</fullName>
        <label>Nom de l&apos;enfant</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/LPCR_StatutInscription.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nouveau</fullName>
        <default>true</default>
        <label>Nouveau</label>
    </customValue>
    <customValue>
        <fullName>Liste attente</fullName>
        <label>Liste d’attente</label>
    </customValue>
    <customValue>
        <fullName>Option</fullName>
    </customValue>
    <customValue>
        <fullName>Recommandation</fullName>
    </customValue>
    <customValue>
        <fullName>Recommandation validée</fullName>
    </customValue>
    <customValue>
        <fullName>Attribuée</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmé</fullName>
    </customValue>
    <customValue>
        <fullName>Inscrit</fullName>
    </customValue>
    <customValue>
        <fullName>Annulé</fullName>
    </customValue>
    <masterLabel>Statut Inscription</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SM009_ParametrageScoreServices_Test.cls
/**
* @author Ayoub Ouarti
* @created 27/02/2020
* @description Test Class of SM009_ParametrageScoreServices.
*/
@isTest
public class SM009_ParametrageScoreServices_Test {
    
    @testSetup 
    
    static void testSetup(){
        Id enfantContactRecordTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName('Contact', 'Enfant');
        Account acc = UM002_TestDataFactory.createAccount('test');
        insert acc;
        UM002_TestDataFactory.ContactTdf c = new UM002_TestDataFactory.ContactTdf();
        Contact contact= c.create('Test','Test', acc);
        contact.RecordTypeId = enfantContactRecordTypeId;
        insert contact;
        LPCR_Preinscription__c  preinsciption = UM002_TestDataFactory.createPreinscription('test', 'test',acc.Id,contact.Id );
        preinsciption.LPCR_HeureDebutLundi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinLundi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_HeureDebutMardi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinMardi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_HeureDebutMercredi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinMercredi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_HeureDebutJeudi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinJeudi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_HeureDebutVendredi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinVendredi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        
        preinsciption.LPCR_ReponseCrecheMunicipale__c='Non';
        preinsciption.LPCR_DateEntreeCreche__c= Date.newInstance(2020, 09, 01);
        preinsciption.LPCR_DateEntreeEntreprise__c = Date.today().addDays(-3);
        preinsciption.LPCR_Revenu__c =12000;

        
        insert preinsciption;
        
        
        List<LPCR_ParametrageScore__c> listParams = UM002_TestDataFactory.createParametrageScores (acc.Id);       
        insert listParams;
    }        
    
    //Test the method setPreinscriptionScore_Test from SM009_ParametrageScoreServices
    @isTest
    public static void setPreinscriptionScore_Test(){
        
        LPCR_Preinscription__c  preinsciption  = [SELECT LPCR_Score__c, LPCR_Statut__c,LPCR_PrenomEnfant__c,NomEnfant__c,LPCR_CompteFamille__c FROM LPCR_Preinscription__c WHERE LPCR_PrenomEnfant__c = 'test'];
        
        Test.startTest();
        System.runAs(UM002_TestDataFactory.createUser()){
            preinsciption.LPCR_Statut__c = 'Confirmé';
            update preinsciption;
            preinsciption  = [SELECT LPCR_ReponseCrecheMunicipale__c,LPCR_Score__c FROM LPCR_Preinscription__c WHERE LPCR_PrenomEnfant__c = 'test'];
            System.assertEquals(450,preinsciption.LPCR_Score__c,'Error in SM009_ParametrageScoreServices_Test.setPreinscriptionScore_Test : LPCR_Preinscription__c.LPCR_Score__c is wrong');
            preinsciption.LPCR_ReponseCrecheMunicipale__c='Oui';
            update preinsciption; 
            preinsciption  = [SELECT LPCR_ReponseCrecheMunicipale__c,LPCR_Score__c FROM LPCR_Preinscription__c WHERE LPCR_PrenomEnfant__c = 'test'];
            System.assertEquals(420,preinsciption.LPCR_Score__c,'Error in SM009_ParametrageScoreServices_Test.setPreinscriptionScore_Test : LPCR_Preinscription__c.LPCR_Score__c is wrong');
          
        }
        Test.stopTest();
        
    }
}