mdapiEYH/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/SBQQ__RenewalModel__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalModel__c</fullName>
    <description>The option to distinguish between Subscription or Asset based renewal.</description>
    <inlineHelpText>Sélectionnez Basé sur les ressources pour générer les renouvellements en fonction des ressources d&apos;un compte ou Basé sur le contrat pour générer les renouvellements en fonction du contrat créé à partir d&apos;un devis.</inlineHelpText>
    <label>Renewal Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asset Based</fullName>
            </value>
            <value>
                <fullName>Contract Based</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SBQQ__RenewalPricingMethod__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalPricingMethod__c</fullName>
    <description>Method for pricing products on renewal.</description>
    <inlineHelpText>Utilisez « Identique » pour conserver le dernier prix payé, « Catalogue » pour utiliser le prix catalogue actuel ou « Augmentation » pour utiliser le dernier prix payé avec une augmentation.</inlineHelpText>
    <label>Renewal Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Same</fullName>
                <default>true</default>
                <label>Same</label>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
            <value>
                <fullName>Uplift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TM000_TriggerHandler_Test.cls
@isTest
public with sharing class TM000_TriggerHandler_Test {
    @isTest
    static void TM000_TriggerHandler_Test() {


        TM001_AccountTriggerHandler accTrigg = new TM001_AccountTriggerHandler();
        accTrigg.setMaxLoopCount(50);
        accTrigg.clearMaxLoopCount();

        Account acc = UM002_TestDataFactory.createAccount('test');
        insert acc;

        acc.SBQQ__RenewalModel__c = 'Contract Based';
        update acc;

        acc.SBQQ__RenewalPricingMethod__c = 'Uplift';
        upsert acc;

        delete acc;

        undelete acc;
    }
}