mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_Representant1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Représentant 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Représentant N°1</relationshipLabel>
        <relationshipName>Representant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Ancien client</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
                <value>
                    <fullName>Ex-adhérent</fullName>
                </value>
                <value>
                    <fullName>Fournisseur</fullName>
                </value>
                <value>
                    <fullName>Rachat LPCR</fullName>
                </value>
                <value>
                    <fullName>Ne souhaite pas adhérer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lien vers la crèche porteuse du contrat</description>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Le compte n&apos; a pas un type d&apos;enregistrement = Crèche</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Crèche</value>
            </filterItems>
            <infoMessage>type d&apos;enregistrement = Crèche</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contrats de la crèche</relationshipLabel>
        <relationshipName>Contrats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Debut</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ContactEnfant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactEnfant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Enfant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact Enfant)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_ContactRepresentant1__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactRepresentant1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Représentant 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Famille</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Contact Représentant 1)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/LPCR_Preinscription__c.object
<CustomObject>
    <description>Objet servant à stocker les réponses aux formulaires de préinscription remplis par les familles par l&apos;intermédiare de FormAssembly</description>
    <label>Préinscription</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Numéro de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Préinscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_CompteFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte Famille</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Préinscriptions (Compte Famille)</relationshipLabel>
        <relationshipName>PreinscriptionsFamille</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <label>Contact Enfant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Enfant</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Préinscriptions</relationshipLabel>
        <relationshipName>Preinscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LPCR_ContactParent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Parent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Préinscriptions (Contact Parent)</relationshipLabel>
        <relationshipName>PreinscriptionsParent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Préinscriptions (Crèche)</relationshipLabel>
        <relationshipName>PreinscriptionsCreche</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateEntreeCreche__c</fullName>
        <label>Date d&apos;entrée en crèche</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_PrenomEnfant__c</fullName>
        <label>Prénom de l&apos;enfant</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nouveau</fullName>
                    <default>true</default>
                    <label>Nouveau</label>
                </value>
                <value>
                    <fullName>Liste d’attente</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Recommandation</fullName>
                </value>
                <value>
                    <fullName>Recommandation validée</fullName>
                </value>
                <value>
                    <fullName>Proposition</fullName>
                </value>
                <value>
                    <fullName>Confirmé</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypePreinscription__c</fullName>
        <label>Type Préinscription</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DEF</fullName>
                    <default>true</default>
                    <label>DEF</label>
                </value>
                <value>
                    <fullName>DSP</fullName>
                </value>
                <value>
                    <fullName>OCC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_ValidationFormulaire__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validation Formulaire</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NomEnfant__c</fullName>
        <label>Nom de l&apos;enfant</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <businessProcess>Opportunité Famille</businessProcess>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Enfant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Devis (Contact Enfant)</relationshipLabel>
        <relationshipName>Devis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ContactRepresentant1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Représentant 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Parent</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Devis (Contact Représentant 1)</relationshipLabel>
        <relationshipName>Devis1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Creche</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Crèche)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/LPCR_StatutInscription.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nouveau</fullName>
        <default>true</default>
        <label>Nouveau</label>
    </customValue>
    <customValue>
        <fullName>Liste attente</fullName>
        <label>Liste d’attente</label>
    </customValue>
    <customValue>
        <fullName>Option</fullName>
    </customValue>
    <customValue>
        <fullName>Recommandation</fullName>
    </customValue>
    <customValue>
        <fullName>Recommandation validée</fullName>
    </customValue>
    <customValue>
        <fullName>Attribuée</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmé</fullName>
    </customValue>
    <customValue>
        <fullName>Inscrit</fullName>
    </customValue>
    <customValue>
        <fullName>Annulé</fullName>
    </customValue>
    <masterLabel>Statut Inscription</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SM006_PreinscriptionServices.cls
/**
* @author Ayoub Ouarti
* @created 25/02/2020
* @description Services class on Preinscription Object
* @Updated by hanae on 12/03/2020
* @Updated by Achraf ABOUL (aaboul@salesforce.com) on 04/05/2020
*/
public class SM006_PreinscriptionServices {
    
    /*
* Generate Oppty & Contract for preinscriptions 
*/
    
    public static void generateOpptyAndQuote(Map<Id, LPCR_Preinscription__c> newPreinscrisMap,Map<Id, LPCR_Preinscription__c> oldPreinscrisMap){
        
        //Map: (Preinscription Id => Opportunity)
        Map<Id, Opportunity> preiscIDToOpportunityMap = new Map<Id, Opportunity>();
        List<SBQQ__Quote__c> listQuotes = new List<SBQQ__Quote__c>();
        //Map (Preinscription Id => Account Id (Compte famille))
        Map<Id, Id> preinscIDToAccountIdMap = new Map<Id, Id>();
        //Creation of opportunities for preinscriptions
        Id familleOpportunityRT = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(System.Label.LPCR_Opportunity,System.Label.LPCR_Famille);
        for(LPCR_Preinscription__c eachNewPreinscri : newPreinscrisMap.values()){
            //Add a new opportunity to the oppts map
            if(eachNewPreinscri.LPCR_Statut__c != oldPreinscrisMap.get(eachNewPreinscri.Id).LPCR_Statut__c 
                && Label.LPCR_Confirme.equals(eachNewPreinscri.LPCR_Statut__c))
               /*&& (
                    Label.LPCR_Entreprise.equals(eachNewPreinscri.LPCR_TypePreinscription__c) 
                   ||  Label.LPCR_DSP.equals(eachNewPreinscri.LPCR_TypePreinscription__c) 
               )*/{
                   preiscIDToOpportunityMap.put(eachNewPreinscri.Id, new Opportunity( 
                       RecordTypeId = familleOpportunityRT,
                       AccountId = eachNewPreinscri.LPCR_CompteFamille__c, 
                       Name = Label.LPCR_OppFor+eachNewPreinscri.LPCR_PrenomEnfant__c + ' ' + eachNewPreinscri.NomEnfant__c,
                       StageName = Label.LPCR_Prospecting,
                       CloseDate = Date.today()));
               }
            //Put a new entry in preinscIDToAccountIdMap
            preinscIDToAccountIdMap.put(eachNewPreinscri.Id, eachNewPreinscri.LPCR_CompteFamille__c);
        }
        //Map ( Account Id => Account Record) (comptes familles)
        Map<Id, Account> accountsMap = new Map<Id, Account>([SELECT Id, LPCR_Representant1__c FROM Account WHERE Id IN :preinscIDToAccountIdMap.values()]);
        
        //Insert the new opportunities
        EM004_OpportunityEntity.saveOrUpdte(preiscIDToOpportunityMap.values());
        Id accueilQuoteRecordTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(System.Label.LPCR_Quote,System.Label.LPCR_ContratA);
        Opportunity currentOpportunity;
        LPCR_Preinscription__c currentPreInscr;
       //Creation of new quotes for each preinscription & update of the related Famille account 
        for(Id eachPreinscId : preiscIDToOpportunityMap.keySet()){
            //Add a new Quote for the preinscription
            currentOpportunity = preiscIDToOpportunityMap.get(eachPreinscId);
            currentPreInscr = newPreinscrisMap.get(eachPreinscId);
            listQuotes.add(new SBQQ__Quote__c(
                RecordTypeId = accueilQuoteRecordTypeId,
                LPCR_DateDebut__c = currentPreInscr.LPCR_DateEntreeCreche__c,
                SBQQ__Account__c = currentPreInscr.LPCR_CompteFamille__c,
                LPCR_ContactEnfant__c = currentPreInscr.LPCR_ContactEnfant__c,
                LPCR_Creche__c = currentPreInscr.LPCR_Creche__c,
                LPCR_ContactRepresentant1__c = currentPreInscr.LPCR_ContactParent__c,
                SBQQ__Opportunity2__c = currentOpportunity.Id));
            //Update of the related "Famille" account
            if(preinscIDToAccountIdMap.get(eachPreinscId) != null && accountsMap.get(preinscIDToAccountIdMap.get(eachPreinscId)) != null)
            accountsMap.get(preinscIDToAccountIdMap.get(eachPreinscId)).put('LPCR_Representant1__c', currentPreInscr.LPCR_ContactParent__c);
        }
        EM006_QuoteEntity.saveOrUpdte(listQuotes);
        update accountsMap.values();
        
    }
    
    //commented in the context of bug/IS-1356
   /* public static void setStatusWhenValidateFormulaireIsTrue(Map<Id,LPCR_Preinscription__c> mapNewPreinscription,Map<Id,LPCR_Preinscription__c> mapOldPreinscription){
        for(LPCR_Preinscription__c eachPreinscription : mapNewPreinscription.values()){
            if(eachPreinscription.LPCR_ValidationFormulaire__c && mapOldPreinscription.get(eachPreinscription.Id).LPCR_ValidationFormulaire__c != eachPreinscription.LPCR_ValidationFormulaire__c ){
                eachPreinscription.LPCR_Statut__c=Label.LPCR_ListeAtt;               
            }  
        }
    }
    
    public static void setStatusWhenValidateFormulaireIsTrue(List<LPCR_Preinscription__c> preinscriptions){
        for(LPCR_Preinscription__c eachPreinscription : preinscriptions){
            if(eachPreinscription.LPCR_ValidationFormulaire__c ){eachPreinscription.LPCR_Statut__c=Label.LPCR_ListeAtt;               
                                                                }
        }
    }*/
    
    
}