mdapiEYH/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/LPCR_ProcessRevenuCascade__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ProcessRevenuCascade__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Process Waterfall Revenue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__Balance__c.field-meta.xml
<CustomField>
    <fullName>blng__Balance__c</fullName>
    <formula>blng__TotalAmount__c -  blng__Allocations__c +  blng__Unallocations__c - blng__Debits__c - blng__Refunds__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Montant de la note de crédit qui n’a pas été alloué ou remboursé</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/blng__CreditNote__c/fields/blng__Status__c.field-meta.xml
<CustomField>
    <fullName>blng__Status__c</fullName>
    <inlineHelpText>Statut actuel de la note de crédit. Cela peut être : Brouillon Publié Annulé</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>blng__PostingStatus</valueSetName>
    </valueSet>
</CustomField>

mdapiEYH/objects/blng__CreditNoteAllocation__c.object
<CustomObject>
</CustomObject>

mdapiEYH/objects/blng__CreditNoteLine__c.object
<CustomObject>
    <label>Credit Note Line</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Note Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__Balance__c</fullName>
        <formula>blng__TotalAmount__c - blng__Allocations__c + blng__Unallocations__c -  blng__Refunds__c - blng__Debits__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount that has not yet been allocated</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__CreditNote__c</fullName>
        <label>Credit Note</label>
        <referenceTo>blng__CreditNote__c</referenceTo>
        <relationshipName>CreditNoteCreditLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__InvoiceLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Line</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Draft Invoice Lines would not be available</errorMessage>
            <filterItems>
                <field>blng__InvoiceLine__c.blng__InvoiceLineStatus__c</field>
                <operation>notEqual</operation>
                <value>Draft</value>
            </filterItems>
            <infoMessage>Draft Invoice Lines would not be available</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__InvoiceLine__c</referenceTo>
        <relationshipLabel>Credit Note Lines</relationshipLabel>
        <relationshipName>InvoiceLineCreditNoteLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>blng__Status__c</fullName>
        <inlineHelpText>Status of the credit memo. Can be: Draft Posted Canceled</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__PostingStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>Total Amount should be same as invoice line amount</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

mdapiEYH/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__Account__c</fullName>
        <inlineHelpText>Rechercher dans le compte la facturation de cette facture.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>AccountInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__Balance__c</fullName>
        <formula>blng__TotalAmount__c - blng__Payments__c - blng__Credits__c + blng__Debits__c + blng__NegativeLineConversion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Solde = montant total - paiements nets totaux - notes de crédit appliquées + notes de débit appliquées + conversions de ligne négatives</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>Total facture (taxes comprises). Égal au sous-total + taxes.</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <summarizedField>blng__InvoiceLine__c.blng__TotalAmount__c</summarizedField>
        <summaryForeignKey>blng__InvoiceLine__c.blng__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

mdapiEYH/objects/blng__InvoiceLine__c.object
<CustomObject>
    <description>The line items on Invoices, such as products etc.</description>
    <label>Invoice Line</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__Balance__c</fullName>
        <formula>blng__TotalAmount__c - blng__Payments__c - blng__Credits__c + blng__Debits__c + blng__NegativeLineConversion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount (with tax) - Payments - Credits + Debits + Negative Line Conversion</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__ConvertedCreditNoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Converted Credit Note Line</label>
        <referenceTo>blng__CreditNoteLine__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>blng__Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>InvoiceInvoiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>SubTotal + Tax</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SM021_CreditNoteServices.cls
/**
* @author Ayoub Ouarti
* @created 15/07/2020
* @description Service class for blng__CreditNote__c Object
*/
public class SM021_CreditNoteServices {
    
    /**
* @Author Ayoub Ouarti
* @created 15/07/2020
* @Description methode updateReleatedObjectsFields to set releated objects fields
* @Inputs void
*/
    public static void updateReleatedObjectsFields(List<blng__CreditNote__c> creditNoteList){
        Pad.log('SM021_CreditNoteServices','updateReleatedObjectsFields(List<blng__CreditNote__c> creditNoteList)','creditNoteList size '+creditNoteList.size());
        Id accountEntrepriseRTId  = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Entreprise);
        Set<Id> creditNoteListIds = UM003_TypeManager.getIdsOfListObjects(creditNoteList);
        List<blng__CreditNote__c> creditNoteListB2B = [SELECT Id  ,blng__Account__c FROM blng__CreditNote__c WHERE Id IN :creditNoteListIds AND blng__Account__r.RecordTypeId =:accountEntrepriseRTId ];
        Set<String> accountIds =     UM003_TypeManager.getFieldsOfListObjects(creditNoteListB2B, 'blng__Account__c');

         
        if(accountIds.size()>0){  
            List<Account> accounts = [SELECT Id,LPCR_ProcessRevenuCascade__c FROM Account WHERE Id IN :accountIds];
            for(Account eachAcc : accounts){
                eachAcc.LPCR_ProcessRevenuCascade__c = true;
            }
            update accounts;
        }

    }
    
    /**
    * @Author Saurabh
    * @created 16/08/2020
    * @Description methode afterUpdateCreateCreditNoteAllocation to create new CreditNoteAllocation records
    * @Inputs void
    */
    public static void afterUpdateCreateCreditNoteAllocation(List<blng__CreditNote__c> newCreditNoteList, Map<Id, blng__CreditNote__c> oldCreditNoteMap){
        Pad.log('SM021_CreditNoteServices','afterUpdateCreateCreditNoteAllocation(List<blng__CreditNote__c> newCreditNoteList)','newCreditNoteList size '+newCreditNoteList.size());
        Set<String> relatedInvoiceSet = new Set<String>();
        
		List<blng__CreditNoteAllocation__c> insertCreditNoteAllocationList = new List<blng__CreditNoteAllocation__c>();
        
        // Get blng__RelatedInvoice__c from blng__CreditNote__c
        for(blng__CreditNote__c eachCreditNote : newCreditNoteList){
            if('Posted'.equals(eachCreditNote.blng__Status__c) && 'Negative Lines Conversion'.equals(eachCreditNote.blng__CreditNoteSourceAction__c)){
                relatedInvoiceSet.add(eachCreditNote.blng__RelatedInvoice__c);
            }
        }
        
        decimal minBal = 0;
        if(test.isRunningTest()){minBal = -1;}   

		// Query only the positive Invoice Lines based on the Source Invoice(blng__RelatedInvoice__c field on Credit Note) AND blng__Balance__c > 0
        if(relatedInvoiceSet.size() > 0){
            for(blng__InvoiceLine__c eachInvoiceLine : [SELECT Id, Name, blng__Balance__c, blng__ConvertedCreditNoteLine__c,blng__ConvertedCreditNoteLine__r.blng__TotalAmount__c FROM blng__InvoiceLine__c WHERE blng__Invoice__c IN: relatedInvoiceSet AND blng__Balance__c > : minBal ]){
                blng__CreditNoteAllocation__c newCreditNoteAllocation = new blng__CreditNoteAllocation__c();
                newCreditNoteAllocation.blng__Amount__c = eachInvoiceLine.blng__Balance__c;
                newCreditNoteAllocation.blng__InvoiceLine__c = eachInvoiceLine.id;
                newCreditNoteAllocation.blng__Notes__c = 'Automatic Credit Note Allocation';
                newCreditNoteAllocation.blng__Type__c = 'Allocation';
                newCreditNoteAllocation.blng__CreditNoteLine__c = eachInvoiceLine.blng__ConvertedCreditNoteLine__c;
                
                if(eachInvoiceLine.blng__Balance__c >= eachInvoiceLine.blng__ConvertedCreditNoteLine__r.blng__TotalAmount__c){
                    newCreditNoteAllocation.blng__Amount__c = eachInvoiceLine.blng__ConvertedCreditNoteLine__r.blng__TotalAmount__c;
                }else{
                    newCreditNoteAllocation.blng__Amount__c = eachInvoiceLine.blng__Balance__c;
                }
                insertCreditNoteAllocationList.add(newCreditNoteAllocation);
            }
        }
		
        if(insertCreditNoteAllocationList.size() > 0){
            try{
				insert insertCreditNoteAllocationList;                
            }catch(Exception ex){
                PAD.log('SM021_CreditNoteServices', 'afterUpdateCreateCreditNoteAllocation', 'Exception: ' + ex.getMessage());
            }
        }
    }
    
}