mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_ResponsableADV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable ADV</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ResponsableServiceFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable Service Famille</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Debut</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_MethodeRenouvellement__c</fullName>
        <label>Méthode Renouvellement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tacite</fullName>
                </value>
                <value>
                    <fullName>Express</fullName>
                </value>
                <value>
                    <fullName>Sans renouvellement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>L&apos;opportunité à partir de laquelle ce contrat a été créé.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ResponsableADV__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ResponsableADV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable ADV</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_ResponsableServiceFamille__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ResponsableServiceFamille__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Service Famille</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_MethodeRenouvellement__c</fullName>
        <label>Méthode Renouvellement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tacite</fullName>
                </value>
                <value>
                    <fullName>Express</fullName>
                </value>
                <value>
                    <fullName>Sans renouvellement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_ResponsableADV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable ADV</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ResponsableServiceFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable Service Famille</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Devis</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/APC013_UpliftNow_TEST.cls
/**
 * @description       : 
 * @author            : Widaad Papauretty
 * @group             : 
 * @last modified on  : 10-15-2021
 * @last modified by  : Widaad Papauretty
**/
@isTest

public with sharing class APC013_UpliftNow_TEST {
    
    private static final Id CONTRACT_RESERVATRICE_RT_ID =   EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Contract, Label.LPCR_Reservataire);
    private static final Id B2C_RT_ID =                     EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Famille);

    @isTest
    public static void APC013_UpliftNow_TEST() {

  
        //create account
        Account acc = UM002_TestDataFactory.createAccounts(1, 'test').get(0);
        insert acc; 
        
        //create opportunity
        Opportunity opp = UM002_TestDataFactory.createOpportunities(10, 'testOpp', 'Client').get(0);
        insert opp;

        //create contract
        Contract con = new Contract (   AccountID               = acc.id,
                                        SBQQ__Opportunity__c    = opp.id,
                                        LPCR_Sales_Rep__c       = UserInfo.getUserId(),
                                        LPCR_ResponsableADV__c  = UserInfo.getUserId(),
                                        LPCR_ResponsableServiceFamille__c = UserInfo.getUserId(),
                                        StartDate               = System.today(),
                                        ContractTerm            = 12,
                                        LPCR_DateDebut__c       = Date.newInstance(2020,10, 01),
                                        LPCR_DateFin__c         = Date.newInstance(2020, 10, 30),
                                        LPCR_MethodeRenouvellement__c = 'Express',
                                        RecordTypeId = CONTRACT_RESERVATRICE_RT_ID
                                    );

        insert con;

        APC013_UpliftNow.doUplift(con.id);
        
        //create quote & quote lines
        // SBQQ__Quote__c quote =UM002_TestDataFactory.createQuotes(1, acc, opp);
        // insert quote;


    }
}