mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Ancien client</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
                <value>
                    <fullName>Ex-adhérent</fullName>
                </value>
                <value>
                    <fullName>Fournisseur</fullName>
                </value>
                <value>
                    <fullName>Rachat LPCR</fullName>
                </value>
                <value>
                    <fullName>Ne souhaite pas adhérer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Enfant</fullName>
        <active>true</active>
        <label>Enfant</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/LPCR_Preinscription__c.object
<CustomObject>
    <description>Objet servant à stocker les réponses aux formulaires de préinscription remplis par les familles par l&apos;intermédiare de FormAssembly</description>
    <label>Préinscription</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Numéro de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Préinscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nouveau</fullName>
                    <default>true</default>
                    <label>Nouveau</label>
                </value>
                <value>
                    <fullName>Liste d’attente</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Recommandation</fullName>
                </value>
                <value>
                    <fullName>Recommandation validée</fullName>
                </value>
                <value>
                    <fullName>Proposition</fullName>
                </value>
                <value>
                    <fullName>Confirmé</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapiEYH/classes/LWC003_UpdateStatusController_Test.cls
@isTest
public with sharing class LWC003_UpdateStatusController_Test {
    @testSetup
    public static void setup(){
        Id enfantContactRecordTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName('Contact', 'Enfant');
        Account acc = UM002_TestDataFactory.createAccount('test');
        insert acc;
        
        UM002_TestDataFactory.ContactTdf c = new UM002_TestDataFactory.ContactTdf();
        Contact contact= c.create('Test','Test', acc);
        contact.RecordTypeId = enfantContactRecordTypeId;
        insert contact;
        List<LPCR_Preinscription__c> lstPreinscrition = UM002_TestDataFactory.createPreinscription(200,'test1','test2','Recommandation validée',acc.Id,contact.Id);
        insert lstPreinscrition;
       
    }
    @isTest
    public static void  getPicklistvalues_Test() {
        System.runAs(UM002_TestDataFactory.createUser()){
            Test.startTest();
            LWC003_UpdateStatusController.getPicklistvalues();
            Test.stopTest();
        }
    }
    
    @isTest
    public static void updateLstPreinscription_Test() {
        System.runAs(UM002_TestDataFactory.createUser()){
            Map<Id, LPCR_Preinscription__c> preinscriptionIdsMap = new Map<Id, LPCR_Preinscription__c>([SELECT Id,LPCR_Statut__c FROM LPCR_Preinscription__c]);
            List<Id> preinscriptionIds = new List<Id>(preinscriptionIdsMap.keySet());
            Test.startTest();
            LWC003_UpdateStatusController.updateLstPreinscription('Option', preinscriptionIds);
            Test.stopTest();
        }
        
    }
}