mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_ResponsableADV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable ADV</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ResponsableServiceFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable Service Famille</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Debut</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_MethodeRenouvellement__c</fullName>
        <label>Méthode Renouvellement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tacite</fullName>
                </value>
                <value>
                    <fullName>Express</fullName>
                </value>
                <value>
                    <fullName>Sans renouvellement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__AmendmentStartDate__c</fullName>
        <description>Start Date of your Amendment. If blank, Amendment will start on today&apos;s date.</description>
        <inlineHelpText>Date de début de votre amendement. Si la date est vide, l&apos;amendement commence à la date du jour.</inlineHelpText>
        <label>Amendment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity from which this Contract was created.</description>
        <inlineHelpText>L&apos;opportunité à partir de laquelle ce contrat a été créé.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ResponsableADV__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ResponsableADV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable ADV</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_ResponsableServiceFamille__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ResponsableServiceFamille__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Service Famille</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/APC010_AmendLexContractController_Test.cls
@isTest
public with sharing class APC010_AmendLexContractController_Test {
    
    
    private static final Id CONTRACT_RESERVATRICE_RT_ID =   EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Contract, Label.LPCR_Reservataire);
    private static final Id B2C_RT_ID =                     EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Famille);

    @isTest
    private static void APC010_AmendLexContractController_Test() {


        Account acc = UM002_TestDataFactory.createAccounts(1, 'test').get(0);acc.RecordTypeId = B2C_RT_ID;
        insert acc;

        List<Opportunity> opps = UM002_TestDataFactory.createOpportunities(100, 'testOpp', 'Prospecting');
        Opportunity opp = opps.get(0);
        insert opp;

        Contract con = new Contract(    AccountID               = acc.id,
                                        SBQQ__Opportunity__c    = opp.id,
                                        LPCR_Sales_Rep__c       = UserInfo.getUserId(),
                                        LPCR_ResponsableADV__c  = UserInfo.getUserId(),
                                        LPCR_ResponsableServiceFamille__c = UserInfo.getUserId(),
                                        StartDate               = System.today(),
                                        ContractTerm            = 12,
                                        LPCR_DateDebut__c       = Date.newInstance(2020,05, 01),
                                        LPCR_DateFin__c         = Date.newInstance(2020, 05, 30),
                                        LPCR_MethodeRenouvellement__c = 'Express',
                                        RecordTypeId = CONTRACT_RESERVATRICE_RT_ID);
        insert con;
        String negativeResult = APC010_AmendLexContractController.getContractDetails(con.id);
        System.assertEquals(System.label.LPCR_AmendLexError,negativeResult);

        con.SBQQ__AmendmentStartDate__c = System.today();
        update con;

        String positiveResult = APC010_AmendLexContractController.getContractDetails(con.id);
        System.assertEquals(null,positiveResult);

    }
}