mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_IDSage__c</fullName>
        <label>ID Sage</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

mdapiEYH/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__Account__c</fullName>
        <inlineHelpText>Rechercher dans le compte la facturation de cette facture.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>AccountInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>OrderInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__Subtotal__c</fullName>
        <inlineHelpText>Total facture (hors taxes)</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>blng__InvoiceLine__c.blng__Subtotal__c</summarizedField>
        <summaryForeignKey>blng__InvoiceLine__c.blng__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>Total facture (taxes comprises). Égal au sous-total + taxes.</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <summarizedField>blng__InvoiceLine__c.blng__TotalAmount__c</summarizedField>
        <summaryForeignKey>blng__InvoiceLine__c.blng__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_MontantAvoirFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_MontantAvoirFacture__c</fullName>
    <defaultValue>-0.1</defaultValue>
    <label>Montant avoir</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_NatureAvoirFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_NatureAvoirFacture__c</fullName>
    <label>Nature de l’avoir</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A.CT - Contrat</fullName>
            </value>
            <value>
                <fullName>A.CT - Résil</fullName>
            </value>
            <value>
                <fullName>A.CT - Annulation</fullName>
            </value>
            <value>
                <fullName>A.COM - Litige comm</fullName>
            </value>
            <value>
                <fullName>A.COM - Formulation client</fullName>
            </value>
            <value>
                <fullName>A.COM - Covid</fullName>
            </value>
            <value>
                <fullName>A.ADV - Erreur saisie</fullName>
            </value>
            <value>
                <fullName>A.ADV - MIB</fullName>
            </value>
            <value>
                <fullName>A.ADV - Doublon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_SocieteFacturante__c.field-meta.xml
<CustomField>
    <fullName>LPCR_SocieteFacturante__c</fullName>
    <formula>blng__Order__r.SBQQ__Quote__r.LPCR_SocieteFacturante__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Société Facturante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_TypeAvoir__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeAvoir__c</fullName>
    <label>Type Avoir</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Total</fullName>
            </value>
            <value>
                <fullName>Partiel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapiEYH/objects/blng__InvoiceLine__c.object
<CustomObject>
    <description>The line items on Invoices, such as products etc.</description>
    <label>Invoice Line</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__EndDate__c</fullName>
        <description>The ending date for the period of calculation of this charge. Applicable only to Recurring Charges.</description>
        <inlineHelpText>The last day of the billing period.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>blng__Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>InvoiceInvoiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__StartDate__c</fullName>
        <description>The starting date for the period of calculation of this charge. Applicable only to Recurring Charges.</description>
        <inlineHelpText>The first day of the billing period.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__Subtotal__c</fullName>
        <inlineHelpText>Invoice Line total (before taxes).</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>SubTotal + Tax</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/objects/blng__InvoiceLine__c/fields/LPCR_DateFinAvoir__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateFinAvoir__c</fullName>
    <label>Date de fin de l&apos;avoir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/blng__InvoiceLine__c/fields/LPCR_MontantAvoirLigneFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_MontantAvoirLigneFacture__c</fullName>
    <defaultValue>-0.1</defaultValue>
    <label>Montant avoir</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LPCR_Avoir__c/LPCR_Avoir__c.object-meta.xml
<CustomObject>
    <label>Avoir</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Nom de Avoir</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avoirs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LPCR_Avoir__c/fields/LPCR_DateFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateFacture__c</fullName>
    <label>Date de début de l&apos;avoir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LPCR_Avoir__c/fields/LPCR_DateFinAvoir__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateFinAvoir__c</fullName>
    <label>Date de fin de l&apos;avoir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LPCR_Avoir__c/fields/LPCR_Description__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LPCR_Avoir__c/fields/LPCR_Facture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>Avoirs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_Avoir__c/fields/LPCR_LigneFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_LigneFacture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne de Facture</label>
    <referenceTo>blng__InvoiceLine__c</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>Avoirs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_Avoir__c/fields/LPCR_Montant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Montant__c</fullName>
    <defaultValue>-0.1</defaultValue>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LPCR_Avoir__c/fields/LPCR_NatureAvoirFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_NatureAvoirFacture__c</fullName>
    <label>Nature de l’avoir</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A.CT - Contrat</fullName>
            </value>
            <value>
                <fullName>A.CT - Résil</fullName>
            </value>
            <value>
                <fullName>A.CT - Annulation</fullName>
            </value>
            <value>
                <fullName>A.COM - Litige comm</fullName>
            </value>
            <value>
                <fullName>A.COM - Formulation client</fullName>
            </value>
            <value>
                <fullName>A.COM - Covid</fullName>
            </value>
            <value>
                <fullName>A.ADV - Erreur saisie</fullName>
            </value>
            <value>
                <fullName>A.ADV - MIB</fullName>
            </value>
            <value>
                <fullName>A.ADV - Doublon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LPCR_Avoir__c/fields/LPCR_TypeAvoir__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeAvoir__c</fullName>
    <label>Type d&apos;avoir</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avoir total</fullName>
            </value>
            <value>
                <fullName>Avoir partiel</fullName>
            </value>
            <value>
                <fullName>Avoir direct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapiEYH/objects/Order.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order/fields/LPCR_SocieteFacturante__c.field-meta.xml
<CustomField>
    <fullName>LPCR_SocieteFacturante__c</fullName>
    <formula>SBQQ__Quote__r.SBQQ__Account__r.LPCR_SocieteFacturanteCompte__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Société Facturante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APC012_CreateAvoir.cls
public with sharing class APC012_CreateAvoir {

    @AuraEnabled(Cacheable=true)
    public static List<String> getPicklistvalues(){
    
    List<String> lstPicklistValue = new List<String>();
    Schema.DescribeFieldResult describeFieldRslt = LPCR_Avoir__c.LPCR_NatureAvoirFacture__c.getDescribe();
    List<Schema.PicklistEntry> pickListEntries = describeFieldRslt.getPicklistValues();
    
    for(Schema.PicklistEntry eachEntry : pickListEntries ) {
        lstPicklistValue.add(eachEntry.getValue());
    }
   
    return lstPicklistValue;
    
    }

    @AuraEnabled(cacheable=true)
    public static String getLigneFacture(Id invId){
        List<LigneFactureWrapper> ligneFactureWrapperList = new List<LigneFactureWrapper>();
        for( blng__InvoiceLine__c ligneFacture :  [SELECT Id,Name, LPCR_MontantAvoirLigneFacture__c,blng__Invoice__r.LPCR_SocieteFacturante__c,blng__Invoice__r.blng__Account__r.LPCR_IDSage__c,blng__Invoice__r.blng__Order__r.SBQQ__Quote__r.LPCR_SocieteFacturante__r.Name, blng__EndDate__c, blng__StartDate__c  FROM blng__InvoiceLine__c where blng__Invoice__c  =:invId]){
                ligneFactureWrapperList.add(new LigneFactureWrapper(
                    ligneFacture.Id,
                    ligneFacture.Name,    
                    ligneFacture.LPCR_MontantAvoirLigneFacture__c ,ligneFacture.blng__Invoice__r.blng__Order__r.SBQQ__Quote__r.LPCR_SocieteFacturante__r.Name,ligneFacture.blng__Invoice__r.blng__Account__r.LPCR_IDSage__c));
        }
        return JSON.serialize(ligneFactureWrapperList);
    }
    public class LigneFactureWrapper{
        private String recId;
        private String name;
        private Decimal Montant;
        private String socfac;
        private String ctNum;

       
        LigneFactureWrapper(String recId,String name, Decimal Montant,String socfac,String ctNum){
          this.recId = recId;
          this.name = name;
          this.Montant = Montant;
          this.socfac=socfac;
          this.ctNum=ctNum;

        }
    }
    @AuraEnabled 
    public static Map<String,Object>  saveAvoir(String resp){
        String errorMsg='';
        Map<String,Object> mapReturn = new Map<String,Object>();
        List<LPCR_Avoir__c> lstavoirInsert=new List<LPCR_Avoir__c> ();
        List<LPCR_Avoir__c> lstavoirInsertTotal=new List<LPCR_Avoir__c> ();

        List<blng__Invoice__c> lstfacture=new List<blng__Invoice__c> ();

        Date datedebut;
        Date dateFin;
        Boolean applytoAllLines=false;
        Decimal sommePartiel=0;
        Boolean containsAvoirTotal=false;
        Boolean containsAvoirPartiel=false;
        Decimal montantFacture=0;
        Decimal sommePartielCustom=0;
        Map<String,Object> mapSrtr=(Map<String, Object>)JSON.deserializeUntyped(resp);
        applytoAllLines=mapSrtr.containsKey('checkboxApplyAll')?(Boolean)mapSrtr.get('checkboxApplyAll'):false;
        List<Object> lstObj=mapSrtr.containsKey('LineList')?(List<Object>)mapSrtr.get('LineList'):(List<Object>)new List<Object>();
        Id invID=mapSrtr.containsKey('invoiceID')? (ID)mapSrtr.get('invoiceID'):null;
        String typeAvoir=mapSrtr.containsKey('TypeAvoir')? (String)mapSrtr.get('TypeAvoir'):'';
        //get facture details

        for(blng__Invoice__c inv :[SELECT Id,blng__TotalAmount__c FROM blng__Invoice__c where id=:invID] ){
            montantFacture=inv.blng__TotalAmount__c;
        }
        for(LPCR_Avoir__c avoir :[SELECT Id, LPCR_TypeAvoir__c,LPCR_Facture__c,LPCR_Facture__r.blng__TotalAmount__c,LPCR_Montant__c FROM LPCR_Avoir__c where LPCR_Facture__c=:invID ] ){
            
            if(avoir.LPCR_TypeAvoir__c =='Avoir total'){
                containsAvoirTotal=true;
            }
            if(avoir.LPCR_TypeAvoir__c =='Avoir partiel' && avoir.LPCR_Montant__c != null ){
                containsAvoirPartiel=true;
                sommePartiel+=avoir.LPCR_Montant__c ;
            }
        }
        if(containsAvoirTotal && typeAvoir =='Avoir total' ){
            mapReturn.put('errorMessage','contient deja un avoir total');
            return mapReturn;
        }
        if(containsAvoirTotal && typeAvoir =='Avoir partiel' ){
            mapReturn.put('errorMessage','contient deja un avoir total');
            return mapReturn;
        }
        if(containsAvoirPartiel &&   typeAvoir =='Avoir total'){
            mapReturn.put('errorMessage','contient deja un avoir partiel');
            return mapReturn;
        }
        if(mapSrtr.containsKey('datedebut')){
            String dateDebutAvoir=mapSrtr.containsKey('datedebut')?(String)mapSrtr.get('datedebut'):'';
            if(!String.isBlank(dateDebutAvoir)){
                List<String> lstDebut=dateDebutAvoir.split('-');
                datedebut=Date.newInstance(Integer.valueOf(lstDebut[0]),Integer.valueOf(lstDebut[1]),Integer.valueOf(lstDebut[2]));
            }
            
        }
        if(mapSrtr.containsKey('datefin')){
            String dateDebutAvoir=mapSrtr.containsKey('datefin')?(String)mapSrtr.get('datefin'):'';
            if(!String.isBlank(dateDebutAvoir)){
                List<String> lstDebut=dateDebutAvoir.split('-');
                dateFin=Date.newInstance(Integer.valueOf(lstDebut[0]),Integer.valueOf(lstDebut[1]),Integer.valueOf(lstDebut[2]));
            }
        }
        //if not apply to all lines 
        
        if(!applytoAllLines && typeAvoir=='Avoir partiel'){
            for(Object obj : lstObj){
                Map<String,Object> mapObjet=(Map<String,Object>)obj;
                if(mapSrtr.containsKey('avoirmontant')){
                sommePartielCustom+=Decimal.valueof((string)mapSrtr.get('avoirmontant'));
                }

                LPCR_Avoir__c avoir=new LPCR_Avoir__c(LPCR_Facture__c=mapSrtr.containsKey('invoiceID')?(ID)mapSrtr.get('invoiceID'):null,LPCR_DateFacture__c=datedebut,LPCR_DateFinAvoir__c=dateFin,LPCR_Description__c=mapSrtr.containsKey('descavoir')?(String)mapSrtr.get('descavoir'):'',LPCR_Montant__c=mapSrtr.containsKey('avoirmontant')?Decimal.valueof((string)mapSrtr.get('avoirmontant')):0,LPCR_LigneFacture__c=(Id)mapObjet.get('recId'),LPCR_TypeAvoir__c =(String)mapSrtr.get('TypeAvoir'),LPCR_NatureAvoirFacture__c =mapSrtr.containsKey('NatureAvoir')?(String)mapSrtr.get('NatureAvoir'):null);

        
                if(typeAvoir=='Avoir partiel'){
                    lstavoirInsert.add(avoir);
                }
            }
        }
        if(applytoAllLines || typeAvoir=='Avoir total' ){
            //lop in all lignes factures 
            for(blng__InvoiceLine__c invLine :[SELECT Id, blng__Invoice__c,blng__EndDate__c, blng__StartDate__c,blng__Subtotal__c FROM blng__InvoiceLine__c where blng__Invoice__c=:invID]){
                if(mapSrtr.containsKey('avoirmontant')){
                    sommePartielCustom+=Decimal.valueof((string)mapSrtr.get('avoirmontant'));
                }
                

                LPCR_Avoir__c avoir=new LPCR_Avoir__c(LPCR_Facture__c=mapSrtr.containsKey('invoiceID')?(ID)mapSrtr.get('invoiceID'):null,LPCR_Description__c=mapSrtr.containsKey('descavoir')?(String)mapSrtr.get('descavoir'):'',LPCR_LigneFacture__c=invLine.Id,LPCR_TypeAvoir__c =(String)mapSrtr.get('TypeAvoir'),LPCR_NatureAvoirFacture__c =mapSrtr.containsKey('NatureAvoir')?(String)mapSrtr.get('NatureAvoir'):null);

                if(typeAvoir=='Avoir partiel'){
                    avoir.LPCR_DateFacture__c=datedebut;
                    avoir.LPCR_DateFinAvoir__c=dateFin;
                    avoir.LPCR_Montant__c=Decimal.valueof((string)mapSrtr.get('avoirmontant'));
                    lstavoirInsert.add(avoir);
                }
                if(typeAvoir=='Avoir total'){
                    avoir.LPCR_DateFacture__c=invLine.blng__StartDate__c;
                    avoir.LPCR_DateFinAvoir__c=invLine.blng__EndDate__c;
                    avoir.LPCR_Montant__c=invLine.blng__Subtotal__c > 0 ?invLine.blng__Subtotal__c*-1:invLine.blng__Subtotal__c;
                    lstavoirInsertTotal.add(avoir);
                }
                
            }
        }
        
        if(typeAvoir =='Avoir total'){
            LPCR_Avoir__c avoir=new LPCR_Avoir__c(LPCR_Facture__c=(ID)mapSrtr.get('invoiceID'),LPCR_DateFacture__c=datedebut,LPCR_DateFinAvoir__c=dateFin,LPCR_Description__c=(String)mapSrtr.get('descavoir'),LPCR_Montant__c=montantFacture,LPCR_TypeAvoir__c =(String)mapSrtr.get('TypeAvoir'));
           // lstavoirInsertTotal.add(avoir);
        }
        if((sommePartiel.abs()+sommePartielCustom.abs()) > montantFacture){
            errorMsg='Montant excedant le montant facture';
        }
        if(containsAvoirTotal && lstavoirInsert.size() > 0 ){
             errorMsg='Facture contient deja un avoir total';
        }
        if(containsAvoirPartiel && lstavoirInsertTotal.size() > 0 ){
            errorMsg='Facture contient deja un avoir partiel';
        }
        mapReturn.put('errorMessage',errorMsg);

        //update total field on invoice 
        if(String.isEmpty(errorMsg) && typeAvoir=='Avoir partiel'){
            Decimal totalPartiel=sommePartiel+sommePartielCustom;
            lstfacture.add(new blng__Invoice__c(Id=invID,LPCR_MontantAvoirFacture__c=totalPartiel));
        }
        try{
            if(lstfacture.size() >0 )update lstfacture;

            if(lstavoirInsert.size() > 0 && errorMsg==''  ) insert lstavoirInsert;
            if(lstavoirInsertTotal.size() > 0 && errorMsg==''  ) insert lstavoirInsertTotal;
        }catch(DmlException e) {
            mapReturn.put('errorMessage',e.getMessage());
            errorMsg=e.getMessage();
        }
        return mapReturn;
    }
   
    
    
}