mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_ResponsableADV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable ADV</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ResponsableServiceFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsable Service Famille</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Ancien client</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
                <value>
                    <fullName>Ex-adhérent</fullName>
                </value>
                <value>
                    <fullName>Fournisseur</fullName>
                </value>
                <value>
                    <fullName>Rachat LPCR</fullName>
                </value>
                <value>
                    <fullName>Ne souhaite pas adhérer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Account/fields/LPCR_ContactInscriptions__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactInscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Inscriptions</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comptes (Contact Inscriptions)</relationshipLabel>
    <relationshipName>Comptes1</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/Opportunity.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/LPCR_ContactInscriptions__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactInscriptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact du client pour les inscriptions. Utilisé comme champ de fusion dans les contrats</description>
    <label>Contact Inscriptions</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Inscription sur Opportunités</relationshipLabel>
    <relationshipName>Opportunites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LPCR_Ref_ContactFacturation__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Ref_ContactFacturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LPCR_Ref_ContactFacturation</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>OppCntFacturation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LPCR_Ref_ContactInscription__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Ref_ContactInscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LPCR_Ref_ContactInscription</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités (LPCR_Ref_ContactInscription)</relationshipLabel>
    <relationshipName>OppCntInscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LPCR_Ref_IdCompte__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Ref_IdCompte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LPCR_Ref_IdCompte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunit_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LPCR_Ref_RespADV__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Ref_RespADV__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LPCR_Ref_RespADV</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunit_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LPCR_Ref_RespServiceFam__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Ref_RespServiceFam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LPCR_Ref_RespServiceFam</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunit_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SM004_OpportunityServices.cls
/**
* @author Achraf ABOUL
* @created 20/02/2020
* @description Services class on Opportunity Object
*/
public class SM004_OpportunityServices {

    
    public static void setOpportunityFields(List<Opportunity> newOpportunitiesList) {

        for (Opportunity opp : newOpportunitiesList) {

            opp.LPCR_Ref_ContactFacturation__c = opp.Account.blng__BillToContact__c;
            opp.LPCR_Ref_ContactInscription__c = opp.Account.LPCR_ContactInscriptions__c;
            opp.LPCR_Ref_IdCompte__c = opp.Account.Id;
            opp.LPCR_Ref_RespADV__c = opp.Account.LPCR_ResponsableADV__c;
            opp.LPCR_Ref_RespServiceFam__c = opp.Account.LPCR_ResponsableServiceFamille__c;
        }
    }
    

    public static void setAccountStatus(Map<Id, Opportunity> newOpportunitiesMap, Map<Id, Opportunity> oldOpportunitiesMap ){
        List<Account> accountListNew = new List<Account>();
        
        Set<String> accountIds= UM003_TypeManager.getFieldsOfListObjects(newOpportunitiesMap.values(), 'AccountId');
        
        Map<String, String> accountStatutMap = new Map<String, String>(); 
        
        for(Opportunity opp : [SELECT AccountId, account.lpcr_statut__c
                               FROM Opportunity
                               WHERE AccountId IN: accountIds]){
                                   accountStatutMap.put(opp.AccountId, opp.Account.lpcr_statut__c);
                               }
        
        
        for(Opportunity opp: newOpportunitiesMap.values()){
            if(oldOpportunitiesMap.get(opp.Id).isWon != opp.isWon){
                if(opp.AccountId != null && accountStatutMap.containsKey(opp.AccountId) && accountStatutMap.get(opp.AccountId) != Label.LPCR_Client){
                    if(opp.isWon == true) accountListNew.add(new Account(id=opp.AccountId, lpcr_statut__c = Label.LPCR_Client));                         
                    else  accountListNew.add(new Account(id=opp.AccountId, lpcr_statut__c = Label.LPCR_Prospect));                    
                }}
        }
        EM004_OpportunityEntity cl = new EM004_OpportunityEntity();
        String methodName = 'setAccountStatus';
        cl.dmlExecuteRequest('update',  accountListNew, true, methodName, DM000_SObject.ProcessType.TRIGGER_SRC);
               
    }

    public static void setAccountStatus(Map<Id, Opportunity> newOpportunitiesMap)
    {
        List<Account> accountListNew = new List<Account>();
        
        Set<String> accountIds= UM003_TypeManager.getFieldsOfListObjects(newOpportunitiesMap.values(), 'AccountId');
        
        Map<String, String> accountStatutMap = new Map<String, String>(); 
        
        for(Opportunity opp : [SELECT AccountId, account.lpcr_statut__c
                               FROM Opportunity
                               WHERE AccountId IN: accountIds]){
                                   accountStatutMap.put(opp.AccountId, opp.Account.lpcr_statut__c);
                               }
        
        
        for(Opportunity opp: newOpportunitiesMap.values()){
            if(opp.AccountId != null && accountStatutMap.containsKey(opp.AccountId) && accountStatutMap.get(opp.AccountId) != Label.LPCR_Client){
                if(opp.isWon == true) accountListNew.add(new Account(id=opp.AccountId, lpcr_statut__c = Label.LPCR_Client));                         
                else  accountListNew.add(new Account(id=opp.AccountId, lpcr_statut__c = Label.LPCR_Prospect));                    
            }
        }
        EM004_OpportunityEntity cl = new EM004_OpportunityEntity();
        String methodName = 'setAccountStatus';
        cl.dmlExecuteRequest('update',  accountListNew, true, methodName, DM000_SObject.ProcessType.TRIGGER_SRC);
               
    }
}