mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_TauxEffort__c</fullName>
        <label>Taux d&apos;effort</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <label>Type de crèche</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ALSH</fullName>
                </value>
                <value>
                    <fullName>MAF</fullName>
                </value>
                <value>
                    <fullName>MICRO</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>Halte-Garderie</fullName>
                </value>
                <value>
                    <fullName>Jardin d’enfants</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeFacturation__c</fullName>
        <label>Type de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingType</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Enfant</fullName>
        <active>true</active>
        <label>Enfant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Famille</fullName>
        <active>true</active>
        <label>Famille</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Debut</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_RenouvellementAutomatique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renouvellement Automatique</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LPCR_TypeFacturation__c</fullName>
        <label>Type de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalQuoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this option to automatically generate a renewal quote on renewal opportunities.</description>
        <inlineHelpText>Sélectionnez cette option pour générer automatiquement un devis de renouvellement dans les opportunités de renouvellement.</inlineHelpText>
        <label>Renewal Quoted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ContactEnfant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactEnfant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Enfant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact Enfant)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_TypeCreche__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeCreche__c</fullName>
    <label>Type de crèche</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LPCR_TypeCreche</valueSetName>
    </valueSet>
</CustomField>

mdapiEYH/objects/LPCR_BaremeCAF__c.object
<CustomObject>
    <label>Barème CAF</label>
    <nameField>
        <displayFormat>BCAF-{00000}</displayFormat>
        <label>Barème CAF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Barèmes CAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
</CustomObject>

mdapiEYH/objects/LPCR_RessourceFamille__c.object
<CustomObject>
    <label>Ressource Famille</label>
    <nameField>
        <label>Ressource Famille Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ressources Familles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_BaremeCaf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barème CAF</label>
        <referenceTo>LPCR_BaremeCAF__c</referenceTo>
        <relationshipLabel>Ressources Familles</relationshipLabel>
        <relationshipName>Ressources_Familles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_CompteFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte Famille</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ressources Familles</relationshipLabel>
        <relationshipName>Ressources_Familles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Enfant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ressources Familles</relationshipLabel>
        <relationshipName>Ressources_Familles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_TauxEffort__c</fullName>
        <label>Taux d&apos;effort</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <formula>Text ( LPCR_creche__r.LPCR_TypeCreche__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type Crèche</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Mac</fullName>
        <active>true</active>
        <label>Mac</label>
    </recordTypes>
</CustomObject>

force-app/main/default/globalValueSets/LPCR_TypeCreche.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALSH</fullName>
    </customValue>
    <customValue>
        <fullName>MAF</fullName>
    </customValue>
    <customValue>
        <fullName>MAC</fullName>
    </customValue>
    <customValue>
        <fullName>MICRO</fullName>
    </customValue>
    <customValue>
        <fullName>Halte-Garderie</fullName>
    </customValue>
    <customValue>
        <fullName>Jardin d’enfants</fullName>
    </customValue>
    <customValue>
        <fullName>RAM</fullName>
    </customValue>
    <customValue>
        <fullName>Partenaire</fullName>
    </customValue>
    <customValue>
        <fullName>PAJE</fullName>
    </customValue>
    <masterLabel>Type de crèche</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SBQQ__BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arrieree</fullName>
        <label>Arriérée</label>
    </customValue>
    <customValue>
        <fullName>Anticipee</fullName>
        <label>Anticipée</label>
    </customValue>
    <description>Billing type</description>
    <masterLabel>Billing Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/APB018_AutomateRessourceFamille_Test.cls
/**
* @author Hanae Makboub
* @date 04/10/2020
* @Description test class: Batch for Automation of "ressource famille" before B2C MAC renewals
*/

@isTest
public class APB018_AutomateRessourceFamille_Test {
	
    private static final Id ACC_B2C_RT_ID = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Famille);
    private static final Id CONTACT_ENFANT_RT_ID = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Contact, Label.LPCR_Enfant);
    private static final Id CONTRACT_ACCUEIL_RT_ID = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Contract, Label.LPCR_ContratA);
    
    private static final Date todayDate = Date.toDay();
    
    @testsetup
    static void setup() {
        
        Map<String, Object> defaultVal = new Map<String, Object> {
            'RecordTypeId' => ACC_B2C_RT_ID,
                'Name' => 'FAMILLE'
                };
                    Account account =(Account) UM002_TestDataFactory.createSObject('Account', defaultVal);
        insert account;
        
        defaultVal = new Map<String, Object> {
            'RecordTypeId' => CONTACT_ENFANT_RT_ID,
                'Name' => 'ENFANT'
                };
                    Contact contact =(Contact) UM002_TestDataFactory.createSObject('Contact', defaultVal);
        insert contact;
        
        defaultVal = new Map<String, Object> {
            'RecordTypeId' => CONTRACT_ACCUEIL_RT_ID,
                'AccountId' => account.id,
                'LPCR_ContactEnfant__c' => contact.id,
                'LPCR_TypeCreche__c' => 'MAC',
                'Status' => 'Draft',
                'LPCR_RenouvellementAutomatique__c' => true,
                'SBQQ__RenewalQuoted__c' => false,
                'LPCR_TypeFacturation__c' => 'Advance',
                'EndDate' => System.today().addDays(-1)
                };
                    Contract contract =(Contract) UM002_TestDataFactory.createSObject('Contract', defaultVal);
        insert contract;
        
        defaultVal = new Map<String, Object> {
            'LPCR_CompteFamille__c' => account.id,
                'LPCR_ContactEnfant__c' => contact.id,
                'LPCR_DateDebut__c' => System.today()
                };
                    LPCR_RessourceFamille__c ressourceFamille1 =(LPCR_RessourceFamille__c) UM002_TestDataFactory.createSObject('LPCR_RessourceFamille__c', defaultVal);
        
        			LPCR_RessourceFamille__c ressourceFamille2 =(LPCR_RessourceFamille__c) UM002_TestDataFactory.createSObject('LPCR_RessourceFamille__c', defaultVal);
        
        			LPCR_RessourceFamille__c ressourceFamille3 =(LPCR_RessourceFamille__c) UM002_TestDataFactory.createSObject('LPCR_RessourceFamille__c', defaultVal);
        
        insert new List<LPCR_RessourceFamille__c>{ressourceFamille1,ressourceFamille2,ressourceFamille3};
        
        
    }
    
    
    @isTest
    private static void testAPB018_AutomateRessourceFamille(){
        
        System.runAs(UM002_TestDataFactory.createUser()){
            
            Date endYear = Date.newInstance(System.today().Year(), 12, 31);
            
            Account acountFamille = [SELECT Id, Name  FROM Account WHERE Name = 'FAMILLE'];
            
            Contact contactEnfant = [SELECT Id, Name  FROM Contact];
            
            Contract contractAcc = [SELECT Id,Status FROM Contract WHERE AccountId =: acountFamille.Id AND LPCR_ContactEnfant__c=: contactEnfant.Id ];
            
            contractAcc.Status = 'Activated';
        	update contractAcc ;
            
            List<LPCR_RessourceFamille__c> ressourceFamilleList = [SELECT Id, LPCR_CompteFamille__c, LPCR_ContactEnfant__c, LPCR_DateFin__c, LPCR_DateDebut__c,LPCR_BaremeCaf__c , LPCR_TauxEffort__c 
                                                                   FROM LPCR_RessourceFamille__c
                                                                   WHERE LPCR_CompteFamille__c =: acountFamille.Id 
                                                                   AND LPCR_ContactEnfant__c =: contactEnfant.Id];
            
            Test.startTest();
            
            APB018_AutomateRessourceFamille resFammileAutomationBatch = new APB018_AutomateRessourceFamille();
            resFammileAutomationBatch.execute(null);
            
            Test.stopTest();
            
            List<LPCR_RessourceFamille__c> listRessourceInactive = [SELECT Id, LPCR_CompteFamille__c, LPCR_ContactEnfant__c, LPCR_DateFin__c, LPCR_DateDebut__c,LPCR_BaremeCaf__c , LPCR_TauxEffort__c 
                                               						FROM LPCR_RessourceFamille__c WHERE LPCR_DateFin__c =: endYear];
            
            List<LPCR_RessourceFamille__c> listRessourceactive = [SELECT Id, LPCR_CompteFamille__c, LPCR_ContactEnfant__c, LPCR_DateFin__c, LPCR_DateDebut__c,LPCR_BaremeCaf__c , LPCR_TauxEffort__c 
                                               					  FROM LPCR_RessourceFamille__c
                                               				      WHERE LPCR_DateFin__c = null];
            
            System.assertEquals(3, listRessourceInactive.size(), 'Error in setting ressource Famille to inactive ');
            System.assertEquals(3, listRessourceactive.size(), ' Error in clonning active ressource famille');
            
        }
           
    }
}