mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_IDSage__c</fullName>
        <label>ID Sage</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_PasDeSIRET__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pas de numéro de SIRET</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SM029_AccountService_Test.cls
@isTest
public  class SM029_AccountService_Test {
    public static Id entrepriseRecTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account,Label.LPCR_Entreprise);
    public static List<Account> lstAccount=new List<Account>();
    @testSetup 
    static void testSetup(){
        
        Account acc= new Account(Name='test',RecordTypeId=entrepriseRecTypeId,LPCR_IDSage__c ='4110000001',LPCR_PasDeSIRET__c=true);
        lstAccount.add(acc);
        insert lstAccount;
    }
    @isTest
    public static void insertAccounts_Test(){
        Account acc= new Account(Name='test1',RecordTypeId=entrepriseRecTypeId,LPCR_PasDeSIRET__c=true);
        lstAccount.add(acc);

        insert lstAccount;
        Test.startTest();
        Test.stopTest();
        List<Account> lstAccountUp=[Select id,LPCR_IDSage__c  from Account where id=:lstAccount[0].id];
        System.assertNotEquals(null, lstAccountUp[0].LPCR_IDSage__c , 'Error in Ctnum');
    }
    
}