mdapiEYH/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <label>Type de crèche</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ALSH</fullName>
                </value>
                <value>
                    <fullName>MAF</fullName>
                </value>
                <value>
                    <fullName>MICRO</fullName>
                </value>
                <value>
                    <fullName>MAC</fullName>
                </value>
                <value>
                    <fullName>Halte-Garderie</fullName>
                </value>
                <value>
                    <fullName>Jardin d’enfants</fullName>
                </value>
                <value>
                    <fullName>RAM</fullName>
                </value>
                <value>
                    <fullName>Partenaire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapiEYH/objects/blng__Usage__c.object
<CustomObject>
    <label>Usage</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Usage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_TypeEvenement__c</fullName>
        <label>LPCR Type Evenement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gestes commerciaux</fullName>
                </value>
                <value>
                    <fullName>Journées occasionnelles (Micro)</fullName>
                </value>
                <value>
                    <fullName>Heures occasionnelles (Mac)</fullName>
                </value>
                <value>
                    <fullName>Grèves</fullName>
                </value>
                <value>
                    <fullName>Hospitalisation</fullName>
                </value>
                <value>
                    <fullName>Fermeture crèches</fullName>
                </value>
                <value>
                    <fullName>Arrivée retardée de l’enfant</fullName>
                </value>
                <value>
                    <fullName>Éviction pour maladie</fullName>
                </value>
                <value>
                    <fullName>Maladie justifiée</fullName>
                </value>
                <value>
                    <fullName>Mise à pied</fullName>
                </value>
                <value>
                    <fullName>Congés non pris</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>AccountUsages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__MatchingId__c</fullName>
        <externalId>true</externalId>
        <label>Matching ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/blng__Usage__c/fields/LPCR_ContactEnfant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactEnfant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact enfant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.blng__Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Enfant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Usages</relationshipLabel>
    <relationshipName>Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/blng__Usage__c/fields/LPCR_Product__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>B2B</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Usages</relationshipLabel>
    <relationshipName>Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/Product2.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Product2/fields/LPCR_TypeEvenement__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeEvenement__c</fullName>
    <label>Type d&apos;événement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LPCR_TypeEvenement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LPCR_TypeEvenement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Modification Absence</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Heure Supplémentaire MAC</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Heure Occasionnel MAC</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Heure Déduite MAC</fullName>
    </customValue>
    <customValue>
        <fullName>Nombre de repas</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Période d&apos;Adaptation</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Accueil Jour Supplémentaire Micro</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Accueil Occasionnel Micro</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Heures Déduites Micro</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Accueil d&apos;Urgence</fullName>
    </customValue>
    <customValue>
        <fullName>Modification Congés non pris MAC</fullName>
    </customValue>
    <customValue>
        <fullName>Mouvement Interne de Berceau</fullName>
    </customValue>
    <customValue>
        <fullName>ALSH</fullName>
    </customValue>
    <masterLabel>Type d&apos;événement</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SM014_UsageServices.cls
/**
* @author Ayoub Ouarti
* @date 19/05/2020
* @description Service class for blng__Usage__c
*/
public with sharing class SM014_UsageServices {
    
    /*
*	@description : this method Update the Matching ID field on Usage object for B2B and Micro	
*	@param List<blng__Usage__c> usageList to process
*	@returns void
*/
    
    public static void setUsageFields(List<blng__Usage__c> usageList){
        
        Pad.log('SM014_UsageServices', 'setUsageFields(List<blng__Usage__c> usageList)', 'usageList.size '+usageList.size());
        
        Id accountEntrepriseRTId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Entreprise);
        Id accountCrecheTId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Creche);
        Set<String> accountIds = UM003_TypeManager.getFieldsOfListObjects(usageList,'blng__Account__c');
        Map<Id,Account> mapAccounts = new Map<Id,Account>([SELECT Id,Name,LPCR_TypeCreche__c, RecordTypeId FROM Account WHERE ID in :accountIds]);
        
        Set<String> productIds = UM003_TypeManager.getFieldsOfListObjects(usageList,'LPCR_Product__c');
        Map<Id,Product2> mapProducts = new Map<Id,Product2>([SELECT Id,Name FROM Product2 WHERE ID in :productIds]);

        Set<String> contactsIds = UM003_TypeManager.getFieldsOfListObjects(usageList,'LPCR_ContactEnfant__c'); 
        Map<Id,Contact> mapContacts= new Map<Id,Contact>([SELECT Id,Name FROM Contact WHERE ID in :contactsIds]);

        
        for(blng__Usage__c eachUsage : usageList){
            //B2B case
            if(mapAccounts.get(eachUsage.blng__Account__c).RecordTypeId ==accountEntrepriseRTId ){
                eachUsage.blng__MatchingId__c = mapProducts.get(eachUsage.LPCR_Product__c).Name + mapAccounts.get(eachUsage.blng__Account__c).Name;
            }
            //B2C & MIRCO case
            else if(mapAccounts.get(eachUsage.blng__Account__c).RecordTypeId ==accountCrecheTId && 'MICRO'.equals(mapAccounts.get(eachUsage.blng__Account__c).LPCR_TypeCreche__c)){
               eachUsage.blng__MatchingId__c =  mapContacts.get(eachUsage.LPCR_ContactEnfant__c).Name + eachUsage.LPCR_TypeEvenement__c + mapAccounts.get(eachUsage.blng__Account__c).Name;
            }
            
            
        }
        
    }
}