mdapiEYH/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_StatutFacture__c</fullName>
        <label>Statut De La Facture</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Brouillon</fullName>
                </value>
                <value>
                    <fullName>A Envoyer</fullName>
                </value>
                <value>
                    <fullName>Envoyée</fullName>
                </value>
                <value>
                    <fullName>Signée</fullName>
                </value>
                <value>
                    <fullName>Annulée</fullName>
                </value>
                <value>
                    <fullName>Terminée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__InvoiceRunCreatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up relationship to the Invoice Run.Invoice is child of  Invoice Run.
This field tells from which Invoice Run the Invoice is generated.</description>
        <label>Invoice Run (Created By)</label>
        <referenceTo>blng__InvoiceRun__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>InvoiceRunInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__InvoiceStatus__c</fullName>
        <description>Warning: Invoice Status is an internal field. Changing it could cause basic functionality to fail or become unstable.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__InvoiceStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_Commentaire__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Commentaire__c</fullName>
    <label>Commentaire</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EM017_FactureEntity.cls
/**
* @author Hanae Makboub
* @date 29/06/2020
* @SOQL Queries about Invoice
*/
public with sharing class EM017_FactureEntity extends EM001_AbstractObjectEntity {
	public EM017_FactureEntity(){
        super('blng__Invoice__c');
    }
    
    public static List<blng__Invoice__c> lstPostedInvoices(Set<Id> invoiceRunIds){
        return [select Id, blng__InvoiceStatus__c,LPCR_Commentaire__c ,blng__InvoiceRunCreatedBy__c , Name , LPCR_StatutFacture__c from blng__Invoice__c 
               	Where blng__InvoiceStatus__c = 'Posted' AND blng__InvoiceRunCreatedBy__c In: invoiceRunIds ];
         
    }
}