mdapiEYH/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_NombreJoursUtilisation__c.field-meta.xml
<CustomField>
    <fullName>LPCR_NombreJoursUtilisation__c</fullName>
    <label>Nombre de jours utilisation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

mdapiEYH/objects/blng__InvoiceLine__c.object
<CustomObject>
    <description>The line items on Invoices, such as products etc.</description>
    <label>Invoice Line</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>blng__Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>InvoiceInvoiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__UsageSummary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usage Summary</label>
        <referenceTo>blng__UsageSummary__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>UsageSummaryInvoiceLines</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/blng__Usage__c.object
<CustomObject>
    <label>Usage</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Usage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>blng__EndDateTime__c</fullName>
        <label>End DateTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>blng__StartDateTime__c</fullName>
        <label>Start DateTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>blng__UsageSummary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usage Summary</label>
        <referenceTo>blng__UsageSummary__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SM028_InvoiceLineService.cls
/**
* @author  PDO
* @created 09/04/2021
* @description Trigger on Invoice Line Object
*/
public class SM028_InvoiceLineService {
    public static void populateNumberDaysBillingUsage(Map<Id, blng__InvoiceLine__c> newInvoiceLineMap,Map<Id, blng__InvoiceLine__c> oldInvoiceLineMap){
        Map<Id,Id>mapInvoiceIdBillingSummary = new Map<Id,Id>();
        Map <Id,String> mapInvoiceDates =new  Map <Id,String>();
        List<blng__Invoice__c> invoiceToUpdateList=new List<blng__Invoice__c>();
        List<Id> billingUsageSummaryList = new List<Id>();
        for(Id key : newInvoiceLineMap.keySet()){
            if(newInvoiceLineMap.get(key).blng__UsageSummary__c!= null){
                billingUsageSummaryList.add(newInvoiceLineMap.get(key).blng__UsageSummary__c );
                mapInvoiceIdBillingSummary.put(newInvoiceLineMap.get(key).blng__UsageSummary__c,newInvoiceLineMap.get(key).blng__Invoice__c);
            }
        }
        for(blng__Usage__c eachBillingUsage : [SELECT  blng__UsageSummary__r.blng__Invoice__c ,blng__StartDateTime__c,blng__EndDateTime__c FROM blng__Usage__c where 	blng__UsageSummary__c IN:billingUsageSummaryList]){
            if(!mapInvoiceDates.containsKey(mapInvoiceIdBillingSummary.get(eachBillingUsage.blng__UsageSummary__c))){
                
                mapInvoiceDates.put(mapInvoiceIdBillingSummary.get(eachBillingUsage.blng__UsageSummary__c),getDaysBetweenDates(eachBillingUsage.blng__StartDateTime__c,eachBillingUsage.blng__EndDateTime__c));
            }else{
                mapInvoiceDates.put(mapInvoiceIdBillingSummary.get(eachBillingUsage.blng__UsageSummary__c),mapInvoiceDates.get(mapInvoiceIdBillingSummary.get(eachBillingUsage.blng__UsageSummary__c))+'\n'+getDaysBetweenDates(eachBillingUsage.blng__StartDateTime__c,eachBillingUsage.blng__EndDateTime__c));
            }
            
        }
        //loop in map and update new field on facture 
        for(Id key :mapInvoiceDates.keySet() ){
            invoiceToUpdateList.add(new blng__Invoice__c(id=key,LPCR_NombreJoursUtilisation__c=mapInvoiceDates.get(key)));
        }
        if(invoiceToUpdateList.size()>0){
            update invoiceToUpdateList;
        }
        
    }
    public static String getDaysBetweenDates(Datetime dateStart,Datetime dateEnd){
        Integer daysBetween=dateStart.date().daysBetween(dateEnd.date());
        String str='';
        For(Integer i=0;i<=daysBetween;i++){
            str=String.isBlank(str)?dateStart.addDays(i).format('dd/MM/yyyy'):str+'\n'+dateStart.addDays(i).format('dd/MM/yyyy');
            
        }
       return str;
    }
    
}