mdapiEYH/objects/blng__LegalEntity__c.object
<CustomObject>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
        <inlineHelpText>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionPricing__c</fullName>
        <description>Determines how the subscription on this line item is priced. Blank value means this line contains product that&apos;s not a subscription.</description>
        <inlineHelpText>Indicates how the subscription price is calculated. If this is blank, the line items is not a subscription product.</inlineHelpText>
        <label>Subscription Pricing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>Percent Of Total</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term for the subscription product in this line. If the product is not a subscription this value has no effect.</description>
        <inlineHelpText>Term for this subscription. If this product is not a subscription this value has no effect.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/LPCR_Quote_Recalculated__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Quote_Recalculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Recalculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/APB016_QuoteReCalculateProcess_Test.cls
@isTest
public with sharing class APB016_QuoteReCalculateProcess_Test {
    
    
    @isTest
    static void testAPB016_QuoteReCalculateProcess_Test() {

        //ACC OPP QUOTE
        List<Account> accs = UM002_TestDataFactory.createAccounts(1,'testAccount');
        insert accs;
        List<Opportunity> oppties = UM002_TestDataFactory.createOpportunities(1, 'testOpp', 'Prospecting');
        insert oppties;
        SBQQ__Quote__c quote =UM002_TestDataFactory.createQuotes(1, accs, oppties).get(0);
        insert quote;


        UM002_TestDataFactory.insertBillingCustomSettings();
        //Not Used
        blng__LegalEntity__c billingLegalEntity = UM002_TestDataFactory.setupLegalEntity();
        //Used
        blng__RevenueRecognitionRule__c revRecRule = UM002_TestDataFactory.setupRevRec(billingLegalEntity.Id);
        blng__BillingRule__c billingRule = UM002_TestDataFactory.setupBillingRule(billingLegalEntity.Id);
        blng__TaxRule__c taxRule = UM002_TestDataFactory.setupTaxRule(billingLegalEntity.Id);
        Id standardPricebookId = Test.getStandardPricebookId();

        Map<String, Object> defaultVal; 

        //Produit
        defaultVal = new Map<String, Object> {
            'Name' => 'prod-test',
            'isActive' => true,
            'blng__BillingRule__c' => billingRule.Id,
            'blng__RevenueRecognitionRule__c' => revRecRule.Id,
            'blng__TaxRule__c' => taxRule.Id,
            'SBQQ__SubscriptionPricing__c' => 'Fixed Price',
            'SBQQ__SubscriptionTerm__c' => 12,
            'ProductCode' => Label.LPCR_RegistrationFeeMac
        };
        Product2 prod = (Product2) UM002_TestDataFactory.createSObject('Product2', defaultVal);
        insert prod;

        //PriceBook
        defaultVal = new Map<String, Object> {
            'isActive' => true,
            'UnitPrice' => 100,
            'Product2Id' => prod.Id,
            'Pricebook2Id' => standardPricebookId
        };
        PricebookEntry priceBookEntry = (PricebookEntry) UM002_TestDataFactory.createSObject('PricebookEntry', defaultVal);
        insert priceBookEntry;

        // QUOTE LINE
        Integer price = 200;
        SBQQ__QuoteLine__c quoteLine = UM002_TestDataFactory.createQuoteLine((string)prod.Id, (string)quote.Id, (string)priceBookEntry.Id, (decimal)price, 1);
        quoteLine.LPCR_Quote_Recalculated__c = false;
        insert quoteLine;

        test.startTest();

        APB016_QuoteReCalculateProcess sc1 = new APB016_QuoteReCalculateProcess();
        sc1.quoteIds.add(quote.Id);
        sc1.execute(null);

        test.stopTest();

        SBQQ__QuoteLine__c quoteAfter = [SELECT LPCR_Quote_Recalculated__c FROM SBQQ__QuoteLine__c WHERE id=:quoteLine.id];
        System.Assert(quoteAfter.LPCR_Quote_Recalculated__c);
    }
}