mdapiEYH/objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>blng__Account__c</fullName>
        <inlineHelpText>Rechercher dans le compte la facturation de cette facture.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>AccountInvoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_Creche__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Creche__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crèche</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creche</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factures (Crèche)</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/blng__Invoice__c/fields/LPCR_LiaisonFamilleFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_LiaisonFamilleFacture__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Liaison famille facture</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/blng__InvoiceLine__c.object
<CustomObject>
    <description>The line items on Invoices, such as products etc.</description>
    <label>Invoice Line</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__EndDate__c</fullName>
        <description>The ending date for the period of calculation of this charge. Applicable only to Recurring Charges.</description>
        <inlineHelpText>The last day of the billing period.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>blng__Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>InvoiceInvoiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__OrderProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>OrderProductInvoiceLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__StartDate__c</fullName>
        <description>The starting date for the period of calculation of this charge. Applicable only to Recurring Charges.</description>
        <inlineHelpText>The first day of the billing period.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_ContratEntreprise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LPCR_ContratEntreprise</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contrats (LPCR_ContratEntreprise)</relationshipLabel>
        <relationshipName>Contrats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lien vers la crèche porteuse du contrat</description>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Le compte n&apos; a pas un type d&apos;enregistrement = Crèche</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Crèche</value>
            </filterItems>
            <infoMessage>type d&apos;enregistrement = Crèche</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contrats de la crèche</relationshipLabel>
        <relationshipName>Contrats</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ContractEntreprise__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContractEntreprise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat Entreprise</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contrats Familles</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/LPCR_LienFamilleFacture__c.object
<CustomObject>
    <label>Lien Famille et Facture</label>
    <nameField>
        <displayFormat>LFF-{0000}</displayFormat>
        <label>Lien Famille et Facture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Liens Familles et Factures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LPCR_LienFamilleFacture__c/fields/LPCR_ContratEntreprise__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContratEntreprise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat Entreprise</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Liens Familles et Factures (Contrat Entreprise)</relationshipLabel>
    <relationshipName>Liens_Familles_et_Factures_B2B</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_LienFamilleFacture__c/fields/LPCR_ContratFamille__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContratFamille__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat Famille</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Liens Familles et Factures</relationshipLabel>
    <relationshipName>Liens_Familles_et_Factures_B2C</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_LienFamilleFacture__c/fields/LPCR_Facture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Liens Familles et Factures</relationshipLabel>
    <relationshipName>Liens_Familles_et_Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_LienFamilleFacture__c/fields/LPCR_LigneFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_LigneFacture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne de Facture</label>
    <referenceTo>blng__InvoiceLine__c</referenceTo>
    <relationshipLabel>Liens Familles et Factures</relationshipLabel>
    <relationshipName>Liens_Familles_et_Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/OrderItem.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/LPCR_Creche__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Creche__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crèche</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products (Crèche)</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contract of the subscription that is created from this order product.</description>
    <inlineHelpText>Le contrat d&apos;abonnement créé à partir de ce produit commandé.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/APB009_GenerateLienFamilleFacture.cls
/**
* @author Ayoub Ouarti
* @date 22/06/2020
* @Description identify the invoices associated with an active B2B contract. 
*/
global class APB009_GenerateLienFamilleFacture implements Database.Batchable<sObject>,Schedulable {
    
    global APB009_GenerateLienFamilleFacture() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //Id accountEntrepriseRTId  = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Entreprise);

        String query = 'SELECT Id, blng__Account__c ,LPCR_LiaisonFamilleFacture__c FROM blng__Invoice__c WHERE LPCR_LiaisonFamilleFacture__c=false ';//AND blng__Acoount__r.RecordTypeeId = :accountEntrepriseRTId';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<blng__Invoice__c> scope) {
        PAD.log('APB009_GenerateLienFamilleFacture','execute','scope to execute : '+scope);
        Id contratB2CRTId  = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Contract, Label.LPCR_Contrat_B2B);

        Set<Id> invoiceIds = UM003_TypeManager.getIdsOfListObjects(scope);
        Map<Id,blng__Invoice__c> mapOfInvoice = new Map<Id,blng__Invoice__c>([SELECT Id, blng__Account__c ,LPCR_LiaisonFamilleFacture__c
                                                         FROM blng__Invoice__c
                                                         WHERE Id IN :invoiceIds ]);   
        
        Set<String> invoiceAccountIds = UM003_TypeManager.getFieldsOfListObjects(mapOfInvoice.values(),'blng__Account__c');

        List<blng__InvoiceLine__c> listOfInvoiceLine = [SELECT Id,LPCR_Creche__c,blng__StartDate__c,blng__EndDate__c ,blng__Invoice__c,blng__Invoice__r.blng__Account__c,blng__OrderProduct__r.SBQQ__Contract__c
                                                        FROM blng__InvoiceLine__c
                                                        WHERE blng__Invoice__c IN :invoiceIds];

        //Date minStartDates = UM003_TypeManager.getMinMaxOfListObjectsDate(listOfInvoiceLine,'startDate')[0];
        //Date maxEndDates = UM003_TypeManager.getMinMaxOfListObjectsDate(listOfInvoiceLine,'endDate')[1];

        List<Contract> listOfContractB2C = [SELECT Id,endDate,startDate,AccountId,LPCR_ContractEntreprise__c,LPCR_ContractEntreprise__r.AccountId
                                            FROM Contract 
                                            WHERE AccountId IN :invoiceAccountIds 
                                            //AND endDate >= :minStartDates
                                            //AND startDate <= :maxEndDates
                                            AND RecordTypeId = :contratB2CRTId];


        List<LPCR_LienFamilleFacture__c> listOfLienFamilleFacture = new List<LPCR_LienFamilleFacture__c>();
        List<blng__Invoice__c> listOfInvocieToUpdate = new List<blng__Invoice__c>();
        blng__Invoice__c invoiceTemp = new blng__Invoice__c();
        for(Contract eachContract : listOfContractB2C){
            for(blng__InvoiceLine__c eachInvoiceLine : listOfInvoiceLine){
                    if( eachInvoiceLine.blng__Invoice__r.blng__Account__c== eachContract.LPCR_ContractEntreprise__r.AccountId &&  eachContract.LPCR_ContractEntreprise__r.AccountId != null
                    && eachInvoiceLine.LPCR_Creche__c == eachContract.LPCR_Creche__c && eachContract.LPCR_Creche__c!=null){

                    if(eachContract.endDate >= eachInvoiceLine.blng__StartDate__c && eachContract.startDate <= eachInvoiceLine.blng__EndDate__c  ){
                        invoiceTemp = new blng__Invoice__c(Id=mapOfInvoice.get(eachInvoiceLine.blng__Invoice__c).Id,LPCR_LiaisonFamilleFacture__c=true);
                        if(!UM003_TypeManager.listContainsValue(listOfInvocieToUpdate,invoiceTemp,'Id')){
                            listOfInvocieToUpdate.add(invoiceTemp);
                        }

                        listOfLienFamilleFacture.add(new LPCR_LienFamilleFacture__c(LPCR_Facture__c=eachInvoiceLine.blng__Invoice__c,
                                                                                    LPCR_LigneFacture__c=eachInvoiceLine.Id,
                                                                                    LPCR_ContratFamille__c =eachContract.Id,
                                                                                    LPCR_ContratEntreprise__c	= eachInvoiceLine.blng__OrderProduct__r.SBQQ__Contract__c
                                                                                    ));
                        }   
                    }
                }
        }
    insert listOfLienFamilleFacture;
    update listOfInvocieToUpdate;

    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
    global void execute(SchedulableContext sc) {
        PAD.log('APB009_GenerateLienFamilleFacture','execute','sc');
        APB009_GenerateLienFamilleFacture sc1 = new APB009_GenerateLienFamilleFacture();
        
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB009_GenerateLienFamilleFacture');
        
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB009_GenerateLienFamilleFacture();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 30 mins
                sc1 = new APB009_GenerateLienFamilleFacture();
                Datetime dt = Datetime.now().addMinutes(30);  // i.e. 30 mins
                String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
                Id schedId = System.Schedule('APB009_GenerateLienFamilleFacture'+timeForScheduler,timeForScheduler,sc1);
            }
        }  
        
    } 
}