mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lien vers la crèche porteuse du contrat</description>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Le compte n&apos; a pas un type d&apos;enregistrement = Crèche</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Crèche</value>
            </filterItems>
            <infoMessage>type d&apos;enregistrement = Crèche</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contrats de la crèche</relationshipLabel>
        <relationshipName>Contrats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateRenouvellement__c</fullName>
        <formula>EndDate +  LPCR_JoursAvance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date de Renouvellement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_JoursAvance__c</fullName>
        <label>Jours à l&apos;avance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LPCR_RenouvellementAutomatique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renouvellement Automatique</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalForecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</description>
        <inlineHelpText>Sélectionnez cette case pour déclencher la génération d&apos;une opportunité de renouvellement à des fins de prévision. Ne génère pas automatiquement un devis de renouvellement.</inlineHelpText>
        <label>Renewal Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalQuoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this option to automatically generate a renewal quote on renewal opportunities.</description>
        <inlineHelpText>Sélectionnez cette option pour générer automatiquement un devis de renouvellement dans les opportunités de renouvellement.</inlineHelpText>
        <label>Renewal Quoted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TECH_AjoutFraisGestion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Champ technique utilise pour processer correctement le contract de 
renouvellement a travers les batchs APB006_PrepaRenewalContract / APB002_RenewalContract</description>
        <label>TECH_Ajout Frais Gestion</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Order.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order/fields/LPCR_Creche__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Creche__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crèche</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creche</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Crèche)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/APB006_PrepaRenewalContract.cls
/**
* @author Dario Correnti
* @date 05/05/2020
* @Description Batch to bulk process Order and prepare them for execution of APB002_RenewalContract.
*/
global class APB006_PrepaRenewalContract implements Database.Batchable<sObject>, Database.Stateful, Schedulable {
    public static final String CONTRACT_TO_RENEW_BASE_QUERY = 'SELECT Id, AccountId, Account.RecordTypeId, LPCR_Creche__c, Name, ' + 
        ' EndDate, LPCR_RenouvellementAutomatique__c, SBQQ__RenewalQuoted__c, LPCR_JoursAvance__c ' +
        ' FROM Contract WHERE Status =\'Activated\' AND LPCR_RenouvellementAutomatique__c = true AND ' + 
        ' LPCR_DateRenouvellement__c <= :today AND (SBQQ__RenewalQuoted__c = false OR SBQQ__RenewalForecast__c = false)';
    
    Set<String> setContractKeyAccountAndNursery;

    global APB006_PrepaRenewalContract () {
        setContractKeyAccountAndNursery = new Set<String> ();
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        PAD.log('APB006_PrepaRenewalContract', 'start', 'START');
        Date today = date.today();

        String query = CONTRACT_TO_RENEW_BASE_QUERY + ' AND AccountId != null AND LPCR_Creche__c != null';
        PAD.log('APB006_PrepaRenewalContract', 'start', 'running query ' + query);

        return Database.getQueryLocator(query);
    }
    
    /*
	*	@description : this execute method simply flg contract (TECH_AjoutFraisGestion__c) to add the registration fee just to one contract in case of several contracts are renewd in parallell for the same customer / nurserey (for instance in case of renewal 2 children).
	*	@param List<Contract> scope to process
    *	@returns void
    */
    global void execute (Database.BatchableContext BC, List<Contract> scope) {
        PAD.log('APB006_PrepaRenewalContract', 'execute', 'scope size: ' + scope.size());
        PAD.log('APB006_PrepaRenewalContract', 'execute', 'setContractKeyAccountAndNursery size: ' + setContractKeyAccountAndNursery.size());

        Id accountEntrepriseRTId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Entreprise);
        Id accountFamilleRTId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Account, Label.LPCR_Famille);
        List<Contract> listContractToUpdate = new List<Contract>();

        for (Contract item : scope) {
            if (item.Account.RecordTypeId == accountEntrepriseRTId || item.Account.RecordTypeId == accountFamilleRTId) {
                String tmpContractKey = item.AccountId + '-' + item.LPCR_Creche__c;    
                if (!setContractKeyAccountAndNursery.contains(tmpContractKey)) {
                    setContractKeyAccountAndNursery.add(tmpContractKey);
                    listContractToUpdate.add(new Contract(Id = item.Id, TECH_AjoutFraisGestion__c = true));
                }
            }
        }
        PAD.log('APB006_PrepaRenewalContract', 'execute', 'updating listContractToUpdate recods: ' + listContractToUpdate.size());
        
        update listContractToUpdate;        
    }
    
    global void finish (Database.BatchableContext BC) {
        PAD.log('APB006_PrepaRenewalContract', 'finish', 'Start finish method');
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB002_RenewalContract');
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        if(!isBatchJobRunning && !isJobQueueFull && !Test.isRunningTest()) {
            PAD.log('APB006_PrepaRenewalContract', 'finish', 'launching APB002_RenewalContract');
            Database.executeBatch(new APB002_RenewalContract(), 1);
        }
    }
    
    global void execute(SchedulableContext sc) {
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB006_PrepaRenewalContract');
        APB006_PrepaRenewalContract sc1 = new APB006_PrepaRenewalContract();
        Datetime dt = Datetime.now().addMinutes(30);  // i.e. 30 mins
        String formatString = 's m H d M \'?\' yyyy';
        String timeForScheduler = dt.format(formatString);
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(!isBatchJobRunning) {
            if (!isJobQueueFull) {Database.executeBatch(sc1, 2000);}
            else { Id schedId = System.Schedule('APB006_PrepaRenewalContract' + timeForScheduler, timeForScheduler, sc1);PAD.log('APB006_PrepaRenewalContract', 'execute', 'scheduling in 30minutes : ' + timeForScheduler);}
        }  
    }
} 