mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lien vers la crèche porteuse du contrat</description>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Le compte n&apos; a pas un type d&apos;enregistrement = Crèche</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Crèche</value>
            </filterItems>
            <infoMessage>type d&apos;enregistrement = Crèche</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contrats de la crèche</relationshipLabel>
        <relationshipName>Contrats</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ContactEnfant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactEnfant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Enfant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact Enfant)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/LPCR_BonAchatPartenaire__c.object
<CustomObject>
    <description>Stockage des bons d&apos;achat partenaire</description>
    <label>Bon d&apos;achat partenaire</label>
    <nameField>
        <label>Numéro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bons d&apos;achat partenaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Enfant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bons d&apos;achat partenaires</relationshipLabel>
        <relationshipName>BonsAchatPartenaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Creche</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bons d&apos;achat (Crèche)</relationshipLabel>
        <relationshipName>BonsAchatCreche</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__Subscription__c/fields/LPCR_BonDachatPartenaire__c.field-meta.xml
<CustomField>
    <fullName>LPCR_BonDachatPartenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>stores detail of bda on contract</description>
    <label>Numéro bon d&apos;achat partenaire</label>
    <referenceTo>LPCR_BonAchatPartenaire__c</referenceTo>
    <relationshipLabel>Abonnements</relationshipLabel>
    <relationshipName>Abonnements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/LPCR_ContactEnfant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactEnfant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Enfant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Abonnements</relationshipLabel>
    <relationshipName>Abonnements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/LPCR_Creche__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Creche__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crèche</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions (Crèche)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SM030_BonAchatPartenaireService.cls
public with sharing class SM030_BonAchatPartenaireService {
    public static Id entrepriseRecTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Contract,Label.LPCR_Referencement);
    public static void populateBonAchatContrat(Map<Id, LPCR_BonAchatPartenaire__c> newBonAchatPartenaireMap){
        
    
        Map<String,ID> mapCrecheIDEnfantBonDachat=new Map<String,ID>();
        Map<String,ID> mapCrecheIDEnfantSubscription=new Map<String,ID>();
        Set<Id> setCreche =new Set<Id>();
        Set<Id> setContrat =new Set<Id>();
        Set<Id> setContactEnfant =new Set<Id>();
        List<SBQQ__Subscription__c> lstSubscriptionUpdate=new List<SBQQ__Subscription__c>();
        for (Id key : newBonAchatPartenaireMap.keySet()){
            if(newBonAchatPartenaireMap.get(key).LPCR_Creche__c != null && newBonAchatPartenaireMap.get(key).LPCR_ContactEnfant__c  != null ){
                if(!mapCrecheIDEnfantBonDachat.containsKey(newBonAchatPartenaireMap.get(key).LPCR_Creche__c+'-'+newBonAchatPartenaireMap.get(key).LPCR_ContactEnfant__c)){
                    mapCrecheIDEnfantBonDachat.put(newBonAchatPartenaireMap.get(key).LPCR_Creche__c+'-'+newBonAchatPartenaireMap.get(key).LPCR_ContactEnfant__c,key);
                    
                    setCreche.add(newBonAchatPartenaireMap.get(key).LPCR_Creche__c);
                    setContactEnfant.add(newBonAchatPartenaireMap.get(key).LPCR_ContactEnfant__c);
                }
                
            }
        }
        //get contrat where bon d'achat is null 
        for(SBQQ__Subscription__c  subs :[SELECT Id, LPCR_Creche__c, LPCR_ContactEnfant__c, LPCR_BonDachatPartenaire__c FROM SBQQ__Subscription__c  where LPCR_BonDachatPartenaire__c =null and LPCR_Creche__c IN:setCreche  and LPCR_ContactEnfant__c IN:setContactEnfant and SBQQ__Contract__r.RecordTypeId=:entrepriseRecTypeId ]){
            if(!mapCrecheIDEnfantSubscription.containsKey(subs.LPCR_Creche__c+'-'+subs.LPCR_ContactEnfant__c)){
                mapCrecheIDEnfantSubscription.put(subs.LPCR_Creche__c+'-'+subs.LPCR_ContactEnfant__c,subs.Id);
            }
        }
        //loop in all newly created subscription 
        for(String key : mapCrecheIDEnfantSubscription.keyset()){
            if(!mapCrecheIDEnfantBonDachat.isEmpty() && mapCrecheIDEnfantBonDachat.containsKey(key) ){
                lstSubscriptionUpdate.add(new SBQQ__Subscription__c(Id=mapCrecheIDEnfantSubscription.get(key),LPCR_BonDachatPartenaire__c=mapCrecheIDEnfantBonDachat.get(key)));
            }
            
        }
        if(lstSubscriptionUpdate.size() > 0 ){
            update lstSubscriptionUpdate;
        }
        
    }
}