mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_FrequenceFacturation__c</fullName>
        <label>Fréquence de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingFrequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to designate this contract as the master contract for this account. Upon renewal, all contracts will be rolled into this one.</description>
        <inlineHelpText>Sélectionnez cette case pour désigner ce contrat en tant que contrat principal de ce compte. Lors du renouvellement, tous les contrats sont cumulés dans celui-ci.</inlineHelpText>
        <label>Master Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_BatchCommande__c.field-meta.xml
<CustomField>
    <fullName>LPCR_BatchCommande__c</fullName>
    <label>LPCR_BatchCommande</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAC</fullName>
            </value>
            <value>
                <fullName>MICRO</fullName>
            </value>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>En Attente</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Batch 1</fullName>
            </value>
            <value>
                <fullName>Batch 2</fullName>
            </value>
            <value>
                <fullName>Batch 3</fullName>
            </value>
            <value>
                <fullName>Batch 4</fullName>
            </value>
            <value>
                <fullName>Batch 5</fullName>
            </value>
            <value>
                <fullName>Batch 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_CompteFacturation__c.field-meta.xml
<CustomField>
    <fullName>LPCR_CompteFacturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte de facturation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats (Compte de facturation)</relationshipLabel>
    <relationshipName>Contrats2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_InitAutoAvecDateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_InitAutoAvecDateDebut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Init auto avec date debu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_TypeEnregistrement__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeEnregistrement__c</fullName>
    <label>Type Enregistrement</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

mdapiEYH/objects/Order.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order/fields/blng__BillingDayOfMonth__c.field-meta.xml
<CustomField>
    <fullName>blng__BillingDayOfMonth__c</fullName>
    <label>Billing Day Of Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/LPCR_FrequenceFacturation__c.field-meta.xml
<CustomField>
    <fullName>LPCR_FrequenceFacturation__c</fullName>
    <label>Fréquence de facturation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/LPCR_InitAutoAvecDateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_InitAutoAvecDateDebut__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field used to know if the billing day of the month has to be setted with Order Start Date</inlineHelpText>
    <label>Facturation spécifique</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/LPCR_TypeEnregistrement__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeEnregistrement__c</fullName>
    <label>Type Enregistrement</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Contracted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contracted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the order is contracted.</description>
    <inlineHelpText>Indique si la commande est contractée.</inlineHelpText>
    <label>Contracted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Defines the billing frequency.</description>
        <inlineHelpText>Defines the billing frequency.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingFrequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master contract with which subscription products in this quote are to be co-terminated.</description>
        <inlineHelpText>Master contract with which subscription products in this quote are to be co-terminated.</inlineHelpText>
        <label>Master Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.SBQQ__Evergreen__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Co-Terminated Quotes</relationshipLabel>
        <relationshipName>CoTerminatedQuotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_BatchCommande__c.field-meta.xml
<CustomField>
    <fullName>LPCR_BatchCommande__c</fullName>
    <label>Lot de facture</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MAC</fullName>
            </value>
            <value>
                <fullName>MICRO</fullName>
            </value>
            <value>
                <fullName>B2B</fullName>
            </value>
            <value>
                <fullName>En Attente</fullName>
            </value>
            <value>
                <fullName>Ad-hoc</fullName>
            </value>
            <value>
                <fullName>Batch 1</fullName>
            </value>
            <value>
                <fullName>Batch 2</fullName>
            </value>
            <value>
                <fullName>Batch 3</fullName>
            </value>
            <value>
                <fullName>Batch 4</fullName>
            </value>
            <value>
                <fullName>Batch 5</fullName>
            </value>
            <value>
                <fullName>Batch 6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_CompteFacturation__c.field-meta.xml
<CustomField>
    <fullName>LPCR_CompteFacturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte de facturation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Compte de facturation)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_FrequenceFacturation__c.field-meta.xml
<CustomField>
    <fullName>LPCR_FrequenceFacturation__c</fullName>
    <label>LPCR_FrequenceFacturation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mensuelle</fullName>
            </value>
            <value>
                <fullName>Trimestrielle</fullName>
            </value>
            <value>
                <fullName>Semestrielle</fullName>
            </value>
            <value>
                <fullName>Annuelle</fullName>
            </value>
            <value>
                <fullName>Plan de facturation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_InitAutoAvecDateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_InitAutoAvecDateDebut__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field used to know if the billing day of the month has to be setted with Order Start Date</inlineHelpText>
    <label>Facturation spécifique</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_TypeEnregistrement__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeEnregistrement__c</fullName>
    <label>Type Enregistrement</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM014_OrderServices.cls
/**
* @author Fowdar Akshaye
* @date 02/06/2020
* @description Service class for Order
*/
public with sharing class SM014_OrderServices {
    
    /*
*	@description : this method is use to update LPCR_BatchCommande from the Quote
*	@param List<Order> order to process
*	@returns void
*/
    public static void setOrderFields (List<order> orderList, Map<Id, Order> oldOrdersMap) {
        Map<String,Schema.RecordTypeInfo> mapOrderRT = Schema.getGlobalDescribe().get('Order').getDescribe().getRecordTypeInfosByDeveloperName();
        Set<String> quoteIds = UM003_TypeManager.getFieldsOfListObjects(orderList,'SBQQ__Quote__c');
        
        Map<Id,SBQQ__Quote__c> quoteMap = new  Map<Id,SBQQ__Quote__c>([SELECT Id,LPCR_TypeEnregistrement__c,RecordType.DeveloperName,LPCR_CompteFacturation__c,SBQQ__BillingFrequency__c  ,LPCR_BatchCommande__c, SBQQ__MasterContract__r.LPCR_BatchCommande__c from SBQQ__Quote__c WHERE Id in :quoteIds]);
  
        for (Order eachOrder : orderList){
           eachOrder.blng__BillingDayOfMonth__c  =  eachOrder.LPCR_InitAutoAvecDateDebut__c ?  eachOrder.EffectiveDate.day()+'' : eachOrder.blng__BillingDayOfMonth__c;
            
           if(
               Trigger.isUpdate  
                && Label.LPCR_Amendment.equals(eachOrder.Type)  
                && eachOrder.SBQQ__Contracted__c == true 
                && oldOrdersMap.get(eachOrder.Id).SBQQ__Contracted__c == false
                ){
                eachOrder.blng__InvoiceBatch__c = quoteMap.get(eachOrder.SBQQ__Quote__c).SBQQ__MasterContract__r.LPCR_BatchCommande__c;
            }
            if(Trigger.isInsert && quoteMap.containsKey(eachOrder.SBQQ__Quote__c)){
                eachOrder.blng__InvoiceBatch__c = quoteMap.get(eachOrder.SBQQ__Quote__c).LPCR_BatchCommande__c;
                eachOrder.LPCR_FrequenceFacturation__c  = quoteMap.get(eachOrder.SBQQ__Quote__c).SBQQ__BillingFrequency__c;
                eachOrder.blng__BillingAccount__c = quoteMap.get(eachOrder.SBQQ__Quote__c).LPCR_CompteFacturation__c;
               
             /*eachOrder.RecordTypeId = mapOrderRT.containsKey(quoteMap.get(eachOrder.SBQQ__Quote__c).RecordType.DeveloperName)? 
                    mapOrderRT.get(quoteMap.get(eachOrder.SBQQ__Quote__c).RecordType.DeveloperName).getRecordTypeId():  eachOrder.RecordTypeId;*/
            if(quoteMap.get(eachOrder.SBQQ__Quote__c).RecordType.DeveloperName != null){
                if( mapOrderRT.containsKey(quoteMap.get(eachOrder.SBQQ__Quote__c).RecordType.DeveloperName)){
                    eachOrder.RecordTypeId = mapOrderRT.get(quoteMap.get(eachOrder.SBQQ__Quote__c).RecordType.DeveloperName).getRecordTypeId();
                }else if(mapOrderRT.containsKey(quoteMap.get(eachOrder.SBQQ__Quote__c).RecordType.DeveloperName.split('_')[0])){
                    eachOrder.RecordTypeId = mapOrderRT.get(quoteMap.get(eachOrder.SBQQ__Quote__c).RecordType.DeveloperName.split('_')[0]).getRecordTypeId();
                }
            }
               
            }
          
        }
    }
}