mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to designate this contract as the master contract for this account. Upon renewal, all contracts will be rolled into this one.</description>
        <inlineHelpText>Sélectionnez cette case pour désigner ce contrat en tant que contrat principal de ce compte. Lors du renouvellement, tous les contrats sont cumulés dans celui-ci.</inlineHelpText>
        <label>Master Contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/LPCR_Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Nom de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_TypeAvenant__c</fullName>
        <label>Type d&apos;avenant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Changement de Prix</fullName>
                </value>
                <value>
                    <fullName>Résiliation</fullName>
                </value>
                <value>
                    <fullName>Ajout/Suppression Berceau</fullName>
                </value>
                <value>
                    <fullName>Modification des termes du contrat</fullName>
                </value>
                <value>
                    <fullName>Modification du type/fréquence de facturation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__MasterContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master contract with which subscription products in this quote are to be co-terminated.</description>
        <inlineHelpText>Master contract with which subscription products in this quote are to be co-terminated.</inlineHelpText>
        <label>Master Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.SBQQ__Evergreen__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Co-Terminated Quotes</relationshipLabel>
        <relationshipName>CoTerminatedQuotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag to drive automatic order creation.</description>
        <inlineHelpText>Select this checkbox to automatically create an order from this quote, if it is a primary quote.</inlineHelpText>
        <label>Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Envoi directrice</fullName>
                </value>
                <value>
                    <fullName>Validé directrice</fullName>
                </value>
                <value>
                    <fullName>Prêt à envoyer</fullName>
                </value>
                <value>
                    <fullName>Envoyé pour signature</fullName>
                </value>
                <value>
                    <fullName>Signé</fullName>
                </value>
                <value>
                    <fullName>Actif</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/APB018_ProcessRenewalContract.cls
/**
* @author Saurabh Singh
* @date 04/11/2020
* @Description Batch for process renewel contract
*/
global class APB018_ProcessRenewalContract implements Database.Batchable<sObject>,Schedulable {
    String query;
    
    global APB018_ProcessRenewalContract() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date today = date.today();
        
        query = 'SELECT Id,SBQQ__MasterContract__c  FROM SBQQ__Quote__c WHERE SBQQ__Type__c =\'Amendment\' AND LPCR_TypeAvenant__c = \'Résiliation\'  AND SBQQ__Ordered__c = True AND SBQQ__Status__c != \'Terminé\' AND SBQQ__StartDate__c <= :today ';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<SBQQ__Quote__c> scope) {
        PAD.log('APB018_ProcessRenewalContract', 'execute', 'scope to execute : '+scope);
		
        Set<Id> quoteIds = UM003_TypeManager.getIdsOfListObjects(scope);
        Set<String> masterContractIds = UM003_TypeManager.getFieldsOfListObjects(scope, 'SBQQ__MasterContract__c');
        Set<String> masterContractQuoteIds = new Set<String>();        
        Set<String> masterQuoteContractIds = new Set<String>();
        String errorMsg = '';
        
        List<LPCR_Log__c> listOfLog = new List<LPCR_Log__c>();
        List<SBQQ__Quote__c> updateQuoteList = new List<SBQQ__Quote__c>();
        
        List<Contract> listOfMasterContract = [SELECT Id,Status,SBQQ__Quote__c,SBQQ__Quote__r.SBQQ__MasterContract__c FROM Contract 
                                         WHERE Id in :masterContractIds ]; 
        
        System.debug('>> APB018_ProcessRenewalContract , execute : listOfMasterContract = '+ listOfMasterContract);
		
        for(Contract eachContract : listOfMasterContract) {
            if(eachContract.SBQQ__Quote__c != null){
                masterContractQuoteIds.add(eachContract.SBQQ__Quote__c);
                if(eachContract.SBQQ__Quote__r.SBQQ__MasterContract__c != null){
                    masterQuoteContractIds.add(eachContract.SBQQ__Quote__r.SBQQ__MasterContract__c);
                }
            } 
            eachContract.Status = 'Terminé';
            listOfLog.add(UM001_LogManager.getWriteLogActivityForBulkInsert('', 'APB018_ProcessRenewalContract', 'Batch', String.valueOf(eachContract.Id), '', 'SUCCESS'));             
        }
		
        if(masterQuoteContractIds.size() > 0){
            for(Contract eachContract : [SELECT Id,Status,SBQQ__Quote__c FROM Contract WHERE Id in :masterQuoteContractIds ]){
                if(eachContract.SBQQ__Quote__c != null){
                    masterContractQuoteIds.add(eachContract.SBQQ__Quote__c);
                }
            }  
        }   
        
        for(SBQQ__Quote__c eachQuote : [SELECT Id,SBQQ__Status__c FROM SBQQ__Quote__c WHERE Id IN: masterContractQuoteIds OR Id IN: quoteIds]){
            eachQuote.SBQQ__Status__c = 'Terminé';
            updateQuoteList.add(eachQuote);
        }
		
        if(updateQuoteList.size() > 0){
            try{
                update updateQuoteList;
                update listOfMasterContract;
            }catch(Exception ex){
                PAD.log('APB018_ProcessRenewalContract','execute','Exception : '+ex.getMessage());
                errorMsg = String.valueOf(ex.getMessage());
            }
            finally {
                if (String.isNotBlank(errorMsg)) {
                    UM001_LogManager.writeLogActivityWithoutFuture('Update Contract Status','APB018_ProcessRenewalContract', 'Batch', '',  'Error:' + errorMsg, UM010_Constant.ERROR);  
                } else {
                    insert listOfLog;
                }               
            }
        }

    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
    global void execute(SchedulableContext sc) {
        
        APB018_ProcessRenewalContract sc1 = new APB018_ProcessRenewalContract();

        Datetime dt = Datetime.now().addMinutes(30);
        String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB018_ProcessRenewalContract');
        
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB018_ProcessRenewalContract();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 30 mins

                Id schedId = System.Schedule('APB018_ProcessRenewalContract'+timeForScheduler,timeForScheduler,new APB018_ProcessRenewalContract());
            }
        }  
        
    } 
}