mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_DateRevisionPrix__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateRevisionPrix__c</fullName>
    <inlineHelpText>Si Révision de prix (%) non renseigné, la facturation de la commande sera suspendue à cette date.</inlineHelpText>
    <label>Date de révision de prix</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_InitAutoAvecDateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_InitAutoAvecDateDebut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Init auto avec date debu</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/Order.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order/fields/LPCR_InitAutoAvecDateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_InitAutoAvecDateDebut__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field used to know if the billing day of the month has to be setted with Order Start Date</inlineHelpText>
    <label>Facturation spécifique</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__RenewalUpliftRate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalUpliftRate__c</fullName>
    <description>Rate of renewal price increases.</description>
    <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
    <label>Renewal Uplift (%)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/APB024_HoldBilling.cls
global with sharing class APB024_HoldBilling implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable{
    String query;
    final String ClassName = APB023_CreateIndexationAmendment.class.getName();
    global APB024_HoldBilling() {
        
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {

        UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'start', 'Batch' , null, 'Starting Batch', UM010_Constant.SUCCESS);
        //select Contract for which amendement indexation needs to be created
        return Database.getQueryLocator([Select id ,LPCR_IndexationConvenue__c,LPCR_DateRevisionPrix__c,LPCR_InitAutoAvecDateDebut__c,SBQQ__RenewalUpliftRate__c,SBQQ__Order__c From Contract where  LPCR_DateRevisionPrix__c=TODAY and LPCR_IndexationConvenue__c='Non' and SBQQ__RenewalUpliftRate__c=null] );
                                        
    }
    public void execute(Database.BatchableContext BC, list<Contract> scope){
        List<Id> lstOrderId=new List<Id>();
        List<OrderItem> lstOrderItemUpdt=new List<OrderItem>();
        for(Contract con : scope){ 
            lstOrderId.add(con.SBQQ__Order__c);
            
        }
        for(OrderItem orderitem : [SELECT Id ,OrderId FROM OrderItem where OrderId IN:lstOrderId]){
            orderitem.blng__HoldBilling__c ='Yes';
            lstOrderItemUpdt.add(orderitem );
        }
          
        if(lstOrderItemUpdt.size() > 0){
            update lstOrderItemUpdt;
        }
        //indexation pas convenue , order item ( hold billing blng__HoldBilling__c on OrderItem):another batch 
        
        
        
    }
    public void finish(Database.BatchableContext BC){
        
    }
    global void execute(SchedulableContext sc) {
    }
}