mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_BillingFrequency__c</fullName>
        <label>Fréquence de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingFrequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_RenouvellementPlanFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_RenouvellementPlanFacture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Facture (Renouvellement)</label>
    <referenceTo>blng__InvoicePlan__c</referenceTo>
    <relationshipLabel>Contracts (Plan de Facture (Renouvellement))</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_LignePlanFacturation__c/LPCR_LignePlanFacturation__c.object-meta.xml
<CustomObject>
    <label>Billing Plan Line</label>
    <nameField>
        <displayFormat>BPL-{0000}</displayFormat>
        <label>Billing Plan Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Plan Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LPCR_LignePlanFacturation__c/fields/LPCR_Amount__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LPCR_LignePlanFacturation__c/fields/LPCR_EndDate__c.field-meta.xml
<CustomField>
    <fullName>LPCR_EndDate__c</fullName>
    <label>Invoice Line End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LPCR_LignePlanFacturation__c/fields/LPCR_OrderItem__c.field-meta.xml
<CustomField>
    <fullName>LPCR_OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Billing Plan Lines</relationshipLabel>
    <relationshipName>Billing_Plan_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_LignePlanFacturation__c/fields/LPCR_PlanFacturation__c.field-meta.xml
<CustomField>
    <fullName>LPCR_PlanFacturation__c</fullName>
    <label>Billing Plan</label>
    <referenceTo>LPCR_PlanFacturation__c</referenceTo>
    <relationshipLabel>Billing Plan Lines</relationshipLabel>
    <relationshipName>Billing_Plan_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LPCR_LignePlanFacturation__c/fields/LPCR_Quantity__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LPCR_LignePlanFacturation__c/fields/LPCR_StartDate__c.field-meta.xml
<CustomField>
    <fullName>LPCR_StartDate__c</fullName>
    <label>Invoice Line Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LPCR_PlanFacturation__c/LPCR_PlanFacturation__c.object-meta.xml
<CustomObject>
    <label>Billing Plan</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Billing Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LPCR_PlanFacturation__c/fields/LPCR_BillingFrequency__c.field-meta.xml
<CustomField>
    <fullName>LPCR_BillingFrequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LPCR_PlanFacturation__c/fields/LPCR_EndDate__c.field-meta.xml
<CustomField>
    <fullName>LPCR_EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LPCR_PlanFacturation__c/fields/LPCR_OrderItem__c.field-meta.xml
<CustomField>
    <fullName>LPCR_OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Billing Plans</relationshipLabel>
    <relationshipName>Billing_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_PlanFacturation__c/fields/LPCR_StartDate__c.field-meta.xml
<CustomField>
    <fullName>LPCR_StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LPCR_PlanFacturation__c/fields/LPCR_TotalContractValue__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TotalContractValue__c</fullName>
    <label>Total Contract Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

mdapiEYH/objects/Order.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order/fields/blng__PendingBillings__c.field-meta.xml
<CustomField>
    <fullName>blng__PendingBillings__c</fullName>
    <inlineHelpText>Total en attente pour tous les produits de commande</inlineHelpText>
    <label>Pending Billing Amount (without tax)</label>
    <summarizedField>OrderItem.blng__PendingBillings__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/LPCR_DateFin__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateFin__c</fullName>
    <label>Date de fin contractuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/LPCR_RenouvellementPlanFacture__c.field-meta.xml
<CustomField>
    <fullName>LPCR_RenouvellementPlanFacture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Facture (Renouvellement)</label>
    <referenceTo>blng__InvoicePlan__c</referenceTo>
    <relationshipLabel>Orders (Plan de Facture (Renouvellement))</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

mdapiEYH/objects/OrderItem.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/blng__PendingBillings__c.field-meta.xml
<CustomField>
    <fullName>blng__PendingBillings__c</fullName>
    <inlineHelpText>Total restant à être facturé.</inlineHelpText>
    <label>Pending Billing Amount (without tax)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LPCR_BillingPlanProcessment__c.field-meta.xml
<CustomField>
    <fullName>LPCR_BillingPlanProcessment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billing Plan Processment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LPCR_ContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContractEndDate__c</fullName>
    <label>Date Fin Contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LPCR_ContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContractStartDate__c</fullName>
    <label>Date Début Contrat</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LPCR_DateFin__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateFin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LPCR_TotalContractValue__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TotalContractValue__c</fullName>
    <label>Total Contrat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/LPCR_Uplift__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Uplift__c</fullName>
    <label>Uplift</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__BillingFrequency__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__BillingFrequency__c</fullName>
    <description>Defines the billing frequency.</description>
    <inlineHelpText>Définit la fréquence de facturation.</inlineHelpText>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingFrequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__Contract__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The contract of the subscription that is created from this order product.</description>
    <inlineHelpText>Le contrat d&apos;abonnement créé à partir de ce produit commandé.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__DefaultSubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__DefaultSubscriptionTerm__c</fullName>
    <description>Term length of the subscription, which only applies if the product is a subscription. It is copied from the Subscription Term of the related product when the line item is first
            generated.</description>
    <inlineHelpText>La longueur de la durée d&apos;abonnement, qui s&apos;applique uniquement si le produit est un abonnement. Elle est copiée à partir de la Durée d&apos;abonnement du produit associé
            lors de la génération initiale de l&apos;élément de ligne.</inlineHelpText>
    <label>Default Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote line where this order product is created from.</description>
    <inlineHelpText>La ligne du devis à partir de laquelle ce produit commandé est créé.</inlineHelpText>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>OrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__RevisedOrderProduct__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RevisedOrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>References the order product that this order product revises.</description>
    <inlineHelpText>Référence le produit commandé qui est révisé par ce produit commandé.</inlineHelpText>
    <label>Revised Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Products (Revised Order Product)</relationshipLabel>
    <relationshipName>RevisingOrderProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SBQQ__TerminatedDate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__TerminatedDate__c</fullName>
    <description>Date that this order product&apos;s related subscription was terminated</description>
    <inlineHelpText>Date de fin de l&apos;abonnement associé à ce produit commandé</inlineHelpText>
    <label>Terminated Date</label>
    <type>Date</type>
</CustomField>

mdapiEYH/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Defines the billing frequency.</description>
        <inlineHelpText>Defines the billing frequency.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingFrequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__DefaultSubscriptionTerm__c</fullName>
        <description>Term length of the subscription, which only applies if the product is a subscription. It is copied from the Subscription Term of the related product when the line item is first generated.</description>
        <inlineHelpText>Term length of the subscription, which only applies if the product is a subscription. It is copied from the Subscription Term of the related product when the line item is first generated.</inlineHelpText>
        <label>Default Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProrateMultiplier__c</fullName>
        <description>Calculated ratio used to compute Prorated Price.</description>
        <inlineHelpText>Calculated ratio used to compute Prorated Price.</inlineHelpText>
        <label>Prorate Multiplier</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>blng__BillableUnitPrice__c</fullName>
        <description>The unprorated amount that will bill each billing period. Equals ((TotalPrice * BillingFrequency) / (ProrateMultiplier * DefaultSubscriptionTerm)).</description>
        <formula>IF(ISPICKVAL(SBQQ__ChargeType__c , &apos;One-Time&apos;),  SBQQ__NetTotal__c,
        (SBQQ__NetTotal__c * (CASE(SBQQ__BillingFrequency__c,
        &quot;Monthly&quot;, 1,
        &quot;Quarterly&quot;, 3,
        &quot;Semiannual&quot;, 6,
        &quot;Annual&quot;, 12,
        0))) / ( SBQQ__ProrateMultiplier__c * SBQQ__DefaultSubscriptionTerm__c )
        )</formula>
        <inlineHelpText>The unprorated amount that will bill each billing period. Equals ((TotalPrice * BillingFrequency) / (ProrateMultiplier * DefaultSubscriptionTerm)).</inlineHelpText>
        <label>Billable Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/classes/APB015_ProcessBillingPlanLines.cls
/**
* @author Saurabh
* @date 06/08/2020
* @Description Batch for Process Amended Billing Plan Lines
*/
 
global class APB015_ProcessBillingPlanLines implements Database.Batchable<sObject>,Schedulable{
    String query;
    
    global APB015_ProcessBillingPlanLines() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(
            [SELECT Id, OrderId, TotalPrice,SBQQ__DefaultSubscriptionTerm__c,LPCR_Uplift__c,LPCR_ContractStartDate__c,LPCR_ContractEndDate__c,ServiceDate,EndDate, 
                    blng__BillableUnitPrice__c, SBQQ__BillingFrequency__c,SBQQ__RevisedOrderProduct__r.SBQQ__BillingFrequency__c, blng__NextChargeDate__c,
                    SBQQ__Contract__c,SBQQ__Contract__r.LPCR_DateFin__c,SBQQ__QuoteLine__r.SBQQ__ProrateMultiplier__c,Order.LPCR_RenouvellementPlanFacture__c,
                    LPCR_BillingPlanProcessment__c,SBQQ__RevisedOrderProduct__c,SBQQ__RevisedOrderProduct__r.blng__LastChargeToDate__c,SBQQ__RevisedOrderProduct__r.Quantity,
                    SBQQ__TerminatedDate__c,SBQQ__RevisedOrderProduct__r.SBQQ__TerminatedDate__c,blng__PendingBillings__c,Quantity,SBQQ__RevisedOrderProduct__r.blng__PendingBillings__c 
                FROM OrderItem 
                    WHERE 
                        SBQQ__BillingFrequency__c != null AND 
                        SBQQ__RevisedOrderProduct__c != null AND 
                        LPCR_BillingPlanProcessment__c = false AND 
                        (
                            (SBQQ__BillingFrequency__c != 'Invoice Plan' AND SBQQ__TerminatedDate__c != null AND blng__PendingBillings__c < 0) OR 
                            (SBQQ__TerminatedDate__c != null AND SBQQ__BillingFrequency__c = 'Invoice Plan' AND Quantity < 0)
                        )
            ]);
    }
    
    global void execute(Database.BatchableContext BC, List<OrderItem> scope) {
        String ErrMsg;
        UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines',
                                                        'APB015_ProcessBillingPlanLines', 'Batch' , null,
                                                        'Execute method started with scope : ' + String.valueOf(scope), 
                                                        UM010_Constant.SUCCESS); 
        PAD.log('APB015_ProcessBillingPlanLines', 'execute', 'scope to execute : ' + scope);
        // Managing proration in case of amendment (Monthly / Quarterly / Semi Annual)
        Map<Id, LPCR_PlanFacturation__c> billingPlanMap = new Map<Id, LPCR_PlanFacturation__c>();
        Map<Id, LPCR_PlanFacturation__c> rpBillingPlanMap = new Map<Id, LPCR_PlanFacturation__c>();
        List<LPCR_LignePlanFacturation__c> billingPlanLineList = new List<LPCR_LignePlanFacturation__c>();
        List<LPCR_LignePlanFacturation__c> tmpBillingPlanLineList = new List<LPCR_LignePlanFacturation__c>();
        Set<Id> selectedOrderItemId = new Set<Id>();
        Set<Id> revisedOrderProductId = new Set<Id>();
        Set<String> orderInvPlanIdsSet = new Set<String>();
        Map<Id, List<blng__BillingTransaction__c>> billingTransactionMap = new Map<Id, List<blng__BillingTransaction__c>>();
        Map<Id, List<blng__BillingTransaction__c>> rpBillingTransactionMap = new Map<Id, List<blng__BillingTransaction__c>>();

        for(OrderItem eachOrderItem : scope){

            // create billing plan record
            LPCR_PlanFacturation__c billingPlan = new LPCR_PlanFacturation__c();
            billingPlan.LPCR_OrderItem__c = eachOrderItem.Id;
            billingPlan.LPCR_BillingFrequency__c = eachOrderItem.SBQQ__BillingFrequency__c;
            //billingPlan.LPCR_TotalContractValue__c = totalFullYearPrice;
            billingPlan.LPCR_StartDate__c = eachOrderItem.ServiceDate;
            billingPlan.LPCR_EndDate__c = eachOrderItem.EndDate;
            billingPlanMap.put(eachOrderItem.Id, billingPlan);
            
            if(eachOrderItem.SBQQ__BillingFrequency__c != 'Invoice Plan' && eachOrderItem.SBQQ__TerminatedDate__c != null && eachOrderItem.blng__PendingBillings__c < 0){
                                               
                // create billing plan line record
                LPCR_LignePlanFacturation__c newBPLine = new LPCR_LignePlanFacturation__c();
                newBPLine.LPCR_Amount__c = eachOrderItem.blng__PendingBillings__c;
                newBPLine.LPCR_StartDate__c = eachOrderItem.ServiceDate;
                newBPLine.LPCR_EndDate__c = eachOrderItem.EndDate;
                newBPLine.LPCR_OrderItem__c = eachOrderItem.id;
                newBPLine.LPCR_BillingFrequency__c = eachOrderItem.SBQQ__BillingFrequency__c;
                newBPLine.LPCR_Quantity__c = eachOrderItem.Quantity;
                
                if(eachOrderItem.SBQQ__RevisedOrderProduct__c != null && newBPLine.LPCR_StartDate__c > eachOrderItem.SBQQ__RevisedOrderProduct__r.blng__LastChargeToDate__c){
                    eachOrderItem.LPCR_ExclureDuPlanFacturation__c = true; 
                }
                
                if(eachOrderItem.SBQQ__RevisedOrderProduct__c != null && eachOrderItem.SBQQ__RevisedOrderProduct__r.blng__LastChargeToDate__c < eachOrderItem.SBQQ__RevisedOrderProduct__r.SBQQ__TerminatedDate__c && eachOrderItem.SBQQ__RevisedOrderProduct__r.blng__PendingBillings__c > 0){
                    newBPLine.LPCR_EndDate__c = eachOrderItem.SBQQ__RevisedOrderProduct__r.SBQQ__TerminatedDate__c;
                    billingPlan.LPCR_EndDate__c = eachOrderItem.SBQQ__RevisedOrderProduct__r.SBQQ__TerminatedDate__c;
                }
                eachOrderItem.LPCR_TraitementLigneFacturationAvenant__c = true;
                billingPlanMap.put(eachOrderItem.Id, billingPlan);
                billingPlanLineList.add(newBPLine);
                
            }else if(eachOrderItem.SBQQ__TerminatedDate__c != null && eachOrderItem.SBQQ__BillingFrequency__c == 'Invoice Plan' && eachOrderItem.Quantity < 0){

                selectedOrderItemId.add(eachOrderItem.Id);
                if(eachOrderItem.SBQQ__RevisedOrderProduct__c != null){
                    revisedOrderProductId.add(eachOrderItem.SBQQ__RevisedOrderProduct__r.id);
                }                 
            }            
        }
        
        if(billingPlanMap.size() > 0){
            try {
                insert billingPlanMap.values();
                UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines',
                                                        'APB015_ProcessBillingPlanLines', 'Batch' , null,
                                                        'Successfully inserted list of billing plan list : ' + String.valueOf(billingPlanMap.values()), 
                                                        UM010_Constant.SUCCESS); 
                PAD.log('APB015_ProcessBillingPlanLines', 'execute', 'Insert success of Billing Plan lines : ' + billingPlanMap.values());
            } catch (Exception e) {
                ErrMsg = e.getMessage();
                PAD.log('APB015_ProcessBillingPlanLines', 'execute', 'Insert Error of Billing Plan lines : ' + e.getMessage()+ '|Line :' + e.getLineNumber());
            }finally {
                if(ErrMsg != null && String.isNotBlank(ErrMsg)){
                    UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines','APB015_ProcessBillingPlanLines', 'Batch' , null,'Error while inserting billing plan list. Error : ' + ErrMsg, UM010_Constant.ERROR);              
                }
            } 
        }
        
        // construct a map of Billing Transaction
        for(blng__BillingTransaction__c eachTransaction : [SELECT Id, Name,blng__Amount__c, blng__BillingSchedule__r.blng__OrderProduct__c, blng__BillingTargetDate__c,blng__OverrideBillingTargetDate__c 
                                                                FROM blng__BillingTransaction__c 
                                                                WHERE blng__BillingSchedule__r.blng__OrderProduct__c IN: selectedOrderItemId ]){
            
            if(!billingTransactionMap.containsKey(eachTransaction.blng__BillingSchedule__r.blng__OrderProduct__c)){
                billingTransactionMap.put(eachTransaction.blng__BillingSchedule__r.blng__OrderProduct__c, new List<blng__BillingTransaction__c>());
            }
            billingTransactionMap.get(eachTransaction.blng__BillingSchedule__r.blng__OrderProduct__c).add(eachTransaction);
        }
        
        for(blng__BillingTransaction__c eachTransaction : [SELECT Id, Name,blng__Amount__c, blng__BillingSchedule__r.blng__OrderProduct__c, blng__BillingTargetDate__c,blng__OverrideBillingTargetDate__c 
                                                                FROM blng__BillingTransaction__c 
                                                                WHERE blng__BillingSchedule__r.blng__OrderProduct__c IN: revisedOrderProductId AND blng__Status__c = 'Pending' ]){
            
            if(!rpBillingTransactionMap.containsKey(eachTransaction.blng__BillingSchedule__r.blng__OrderProduct__c)){
                rpBillingTransactionMap.put(eachTransaction.blng__BillingSchedule__r.blng__OrderProduct__c, new List<blng__BillingTransaction__c>());
            }
            rpBillingTransactionMap.get(eachTransaction.blng__BillingSchedule__r.blng__OrderProduct__c).add(eachTransaction);
        }
        
        
        for(OrderItem eachOrderItem : scope) {

            if(eachOrderItem.SBQQ__TerminatedDate__c != null && eachOrderItem.SBQQ__BillingFrequency__c == 'Invoice Plan' && eachOrderItem.Quantity < 0) {

                if(billingTransactionMap.containsKey(eachOrderItem.Id)){

                    for(blng__BillingTransaction__c eachTransaction : billingTransactionMap.get(eachOrderItem.Id)){

                        // create billing plan line record
                        LPCR_LignePlanFacturation__c newBPLine = new LPCR_LignePlanFacturation__c();
                        newBPLine.LPCR_Amount__c = eachTransaction.blng__Amount__c;
                        newBPLine.LPCR_StartDate__c = (eachTransaction.blng__OverrideBillingTargetDate__c != null)?eachTransaction.blng__OverrideBillingTargetDate__c:eachTransaction.blng__BillingTargetDate__c;
                        newBPLine.LPCR_EndDate__c = (eachTransaction.blng__OverrideBillingTargetDate__c != null)?eachTransaction.blng__OverrideBillingTargetDate__c:eachTransaction.blng__BillingTargetDate__c;
                        newBPLine.LPCR_OrderItem__c = eachOrderItem.id;
                        newBPLine.LPCR_BillingFrequency__c = eachOrderItem.SBQQ__BillingFrequency__c;
                        newBPLine.LPCR_Quantity__c = eachOrderItem.Quantity;
                        newBPLine.LPCR_PlanFacturation__c = billingPlanMap.get(eachOrderItem.id).id;
                        billingPlanLineList.add(newBPLine);
                        
                        if (eachOrderItem.SBQQ__RevisedOrderProduct__c != null && newBPLine.LPCR_StartDate__c > eachOrderItem.SBQQ__RevisedOrderProduct__r.SBQQ__TerminatedDate__c){
                            eachOrderItem.LPCR_ExclureDuPlanFacturation__c = true; 
                        }
                    }
                    eachOrderItem.LPCR_TraitementLigneFacturationAvenant__c = true;
                }
                
                if (rpBillingTransactionMap.containsKey(eachOrderItem.SBQQ__RevisedOrderProduct__c)){

                    Double sumAmount = 0;
                    Date overrideBillingTargetDate = null;
                    
                    // create billing plan record
                    LPCR_PlanFacturation__c billingPlan = new LPCR_PlanFacturation__c();
                    billingPlan.LPCR_OrderItem__c = eachOrderItem.SBQQ__RevisedOrderProduct__c;
                    billingPlan.LPCR_BillingFrequency__c = eachOrderItem.SBQQ__RevisedOrderProduct__r.SBQQ__BillingFrequency__c;
                    //billingPlan.LPCR_TotalContractValue__c = totalFullYearPrice;
                    
                    for (blng__BillingTransaction__c eachTransaction : rpBillingTransactionMap.get(eachOrderItem.SBQQ__RevisedOrderProduct__c)) {
                        sumAmount += eachTransaction.blng__Amount__c;
                        overrideBillingTargetDate = eachTransaction.blng__OverrideBillingTargetDate__c;
                    }
                    
                    billingPlan.LPCR_StartDate__c = eachOrderItem.ServiceDate;
                    billingPlan.LPCR_EndDate__c = eachOrderItem.EndDate;
                    rpBillingPlanMap.put(eachOrderItem.SBQQ__RevisedOrderProduct__c,billingPlan);
                    
                    // create billing plan line record
                    LPCR_LignePlanFacturation__c newBPLine = new LPCR_LignePlanFacturation__c();
                    newBPLine.LPCR_Amount__c = sumAmount;
                    newBPLine.LPCR_StartDate__c = overrideBillingTargetDate;
                    newBPLine.LPCR_EndDate__c = overrideBillingTargetDate;
                    newBPLine.LPCR_OrderItem__c = eachOrderItem.SBQQ__RevisedOrderProduct__c;
                    newBPLine.LPCR_BillingFrequency__c = eachOrderItem.SBQQ__BillingFrequency__c;
                    newBPLine.LPCR_Quantity__c = eachOrderItem.SBQQ__RevisedOrderProduct__r.Quantity;
                    //newBPLine.LPCR_PlanFacturation__c = billingPlanMap.get(eachOrderItem.id).id;
                    tmpBillingPlanLineList.add(newBPLine);
                }                
            }
        }
        
        // insert new billing plan record
        ErrMsg = null;
        if (rpBillingPlanMap.size() > 0) {
            try {
                insert rpBillingPlanMap.values();
                PAD.log('APB015_ProcessBillingPlanLines', 'execute', 'Insert success of Billing Plan lines : ' + rpBillingPlanMap.values());
                UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines',
                                                                'APB015_ProcessBillingPlanLines', 'Batch' , null,
                                                                'Successfully inserted list of billing plan list : ' + String.valueOf(rpBillingPlanMap.values()), 
                                                                UM010_Constant.SUCCESS); 
                                                                
                for (LPCR_LignePlanFacturation__c eachBPLine : tmpBillingPlanLineList){

                    if (rpBillingPlanMap.containsKey(eachBPLine.LPCR_OrderItem__c)){

                        eachBPLine.LPCR_PlanFacturation__c = rpBillingPlanMap.get(eachBPLine.LPCR_OrderItem__c).Id;
                        billingPlanLineList.add(eachBPLine);
                    }
                }
            }catch(Exception ex){
                ErrMsg = ex.getMessage();
                PAD.log('APB015_ProcessBillingPlanLines', 'execute', 'Insert Error of Billing Plan lines : ' + ex.getMessage()+ '|Line :' + ex.getLineNumber());
            }finally {
                if(ErrMsg != null && String.isNotBlank(ErrMsg)){
                    UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines','APB015_ProcessBillingPlanLines', 'Batch' , null,'Error while inserting billing plan list. Error : ' + ErrMsg, UM010_Constant.ERROR);              
                }
            } 
        }

        ErrMsg = null;
        // insert billing plan line list
        try {
            insert billingPlanLineList;
            UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines',
                                                            'APB015_ProcessBillingPlanLines', 'Batch' , null,
                                                            'Successfully inserted list of billing plan lines : ' + String.valueOf(billingPlanLineList), 
                                                            UM010_Constant.SUCCESS); 
            PAD.log('APB015_ProcessBillingPlanLines', 'execute', 'Insert success of Billing Plan lines : ' + billingPlanLineList);
        } catch (Exception e) {
            ErrMsg = e.getMessage();
        } finally {
            if(ErrMsg != null && String.isNotBlank(ErrMsg)){
                UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines','APB015_ProcessBillingPlanLines', 'Batch' , null,'Error while updating billing plan lines. Error : ' + ErrMsg, UM010_Constant.ERROR);              
            }
        }  
        
        // update order item
        ErrMsg = null;
        if(scope.size() > 0){
            try{
                update scope;
                UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines',
                                                                'APB015_ProcessBillingPlanLines', 'Batch' , null,
                                                                'Successfully updated list of order items : ' + String.valueOf(scope), 
                                                                UM010_Constant.SUCCESS); 
                PAD.log('APB015_ProcessBillingPlanLines', 'execute', 'Update Success of Order items : ' + scope);
            }catch(Exception ex){
                ErrMsg = ex.getMessage();
                PAD.log('APB015_ProcessBillingPlanLines', 'execute', 'Update Error of Order items : ' + ex.getMessage() + '|Line :' + ex.getLineNumber());
            }finally {
                if(ErrMsg != null && String.isNotBlank(ErrMsg)){
                    UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for Process Amended Billing Plan Lines','APB015_ProcessBillingPlanLines', 'Batch' , null,'Error while updating order items. Error : ' + ErrMsg, UM010_Constant.ERROR);              
                }
            }  
        }
   
    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
    global void execute(SchedulableContext sc) {
        
        APB015_ProcessBillingPlanLines sc1 = new APB015_ProcessBillingPlanLines();
        Datetime dt = Datetime.now().addMinutes(30);  // i.e. 30 mins
        String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB015_ProcessBillingPlanLines');
        
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB015_ProcessBillingPlanLines();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 30 mins
                Id schedId = System.Schedule('APB015_ProcessBillingPlanLines'+timeForScheduler,timeForScheduler,new APB015_ProcessBillingPlanLines());
            }
        }  
        
    }
}