mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/LPCR_ModificationEntrante__c.object
<CustomObject>
    <description>Cet objet nous permettra de collecter les données en provenance d&apos;Intranet et de la GTA  concernant des événements et liés à de l&apos;usage sur SF (absences, heures déduites, maladie ...)</description>
    <label>Modification Entrante</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modifications Entrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contrat Salesforce</description>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteContrat</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Devis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Devis</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteDevis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Evenement__c</fullName>
        <label>Evènement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Modification Adresse Contact Parent</fullName>
                </value>
                <value>
                    <fullName>Modification Autorité Parentale</fullName>
                </value>
                <value>
                    <fullName>Modification Numéro Allocataire</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Handicapé Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Type Accueil</fullName>
                </value>
                <value>
                    <fullName>Modification Type Planning</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Montant Ressource</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Jour Congé</fullName>
                </value>
                <value>
                    <fullName>Date Fin Contrat</fullName>
                </value>
                <value>
                    <fullName>Modification Section</fullName>
                </value>
                <value>
                    <fullName>Date Naissance Enfant</fullName>
                </value>
                <value>
                    <fullName>Modification Mode Garde</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Familiale</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Mois Mensualisé</fullName>
                </value>
                <value>
                    <fullName>Modification Traitement Jour férié</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Modification Délai Carence</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Supplémentaire MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Occasionnel MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Congés MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Déduite MAC</fullName>
                </value>
                <value>
                    <fullName>Validation Contrat Directrice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EM016_ModificationEntranteEntity_Test.cls
@isTest
public with sharing class EM016_ModificationEntranteEntity_Test {
    @isTest
    static void EM016_ModificationEntranteEntity_Test() {//TEST
        EM016_ModificationEntranteEntity entity = new EM016_ModificationEntranteEntity();
        Account acc = UM002_TestDataFactory.createAccount('test acc');
        insert acc;
        Contract contract = UM002_TestDataFactory.createContract(acc.id);	
        insert contract;
        List<Opportunity> oppties = UM002_TestDataFactory.createOpportunities(1, 'test opp', 'Prospecting');
        insert oppties;
        SBQQ__Quote__c quote = UM002_TestDataFactory.createQuotes(1, new List<Account>{acc}, oppties).get(0);
        insert quote;
        LPCR_ModificationEntrante__c tempModif = new LPCR_ModificationEntrante__c(
                                    LPCR_Devis__c  = quote.Id,
                                    LPCR_Contract__c = contract.Id,
                                    LPCR_Evenement__c  = 'EVT_VALIDATION_CONTRAT_DIRECTRICE');
        insert tempModif;
        
        Test.startTest();
        List<LPCR_ModificationEntrante__c> listModifs = new List<LPCR_ModificationEntrante__c>{tempModif};
        List<LPCR_ModificationEntrante__c> tempModifResult = EM016_ModificationEntranteEntity.getModifEntranteById(listModifs);
        Test.stopTest();

        System.assertEquals(1, tempModifResult.size());

    }
}