mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__AmendmentStartDate__c</fullName>
        <description>Start Date of your Amendment. If blank, Amendment will start on today&apos;s date.</description>
        <inlineHelpText>Date de début de votre amendement. Si la date est vide, l&apos;amendement commence à la date du jour.</inlineHelpText>
        <label>Amendment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_DateRevisionPrix__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateRevisionPrix__c</fullName>
    <inlineHelpText>Si Révision de prix (%) non renseigné, la facturation de la commande sera suspendue à cette date.</inlineHelpText>
    <label>Date de révision de prix</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_InitAutoAvecDateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_InitAutoAvecDateDebut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Init auto avec date debu</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/LPCR_Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Nom de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APB025_MAJChampAmendment.cls
global class APB025_MAJChampAmendment implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable {
    //Batch to be executed for update of Date amendement for uplift to be included in desired date 
    String query;
    final String ClassName = APB025_MAJChampAmendment.class.getName();
    global APB025_MAJChampAmendment() {
        
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {

        UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'start', 'Batch' , null, 'Starting Batch', UM010_Constant.SUCCESS);
        //select Contract for which amendement indexation needs to be created
        return Database.getQueryLocator([Select id ,LPCR_IndexationConvenue__c,LPCR_DateRevisionPrix__c,LPCR_InitAutoAvecDateDebut__c,SBQQ__RenewalUpliftRate__c,SBQQ__Order__c From Contract where  LPCR_DateRevisionPrix__c !=null]);
                                        
    }
    public void execute(Database.BatchableContext BC, list<Contract> scope){
        List<Contract> lstContractUpd= new List<Contract>();
        List<LPCR_Log__c> listOfLog = new List<LPCR_Log__c>();
		for(Contract tmpContract : scope){
			tmpContract.SBQQ__AmendmentStartDate__c=tmpContract.LPCR_DateRevisionPrix__c;
           	lstContractUpd.add(tmpContract);
            listOfLog.add(UM001_LogManager.getWriteLogActivityForBulkInsert('', ClassName, 'Batch', String.valueOf(tmpContract.Id), '', 'SUCCESS'));             
           
        }
        if(lstContractUpd.size() > 0 ){
            update lstContractUpd;
            insert listOfLog;
        }
        
    }
    public void finish(Database.BatchableContext BC){
        UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'finish', 'Batch' , null, 'Finished Batch Processing', UM010_Constant.SUCCESS);
        PAD.log(ClassName, 'finish', 'Start finish method');
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB023_CreateIndexationAmendment');
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        if(!isBatchJobRunning && !isJobQueueFull && !Test.isRunningTest()) {
            PAD.log(ClassName, 'finish', 'launching APB023_CreateIndexationAmendment');
		    Database.executeBatch(new APB023_CreateIndexationAmendment(), 1);
        }
    }
    global void execute(SchedulableContext sc) {
    }
}