mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapiEYH/objects/LPCR_ModificationEntrante__c.object
<CustomObject>
    <description>Cet objet nous permettra de collecter les données en provenance d&apos;Intranet et de la GTA  concernant des événements et liés à de l&apos;usage sur SF (absences, heures déduites, maladie ...)</description>
    <label>Modification Entrante</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modifications Entrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contrat Salesforce</description>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteContrat</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Evenement__c</fullName>
        <label>Evènement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Modification Adresse Contact Parent</fullName>
                </value>
                <value>
                    <fullName>Modification Autorité Parentale</fullName>
                </value>
                <value>
                    <fullName>Modification Numéro Allocataire</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Handicapé Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Type Accueil</fullName>
                </value>
                <value>
                    <fullName>Modification Type Planning</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Montant Ressource</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Jour Congé</fullName>
                </value>
                <value>
                    <fullName>Date Fin Contrat</fullName>
                </value>
                <value>
                    <fullName>Modification Section</fullName>
                </value>
                <value>
                    <fullName>Date Naissance Enfant</fullName>
                </value>
                <value>
                    <fullName>Modification Mode Garde</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Familiale</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Mois Mensualisé</fullName>
                </value>
                <value>
                    <fullName>Modification Traitement Jour férié</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Modification Délai Carence</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Supplémentaire MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Occasionnel MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Congés MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Déduite MAC</fullName>
                </value>
                <value>
                    <fullName>Validation Contrat Directrice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EM016_ModificationEntranteEntity.cls
/**
* @author Hanae MAKBOUB
* @date 15/05/2020
* @Description Queries about LPCR_ModificationEntrante__c
*/
public with sharing class EM016_ModificationEntranteEntity extends EM001_AbstractObjectEntity{
    
    public EM016_ModificationEntranteEntity(){
        super('LPCR_ModificationEntrante__c');
    }
    
    public static List<LPCR_ModificationEntrante__c> getModifEntranteById(List<LPCR_ModificationEntrante__c> modifId){
        return [SELECT Id, LPCR_Evenement__c,LPCR_Contract__c,LPCR_Contract__r.SBQQ__Quote__c  FROM LPCR_ModificationEntrante__c WHERE LPCR_Evenement__c  = 'EVT_VALIDATION_CONTRAT_DIRECTRICE' AND id =:modifId];
    }
	
}