mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ContractEntreprise__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContractEntreprise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat Entreprise</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contrats Familles</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_ProcessIdRenouvellementContrat__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ProcessIdRenouvellementContrat__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flag Batch Id Renouvellement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Accueil.recordType-meta.xml
<RecordType>
    <fullName>Accueil</fullName>
    <active>true</active>
    <label>Accueil</label>
</RecordType>

mdapiEYH/objects/LPCR_Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Nom de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiEYH/objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Entreprise</fullName>
        <active>true</active>
        <businessProcess>Opportunité Entreprise%2FAO Privé%2FPartenaire</businessProcess>
        <label>Entreprise</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_ContractEntreprise__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContractEntreprise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat Entreprise</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Quotes (Contrat Entreprise)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Accueil.recordType-meta.xml
<RecordType>
    <fullName>Accueil</fullName>
    <active>true</active>
    <label>Contrat D’accueil</label>
</RecordType>

force-app/main/default/classes/APB017_UpdateIdRenouvellementContrat.cls
/**
* @author Saurabh Singh
* @date 29/10/2020
* @Description Task IS-1848
*/
global class APB017_UpdateIdRenouvellementContrat implements Database.Batchable<sObject>,Schedulable {
    
    private static final Id CONTRACT_ACCUEIL_RT_ID = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Contract, Label.LPCR_ContratA);
    
    global APB017_UpdateIdRenouvellementContrat() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__c,LPCR_ProcessIdRenouvellementContrat__c FROM Contract WHERE LPCR_ProcessIdRenouvellementContrat__c = true AND SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__c != null ';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contract> scope) {
        PAD.log('APB017_UpdateIdRenouvellementContrat','execute','scope to execute : '+scope);        
        
        List<Contract> updateContractB2C = new List<Contract>();
        List<Contract> updateContractB2B = new List<Contract>();
        
        Map<String, String> b2bContractIdsMap = new Map<String, String>();
        Map<String, Contract> b2bUpdateContractMap = new Map<String, Contract>();
        List<LPCR_Log__c> listOfLog = new List<LPCR_Log__c>();
        
        for(Contract eachContract : scope){
            b2bContractIdsMap.put(eachContract.SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__c,eachContract.id);
            b2bUpdateContractMap.put(eachContract.SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__c,eachContract);
        }
        
        PAD.log('APB017_UpdateIdRenouvellementContrat','execute','b2bContractIdsMap : '+b2bContractIdsMap);
        
        // Query B2C Contract (Contract.RecordType = 'Accueil')
        for(Contract eachB2CContract : [SELECT Id,LPCR_ContractEntreprise__c FROM Contract WHERE LPCR_ContractEntreprise__c IN : b2bContractIdsMap.keySet() AND recordtypeid =: CONTRACT_ACCUEIL_RT_ID ]){
            PAD.log('APB017_UpdateIdRenouvellementContrat','execute','before eachB2CContract : '+eachB2CContract);
            if(b2bContractIdsMap.keyset().contains(eachB2CContract.LPCR_ContractEntreprise__c)){
                b2bUpdateContractMap.get(eachB2CContract.LPCR_ContractEntreprise__c).LPCR_ProcessIdRenouvellementContrat__c = false;
                eachB2CContract.LPCR_ContractEntreprise__c = b2bContractIdsMap.get(eachB2CContract.LPCR_ContractEntreprise__c);                 
                updateContractB2C.add(eachB2CContract);
            }
            listOfLog.add(UM001_LogManager.getWriteLogActivityForBulkInsert('Update Contract Entreprise', 'APB017_UpdateIdRenouvellementContrat', 'Batch', String.valueOf(eachB2CContract.Id), '', 'SUCCESS'));  
        }        
        
        // update B2C and B2B contract records
        if(updateContractB2C.size() > 0){
            try{
                update updateContractB2C;
                update b2bUpdateContractMap.values();
                insert listOfLog;
            }catch(Exception ex){
                PAD.log('APB017_UpdateIdRenouvellementContrat','execute','Exception : '+ex.getMessage());
            }
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
    global void execute(SchedulableContext sc) {
        PAD.log('APB017_UpdateIdRenouvellementContrat','execute','sc');
        APB017_UpdateIdRenouvellementContrat sc1 = new APB017_UpdateIdRenouvellementContrat();
        
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB017_UpdateIdRenouvellementContrat');
        
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB017_UpdateIdRenouvellementContrat();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 30 mins
                sc1 = new APB017_UpdateIdRenouvellementContrat();
                Datetime dt = Datetime.now().addMinutes(30);  // i.e. 30 mins
                String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
                Id schedId = System.Schedule('APB017_UpdateIdRenouvellementContrat'+timeForScheduler,timeForScheduler,sc1);
            }
        }  
        
    } 
    
}