mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Enfant</fullName>
        <active>true</active>
        <label>Enfant</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutJeudi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutJeudi__c</fullName>
    <label>Heure de début jeudi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutLundi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutLundi__c</fullName>
    <label>Heure de début lundi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutMardi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutMardi__c</fullName>
    <label>Heure de début mardi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutMercredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutMercredi__c</fullName>
    <label>Heure de début mercredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutVendredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutVendredi__c</fullName>
    <label>Heure de début vendredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinJeudi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinJeudi__c</fullName>
    <label>Heure de fin jeudi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinLundi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinLundi__c</fullName>
    <label>Heure de fin lundi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinMardi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinMardi__c</fullName>
    <label>Heure de fin mardi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinMercredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinMercredi__c</fullName>
    <label>Heure de fin mercredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinVendredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinVendredi__c</fullName>
    <label>Heure de fin vendredi</label>
    <type>Time</type>
</CustomField>

mdapiEYH/objects/LPCR_Preinscription__c.object
<CustomObject>
    <description>Objet servant à stocker les réponses aux formulaires de préinscription remplis par les familles par l&apos;intermédiare de FormAssembly</description>
    <label>Préinscription</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Numéro de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Préinscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Préinscriptions (Crèche)</relationshipLabel>
        <relationshipName>PreinscriptionsCreche</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateEntreeCreche__c</fullName>
        <label>Date d&apos;entrée en crèche</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateEntreeEntreprise__c</fullName>
        <label>Date d&apos;entrée dans l&apos;entreprise</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutJeudi__c</fullName>
        <label>Heure de début jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutLundi__c</fullName>
        <label>Heure de début lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMardi__c</fullName>
        <label>Heure de début mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMercredi__c</fullName>
        <label>Heure de début mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutVendredi__c</fullName>
        <label>Heure de début vendredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinJeudi__c</fullName>
        <label>Heure de fin jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinLundi__c</fullName>
        <label>Heure de fin lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMardi__c</fullName>
        <label>Heure de fin mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMercredi__c</fullName>
        <label>Heure de fin mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinVendredi__c</fullName>
        <label>Heure de fin vendredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_ReponseCrecheMunicipale__c</fullName>
        <label>Reponse crèche municipale</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_Revenu__c</fullName>
        <label>Revenu</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SM020_PresinscriptionInvockeService_Test.cls
/**
* @author Saurabh
* @date 02/07/2020
* @description Test class for SM020_PresinscriptionInvockeService
*/

@isTest
public class SM020_PresinscriptionInvockeService_Test {
	@isTest
    static void presinscriptionSendEmail_Test(){
        Test.setMock(HttpCalloutMock.class, new MCK001_LPCRHttpCalloutMockImpl());
        Id enfantContactRecordTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName('Contact', 'Enfant');
        Account acc = UM002_TestDataFactory.createAccount('test');
        insert acc;
        UM002_TestDataFactory.ContactTdf c = new UM002_TestDataFactory.ContactTdf();
        Contact contact= c.create('Test','Test', acc);
        contact.RecordTypeId = enfantContactRecordTypeId;
        insert contact;
        LPCR_Preinscription__c  preinsciption = UM002_TestDataFactory.createPreinscription('test', 'test',acc.Id,contact.Id );
        preinsciption.LPCR_HeureDebutLundi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinLundi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_HeureDebutMardi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinMardi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_HeureDebutMercredi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinMercredi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_HeureDebutJeudi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinJeudi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_HeureDebutVendredi__c   = DateTime.newInstance(2020, 01, 01, 8, 0, 0).Time();
        preinsciption.LPCR_HeureFinVendredi__c    = DateTime.newInstance(2020, 01, 01, 16, 0, 0).Time();
        
        preinsciption.LPCR_Creche__c = acc.Id;
        preinsciption.LPCR_ReponseCrecheMunicipale__c='Refus';
        preinsciption.LPCR_DateEntreeCreche__c= Date.newInstance(2020, 09, 01);
        preinsciption.LPCR_DateEntreeEntreprise__c = Date.today().addDays(-3);
        preinsciption.LPCR_Revenu__c =12000;
        
        insert preinsciption;
        
        Test.startTest();
        
        List<SM020_PresinscriptionInvockeService.PresinscriptionParameter> presinscriptionParameters = new List<SM020_PresinscriptionInvockeService.PresinscriptionParameter>();
        SM020_PresinscriptionInvockeService.PresinscriptionParameter perms = new SM020_PresinscriptionInvockeService.PresinscriptionParameter();
        perms.presinscriptionId = preinsciption.id;
        perms.fromEmail = 'test@mail.com';
        perms.toEmail = 'mytest@mail.com';
        perms.subject = 'subject';
        perms.body = 'body';
        presinscriptionParameters.add(perms);
        SM020_PresinscriptionInvockeService.presinscriptionSendEmail(presinscriptionParameters);
        
        Test.stopTest();
    }
}