mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__AmendmentStartDate__c</fullName>
        <description>Start Date of your Amendment. If blank, Amendment will start on today&apos;s date.</description>
        <inlineHelpText>Date de début de votre amendement. Si la date est vide, l&apos;amendement commence à la date du jour.</inlineHelpText>
        <label>Amendment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_DateRevisionPrix__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateRevisionPrix__c</fullName>
    <inlineHelpText>Si Révision de prix (%) non renseigné, la facturation de la commande sera suspendue à cette date.</inlineHelpText>
    <label>Date de révision de prix</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_InitAutoAvecDateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_InitAutoAvecDateDebut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Init auto avec date debu</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_TechDateRevisionActuel__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TechDateRevisionActuel__c</fullName>
    <formula>LPCR_DateRevisionPrix__c-35</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LPCR_Tech_DateRevisionActuel</label>
    <type>Date</type>
</CustomField>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeAvenant__c</fullName>
        <label>Type d&apos;avenant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Changement de Prix</fullName>
                </value>
                <value>
                    <fullName>Résiliation</fullName>
                </value>
                <value>
                    <fullName>Ajout/Suppression Berceau</fullName>
                </value>
                <value>
                    <fullName>Modification des termes du contrat</fullName>
                </value>
                <value>
                    <fullName>Modification du type/fréquence de facturation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Rate of renewal price increases.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_DateRevisionPrix__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateRevisionPrix__c</fullName>
    <label>Date de révision de prix</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_InitAutoAvecDateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_InitAutoAvecDateDebut__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field used to know if the billing day of the month has to be setted with Order Start Date</inlineHelpText>
    <label>Facturation spécifique</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/LPCR_IndexationQuote__c.field-meta.xml
<CustomField>
    <fullName>LPCR_IndexationQuote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Indexation Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/LPCR_TypeAvenant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeAvenant__c</fullName>
    <formula>TEXT(SBQQ__Quote__r.LPCR_TypeAvenant__c)</formula>
    <label>Type d&apos;avenant</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/APB023_CreateIndexationAmendment.cls
global class APB023_CreateIndexationAmendment implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable {
    String query;
    final String ClassName = APB023_CreateIndexationAmendment.class.getName();
    final private static String TYPEAVENANT_INDEXATION = 'Amendement d\'indexation';

    global APB023_CreateIndexationAmendment() {
        
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'start', 'Batch' , null, 'Starting Batch', UM010_Constant.SUCCESS);
        Id contratResaID  = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Contract, Label.LPCR_Reservataire);
        //select Contract for which amendement indexation needs to be created
        return Database.getQueryLocator([Select id ,LPCR_IndexationConvenue__c,LPCR_DateRevisionPrix__c,LPCR_InitAutoAvecDateDebut__c,SBQQ__RenewalUpliftRate__c,SBQQ__Order__c From Contract where  LPCR_DateRevisionPrix__c !=null and LPCR_TechDateRevisionActuel__c =TODAY and RecordTypeId =:contratResaID]);
        
    }
    public void execute(Database.BatchableContext BC, list<Contract> scope){
        List<SBQQ__QuoteLine__c> listCloneQuoteLine = new List<SBQQ__QuoteLine__c>();
        List<Contract> lstContractUpd= new List<Contract>();
        for(Contract tmpContract : scope){
            
            UM006_ContractAmender amender = new UM006_ContractAmender();
            WRP001_QuoteModel quote = amender.load(tmpContract.Id);
            UM007_QuoteReader reader = new UM007_QuoteReader();
            WRP001_QuoteModel quoteModel = reader.read(quote.record.id);
            APC006_CloneQuoteLinesIndexation.cloneAndResetQL(quoteModel.record.id, tmpContract.SBQQ__RenewalUpliftRate__c, tmpContract.LPCR_DateRevisionPrix__c);
            
            quoteModel.record.SBQQ__RenewalUpliftRate__c = tmpContract.SBQQ__RenewalUpliftRate__c;
            quoteModel.record.LPCR_DateRevisionPrix__c = tmpContract.LPCR_DateRevisionPrix__c.addYears(1);
            quoteModel.record.LPCR_TypeAvenant__c = TYPEAVENANT_INDEXATION;
            
            SBQQ__Quote__c quote1 = quoteModel.record;
            update quote1;
            
            
            quoteModel = reader.read(quote.record.id);
            
            for(WRP002_QuoteLineModel eachQuoteLine : quoteModel.lineItems){
                if (eachQuoteLine.record.LPCR_IndexationQuote__c  == true) {
                    
                    SBQQ__QuoteLine__c updateQLI = eachQuoteLine.record;
                    listCloneQuoteLine.add(updateQLI);            	
                }
            }
            tmpContract.SBQQ__AmendmentStartDate__c=null;
            lstContractUpd.add(tmpContract);
        }
        if(listCloneQuoteLine.size() > 0 ){
            update listCloneQuoteLine;
        }
        if(lstContractUpd.size() > 0 ){
            update lstContractUpd;
        }
        
    }
    public void finish(Database.BatchableContext BC){
        
        
    }
    global void execute(SchedulableContext sc) {
        APB023_CreateIndexationAmendment sc1 = new APB023_CreateIndexationAmendment();
        //PDO : Modify waiting time for test 
        Datetime dt = Datetime.now().addMinutes(30);
        String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB023_CreateIndexationAmendment');
        
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB023_CreateIndexationAmendment();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 30 mins
                 Id schedId = System.Schedule('APB023_CreateIndexationAmendment'+timeForScheduler,timeForScheduler,new APB023_CreateIndexationAmendment());
            }
        }  
    }
}