mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Parent</fullName>
        <active>true</active>
        <label>Parent</label>
    </recordTypes>
</CustomObject>

mdapiEYH/objects/LPCR_ModificationEntrante__c.object
<CustomObject>
    <description>Cet objet nous permettra de collecter les données en provenance d&apos;Intranet et de la GTA  concernant des événements et liés à de l&apos;usage sur SF (absences, heures déduites, maladie ...)</description>
    <label>Modification Entrante</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modifications Entrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Envoi directrice</fullName>
                </value>
                <value>
                    <fullName>Validé directrice</fullName>
                </value>
                <value>
                    <fullName>Prêt à envoyer</fullName>
                </value>
                <value>
                    <fullName>Envoyé pour signature</fullName>
                </value>
                <value>
                    <fullName>Signé</fullName>
                </value>
                <value>
                    <fullName>Actif</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/SM013_ModificationEntranteServices_Test.cls
/**
* @author Hanae MAKBOUB
* @date 19/05/2020
* @description Test class for Service class LPCR_ModificationEntrante__c
*/
@isTest
public class SM013_ModificationEntranteServices_Test {
    @testSetup 
    static void testSetup(){
        List<Account> accounts = UM002_TestDataFactory.createAccounts(100, 'testAccount');
        List<Opportunity> opps = UM002_TestDataFactory.createOpportunities(100, 'testOpp', 'Prospecting');
        insert accounts;
        insert opps;
        List<SBQQ__Quote__c> quotes = UM002_TestDataFactory.createQuotes(100, accounts, opps);
        insert quotes;
        List<LPCR_ModificationEntrante__c> modifEntrantesValides = UM002_TestDataFactory.createModificationsEntrantes(50,quotes,'Validation Contrat Directrice');
        insert modifEntrantesValides;
        List<LPCR_ModificationEntrante__c> modifEntrantes = UM002_TestDataFactory.createModificationsEntrantes(50,quotes,'Modification Adresse Contact Parent	');
        insert modifEntrantes;
    }
    @isTest
    public static void updateQuotesFromModifEntrantes_Test(){
        System.runAs(UM002_TestDataFactory.createUser()){
            Test.startTest();
        List<SBQQ__Quote__c> quotesValides = [SELECT Id, SBQQ__Status__c FROM SBQQ__Quote__c WHERE SBQQ__Status__c = 'Validé Directrice'];
        System.assertEquals(50, quotesValides.size(), 'Error in SM013_ModificationEntranteServices_Test : problem in updating quotesValides');
        List<SBQQ__Quote__c> quotesNonValides = [SELECT Id, SBQQ__Status__c FROM SBQQ__Quote__c WHERE SBQQ__Status__c != 'Validé Directrice'];
        System.assertEquals(50, quotesNonValides.size(), 'Error in SM013_ModificationEntranteServices_Test : problem in updating quotesNonValides');
        Test.stopTest();
        }
    }
}