mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_BillingFrequency__c</fullName>
        <label>Fréquence de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingFrequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_ChiffreAffaire__c</fullName>
        <label>Chiffre d&apos;affaire</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LPCR_ContratEntreprise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LPCR_ContratEntreprise</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contrats (LPCR_ContratEntreprise)</relationshipLabel>
        <relationshipName>Contrats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Debut</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_MasterDevis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contrat Cadre</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts (Contrat Cadre)</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_MethodeRenouvellement__c</fullName>
        <label>Méthode Renouvellement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tacite</fullName>
                </value>
                <value>
                    <fullName>Express</fullName>
                </value>
                <value>
                    <fullName>Sans renouvellement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_PlanningEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LPCR_PlanningEnfant</label>
        <referenceTo>LPCR_Planning__c</referenceTo>
        <relationshipLabel>Contrats</relationshipLabel>
        <relationshipName>Contrats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_RenouvellementAutomatique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renouvellement Automatique</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LPCR_RenouvellementConvenu__c</fullName>
        <label>Renouvellement Convenu</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeFacturation__c</fullName>
        <label>Type de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Order.object
<CustomObject>
    <fields>
        <fullName>LPCR_MasterDevis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contrat Cadre</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders (Contrat Cadre)</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Order/fields/LPCR_DateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateDebut__c</fullName>
    <label>Date De Début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/LPCR_DateFin__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateFin__c</fullName>
    <label>Date de fin contractuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The quote where the order is created from.</description>
    <inlineHelpText>Le devis à partir duquel la commande est créée.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SBQQ__RenewalUpliftRate__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalUpliftRate__c</fullName>
    <description>Rate of renewal price increases.</description>
    <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
    <label>Renewal Uplift (%)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_ChiffreAffaire__c</fullName>
        <label>Chiffre d&apos;affaire</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LPCR_ContratEntreprise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LPCR_ContratEntreprise</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Devis (LPCR_ContratEntreprise)</relationshipLabel>
        <relationshipName>Devis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_MasterDevis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Ce champs fait référence au devis &apos;agreement quote&apos; associé</description>
        <label>Contrat Cadre</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contrat Référencement</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_MethodeRenouvellement__c</fullName>
        <label>Méthode Renouvellement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tacite</fullName>
                </value>
                <value>
                    <fullName>Express</fullName>
                </value>
                <value>
                    <fullName>Sans renouvellement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_PlanningEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Enfant</label>
        <referenceTo>LPCR_Planning__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_RenouvellementConvenu__c</fullName>
        <label>Renouvellement Convenu</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeEntreprise__c</fullName>
        <formula>TEXT(SBQQ__Account__r.LPCR_TypeEntreprise__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type d&apos;entreprise</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_TypeFacturation__c</fullName>
        <label>Type de facturation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__BillingFrequency__c</fullName>
        <description>Defines the billing frequency.</description>
        <inlineHelpText>Defines the billing frequency.</inlineHelpText>
        <label>Billing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__BillingFrequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Rate of renewal price increases.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/SBQQ__BillingType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arrieree</fullName>
        <label>Arriérée</label>
    </customValue>
    <customValue>
        <fullName>Anticipee</fullName>
        <label>Anticipée</label>
    </customValue>
    <description>Billing type</description>
    <masterLabel>Billing Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SM010_ContractServices.cls
/**
* @author Ayoub Ouarti
* @created 23/03/2020
* @description Service class for Contract Object
* @Updated By Achraf ABOUL(aaboul@salesforce.com) 08/05/2020
*/
public class SM010_ContractServices {
    
    /**
* @Author Ayoub Ouarti
* @Created 23/03/2020
* @Description methode setContractFields to set Contract fields from Quote before Insert
* @Inputs List<Contract> contracts
*/
    public static void setContractFields(List<Contract> contracts){
        Pad.log('SM010_ContractServices','setContractFields(List<Contract> contracts)','contracts size '+contracts.size());

        Set<String> quoteIds = UM003_TypeManager.getFieldsOfListObjects(contracts,'SBQQ__Quote__c');
        Map<Id,SBQQ__Quote__c> quoteMap = new  Map<Id,SBQQ__Quote__c>([SELECT Id,LPCR_TypeFacturation__c,SBQQ__BillingFrequency__c,LPCR_IndexationConvenue__c,LPCR_MasterDevis__c,LPCR_RenouvellementConvenu__c,LPCR_DateDebut__c,LPCR_DateFin__c,LPCR_ChiffreAffaire__c, LPCR_MethodeRenouvellement__c,SBQQ__RenewalUpliftRate__c,LPCR_TypeEntreprise__c, LPCR_ContratEntreprise__c , recordtype.name, LPCR_PlanningEnfant__c  from SBQQ__Quote__c WHERE Id in :quoteIds]);
        
        for (Contract eachContract : contracts){
            if(quoteMap.containsKey(eachContract.SBQQ__Quote__c)){                
                eachContract =setContractFieldsFromQuoteHelper(eachContract,quoteMap.get(eachContract.SBQQ__Quote__c));
                Pad.log('SM010_ContractServices','setContractFields(List<Contract> contracts)','eachContract before insert'+eachContract);

            }
        }
    }
    
    
    /**
* @Author Ayoub Ouarti
* @Created 08/06/2020
* @Description methode setContractFields to set Contract fields from new Order's quote if the Order is getting changed before Update
* @Inputs Map<Id, Contract> oldContractMap,Map<Id, Contract> newContractMap
*/
    public static void setContractFields(Map<Id, Contract> oldContractMap,Map<Id, Contract> newContractMap){
        Pad.log('SM010_ContractServices','setContractFields(Map<Id, Contract> oldContractMap,Map<Id, Contract> newContractMap)','oldContractMap size '+oldContractMap.size(),'oldContractMap size '+newContractMap.size());

        Set<String> orderIds = new Set<String>();
        for(Contract eachContract : newContractMap.values()){
            if(eachContract.SBQQ__Order__c != oldContractMap.get(eachContract.Id).SBQQ__Order__c){
                orderIds.add(eachContract.SBQQ__Order__c);
            }
        }
        
        Map<Id,Order> mapOrders = new Map<Id,Order>([SELECT Id,SBQQ__Quote__c from Order WHERE Id in :orderIds ]);
        Set<String> quoteIds = UM003_TypeManager.getFieldsOfListObjects(mapOrders.values(),'SBQQ__Quote__c');
        Map<Id,SBQQ__Quote__c> quoteMap = new  Map<Id,SBQQ__Quote__c>([SELECT Id,LPCR_TypeFacturation__c,SBQQ__BillingFrequency__c,LPCR_IndexationConvenue__c,LPCR_MasterDevis__c,LPCR_RenouvellementConvenu__c,LPCR_DateDebut__c,LPCR_DateFin__c,LPCR_ChiffreAffaire__c, LPCR_MethodeRenouvellement__c,SBQQ__RenewalUpliftRate__c,LPCR_TypeEntreprise__c, LPCR_ContratEntreprise__c , recordtype.name, LPCR_PlanningEnfant__c  from SBQQ__Quote__c WHERE Id in :quoteIds]);
        
        //  Check if the Order is getting changed, If so , updating the fields 
        for(Contract eachContract : newContractMap.values()){
            eachContract=setContractFieldsFromQuoteHelper(eachContract,quoteMap.get(mapOrders.get(eachContract.SBQQ__Order__c).SBQQ__Quote__c));
        }
    }
    /**
* @Author Ayoub Ouarti
* @Created 08/06/2020
* @Description methode setContractFieldsFromQuoteHelper to help setting Contract fields from Quote
* @Inputs Contract contract , SBQQ__Quote__c quote
* Updated by Achraf Aboul adding new fields to set
*/
    public static Contract setContractFieldsFromQuoteHelper(Contract contract,SBQQ__Quote__c quote){
        Pad.log('SM010_ContractServices','setContractFieldsFromQuoteHelper(SBQQ__Quote__c quote)','quote : '+quote);

      
        contract.LPCR_IndexationConvenue__c = quote.LPCR_IndexationConvenue__c;
        
        contract.LPCR_TypeFacturation__c = quote.LPCR_TypeFacturation__c;
        
        contract.LPCR_BillingFrequency__c = quote.SBQQ__BillingFrequency__c;
        
        contract.LPCR_MasterDevis__c = quote.LPCR_MasterDevis__c;
        
        contract.LPCR_RenouvellementConvenu__c = quote.LPCR_RenouvellementConvenu__c;
        
        contract.LPCR_DateDebut__c = quote.LPCR_DateDebut__c;
        
        contract.LPCR_DateFin__c = quote.LPCR_DateFin__c;
        
        contract.LPCR_ChiffreAffaire__c = quote.LPCR_ChiffreAffaire__c;
        
        contract.LPCR_PlanningEnfant__c = quote.LPCR_PlanningEnfant__c;
        
        contract.LPCR_MethodeRenouvellement__c = quote.LPCR_MethodeRenouvellement__c;
        
        contract.LPCR_RenouvellementAutomatique__c = quote.SBQQ__RenewalUpliftRate__c == null ? false : true;
        
        if(quote.recordtype.name == Label.LPCR_ContratA) {
            contract.LPCR_ContratEntreprise__c = quote.LPCR_ContratEntreprise__c;
        }
        return contract;
    }
    
}