mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutJeudi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutJeudi__c</fullName>
    <label>Heure de début jeudi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutLundi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutLundi__c</fullName>
    <label>Heure de début lundi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutMardi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutMardi__c</fullName>
    <label>Heure de début mardi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutMercredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutMercredi__c</fullName>
    <label>Heure de début mercredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutVendredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutVendredi__c</fullName>
    <label>Heure de début vendredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinJeudi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinJeudi__c</fullName>
    <label>Heure de fin jeudi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinLundi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinLundi__c</fullName>
    <label>Heure de fin lundi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinMardi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinMardi__c</fullName>
    <label>Heure de fin mardi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinMercredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinMercredi__c</fullName>
    <label>Heure de fin mercredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinVendredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinVendredi__c</fullName>
    <label>Heure de fin vendredi</label>
    <type>Time</type>
</CustomField>

mdapiEYH/objects/LPCR_PlanningPrevisionnel__c.object
<CustomObject>
    <label>Planning Prévisionnel</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plannings Prévisionnels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Contrat__c</fullName>
        <label>Contrat</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Plannings Prévisionnels</relationshipLabel>
        <relationshipName>Plannings_Pr_visionnels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutJeudi__c</fullName>
        <label>Heure de début jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutLundi__c</fullName>
        <label>Heure de début lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMardi__c</fullName>
        <label>Heure de début mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMercredi__c</fullName>
        <label>Heure de début mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutVendredi__c</fullName>
        <label>Heure de début vendredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinJeudi__c</fullName>
        <label>Heure de fin jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinLundi__c</fullName>
        <label>Heure de fin lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMardi__c</fullName>
        <label>Heure de fin mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMercredi__c</fullName>
        <label>Heure de fin mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinVendredi__c</fullName>
        <label>Heure de fin vendredi</label>
        <type>Time</type>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Enfant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Devis (Contact Enfant)</relationshipLabel>
        <relationshipName>Devis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Creche</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Crèche)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_RessourcesMensuelles__c</fullName>
        <label>Ressources Mensuelles</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/classes/VFC001_GenererDocAnn2.cls
/**
* @ author Hanae Makboub
* @created 18/02/2020
* @description controller to display tables of plannings for each quote in a VFP001_GenererDocAnn2 VF page
*/

public with sharing class VFC001_GenererDocAnn2 {
    public Annex2Wrapper annex{get;set;}
    //SBQQ__Quote__c currentRecord;
    public VFC001_GenererDocAnn2() {
        //currentRecord = new SBQQ__Quote__c(id=Apexpages.currentPage().getParameters().get('recordId'));
        annex = new Annex2Wrapper(Apexpages.currentPage().getParameters().get('recordId'));
    }
    
    
    
    public class Annex2Wrapper{
        public List<planningPrevisionnelWrapper> planningPrevisionnels{get;set;}
        public SBQQ__Quote__c quote{get;set;}
        public Double LPCR_AverageTime{get;set;}
        public SBQQ__Quote__c getQuoteById(Id quoteId){
            return  [Select Id, 
                     SBQQ__StartDate__c,
                     SBQQ__EndDate__c, 
                     LPCR_ContactEnfant__r.Name,
                     LPCR_Creche__r.ShippingCity, 
                     LPCR_RessourcesMensuelles__c,
                     (Select Id, 
                      LPCR_Contrat__c,
                      LPCR_HeureDebutLundi__c, 
                      LPCR_HeureFinLundi__c , 
                      LPCR_HeureDebutMardi__c, 
                      LPCR_HeureFinMardi__c, 
                      LPCR_HeureDebutMercredi__c, 
                      LPCR_HeureFinMercredi__c ,
                      LPCR_HeureDebutJeudi__c, 
                      LPCR_HeureFinJeudi__c , 
                      LPCR_HeureDebutVendredi__c, 
                      LPCR_HeureFinVendredi__c 
                      FROM Plannings_Pr_visionnels__r )
                     From SBQQ__Quote__c 
                     WHERE Id=:quoteId];
            
        }
        public List<planningPrevisionnelWrapper> getPlannings(){
            //List<LPCR_PlanningPrevisionnel__c> plannings= EM010_PlanningPrEntity.getPlanningsByQuoteId(currentRecord.id);
            List<planningPrevisionnelWrapper> wrapperPlannings = new List<planningPrevisionnelWrapper>();
            for(LPCR_PlanningPrevisionnel__c pl : this.quote.Plannings_Pr_visionnels__r ){
                wrapperPlannings.add(new planningPrevisionnelWrapper(pl));
            }
            return wrapperPlannings;
        }
        public Annex2Wrapper(Id quoteId){
            this.quote=getQuoteById(quoteId);
            this.planningPrevisionnels = getPlannings();
            getTimeAverage();
        }
        public void getTimeAverage(){
            Double averag = 0;
            Integer sumavg = 0;
            List<Integer> plAverage = new List<Integer>();
            for(LPCR_PlanningPrevisionnel__c p: this.quote.Plannings_Pr_visionnels__r){
                try{
                     Integer avg = (((p.LPCR_HeureFinLundi__c.hour() - p.LPCR_HeureDebutLundi__c.hour())+ (p.LPCR_HeureFinLundi__c.minute()-p.LPCR_HeureDebutLundi__c.minute()))+
                          			((p.LPCR_HeureFinMardi__c.hour() - p.LPCR_HeureDebutMardi__c.hour())+ (p.LPCR_HeureFinMardi__c.minute()-p.LPCR_HeureDebutMardi__c.minute()))+
                                  	((p.LPCR_HeureFinMercredi__c.hour() - p.LPCR_HeureDebutMercredi__c.hour())+ (p.LPCR_HeureFinMercredi__c.minute()-p.LPCR_HeureDebutMercredi__c.minute()))+
                                    ((p.LPCR_HeureFinJeudi__c.hour() - p.LPCR_HeureDebutJeudi__c.hour())+ (p.LPCR_HeureFinJeudi__c.minute()-p.LPCR_HeureDebutJeudi__c.minute()))+
                                    ((p.LPCR_HeureFinVendredi__c.hour() - p.LPCR_HeureDebutVendredi__c.hour())+ (p.LPCR_HeureFinVendredi__c.minute()-p.LPCR_HeureDebutVendredi__c.minute()))); 
               plAverage.add(avg);
                }
                catch(Exception e){
                    system.debug('error'+e);
                }
              
            }
           
            system.debug('tttt'+plAverage);
            if(plAverage != null){
                for(Integer a:plAverage){
                    sumavg += a ;
                }
                system.debug('hanae'+sumavg);
                averag = sumavg/plAverage.size();
                system.debug('ha'+averag);
            }
           this.LPCR_AverageTime = averag;
        }
    }
    public class planningPrevisionnelWrapper{
        
        public String LPCR_HeureDebutLundi{get;set;}
        public String LPCR_HeureFinLundi{get;set;} 
        public String LPCR_HeureDebutMardi{get;set;}
        public String LPCR_HeureFinMardi{get;set;}
        public String LPCR_HeureDebutMercredi{get;set;}
        public String LPCR_HeureFinMercredi{get;set;}
        public String LPCR_HeureDebutJeudi{get;set;} 
        public String LPCR_HeureFinJeudi{get;set;}
        public String LPCR_HeureDebutVendredi{get;set;}
        public String LPCR_HeureFinVendredi{get;set;}
        public planningPrevisionnelWrapper(LPCR_PlanningPrevisionnel__c pl){
            LPCR_HeureDebutLundi = convertTimeToString(pl.LPCR_HeureDebutLundi__c);
            LPCR_HeureFinLundi = convertTimeToString(pl.LPCR_HeureFinLundi__c);
            LPCR_HeureDebutMardi = convertTimeToString(pl.LPCR_HeureDebutMardi__c);
            LPCR_HeureFinMardi = convertTimeToString(pl.LPCR_HeureFinMardi__c);
            LPCR_HeureDebutMercredi = convertTimeToString(pl.LPCR_HeureDebutMercredi__c);
            LPCR_HeureFinMercredi = convertTimeToString(pl.LPCR_HeureFinMercredi__c);
            LPCR_HeureDebutJeudi = convertTimeToString(pl.LPCR_HeureDebutJeudi__c);
            LPCR_HeureFinJeudi = convertTimeToString(pl.LPCR_HeureFinJeudi__c);
            LPCR_HeureDebutVendredi = convertTimeToString(pl.LPCR_HeureDebutVendredi__c);
            LPCR_HeureFinVendredi = convertTimeToString(pl.LPCR_HeureFinVendredi__c);
        }
        public String convertTimeToString(Time tm){
            String tt = '';
            if(tm != null){
                tt = tm.hour()+':'+tm.minute();
            }
            return tt;
        }
        
    }
    
    
}