mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Debut</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateRenouvellement__c</fullName>
        <formula>EndDate +  LPCR_JoursAvance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date de Renouvellement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_RenouvellementAutomatique__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renouvellement Automatique</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalForecast__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</description>
        <inlineHelpText>Sélectionnez cette case pour déclencher la génération d&apos;une opportunité de renouvellement à des fins de prévision. Ne génère pas automatiquement un devis de renouvellement.</inlineHelpText>
        <label>Renewal Forecast</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalQuoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this option to automatically generate a renewal quote on renewal opportunities.</description>
        <inlineHelpText>Sélectionnez cette option pour générer automatiquement un devis de renouvellement dans les opportunités de renouvellement.</inlineHelpText>
        <label>Renewal Quoted</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_ContactEnfant__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ContactEnfant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Enfant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact Enfant)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_TypeCreche__c.field-meta.xml
<CustomField>
    <fullName>LPCR_TypeCreche__c</fullName>
    <label>Type de crèche</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LPCR_TypeCreche</valueSetName>
    </valueSet>
</CustomField>

mdapiEYH/objects/LPCR_BaremeCAF__c.object
<CustomObject>
    <label>Barème CAF</label>
    <nameField>
        <displayFormat>BCAF-{00000}</displayFormat>
        <label>Barème CAF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Barèmes CAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
</CustomObject>

mdapiEYH/objects/LPCR_Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Nom de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiEYH/objects/LPCR_RessourceFamille__c.object
<CustomObject>
    <label>Ressource Famille</label>
    <nameField>
        <label>Ressource Famille Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ressources Familles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Active__c</fullName>
        <formula>If (Isblank ( LPCR_DateFin__c ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LPCR_BaremeCaf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Barème CAF</label>
        <referenceTo>LPCR_BaremeCAF__c</referenceTo>
        <relationshipLabel>Ressources Familles</relationshipLabel>
        <relationshipName>Ressources_Familles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_CompteFamille__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte Famille</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ressources Familles</relationshipLabel>
        <relationshipName>Ressources_Familles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Enfant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ressources Familles</relationshipLabel>
        <relationshipName>Ressources_Familles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_TauxEffort__c</fullName>
        <label>Taux d&apos;effort</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <formula>Text ( LPCR_creche__r.LPCR_TypeCreche__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type Crèche</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Mac</fullName>
        <active>true</active>
        <label>Mac</label>
    </recordTypes>
</CustomObject>

force-app/main/default/globalValueSets/LPCR_TypeCreche.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALSH</fullName>
    </customValue>
    <customValue>
        <fullName>MAF</fullName>
    </customValue>
    <customValue>
        <fullName>MAC</fullName>
    </customValue>
    <customValue>
        <fullName>MICRO</fullName>
    </customValue>
    <customValue>
        <fullName>Halte-Garderie</fullName>
    </customValue>
    <customValue>
        <fullName>Jardin d’enfants</fullName>
    </customValue>
    <customValue>
        <fullName>RAM</fullName>
    </customValue>
    <customValue>
        <fullName>Partenaire</fullName>
    </customValue>
    <customValue>
        <fullName>PAJE</fullName>
    </customValue>
    <masterLabel>Type de crèche</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/APB019_AutomateRessourceFamille.cls
/**
* @author Hanae Makboub
* @date 04/10/2020
* @Description Batch for Automation of "ressource famille" before B2C MAC renewals
*/
global class APB019_AutomateRessourceFamille implements Database.Batchable<sObject>,Schedulable {
    String query;
    public static Id accueilRecTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName('Contract',Label.LPCR_ContratA);
    global APB019_AutomateRessourceFamille() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Date today = date.today();
        
        query = 'SELECT Id, AccountId, LPCR_ContactEnfant__c FROM Contract WHERE RecordTypeId =: accueilRecTypeId AND LPCR_TypeCreche__c = \'MAC\' AND  Status =\'Activated\' AND LPCR_RenouvellementAutomatique__c = true AND  LPCR_DateRenouvellement__c <= :today AND LPCR_DateRenouvellement__c != null AND (SBQQ__RenewalQuoted__c = false OR SBQQ__RenewalForecast__c = false) ';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contract> scope) {
        
        PAd.log('APB019_AutomateRessourceFamille', 'execute', 'scope to execute : '+scope);
        
        string errorMsg;
        
        set<String> accFamilleIds = UM003_TypeManager.getFieldsOfListObjects(scope,'AccountId');
        
        set<String> contractEnfantIds = UM003_TypeManager.getFieldsOfListObjects(scope,'LPCR_ContactEnfant__c');
        
        List<LPCR_RessourceFamille__c> ressourceFamilleList = [SELECT Id, LPCR_CompteFamille__c, LPCR_ContactEnfant__c, LPCR_DateFin__c, LPCR_DateDebut__c,LPCR_BaremeCaf__c , LPCR_TauxEffort__c 
                                                               FROM LPCR_RessourceFamille__c 
                                                               WHERE LPCR_CompteFamille__c IN : accFamilleIds 
                                                               AND LPCR_ContactEnfant__c IN : contractEnfantIds 
                                                               AND LPCR_Active__c = true];
        
        List<LPCR_Log__c> listOfLog = new List<LPCR_Log__c>();
        
        List<LPCR_RessourceFamille__c> newactiveList = new List<LPCR_RessourceFamille__c>();
        
        for(LPCR_RessourceFamille__c eachResFamille : ressourceFamilleList){
            
            LPCR_RessourceFamille__c tempRessFamille = new LPCR_RessourceFamille__c();
            
            eachResFamille.LPCR_DateFin__c = date.newInstance(eachResFamille.LPCR_DateDebut__c.year(), 12, 31);
            
            tempRessFamille.LPCR_CompteFamille__c = eachResFamille.LPCR_CompteFamille__c;
            
            tempRessFamille.LPCR_ContactEnfant__c = eachResFamille.LPCR_ContactEnfant__c;
            
            tempRessFamille.LPCR_DateDebut__c  = date.newInstance(eachResFamille.LPCR_DateDebut__c.year()+1, 01, 01);
            
            tempRessFamille.LPCR_DateFin__c = null;
            
            tempRessFamille.LPCR_BaremeCaf__c = null;
            
            tempRessFamille.LPCR_TauxEffort__c = null;
            
            newactiveList.add(tempRessFamille);
            
            listOfLog.add(UM001_LogManager.getWriteLogActivityForBulkInsert('Automating Ressource Famille', 'APB019_AutomateRessourceFamille', 'Batch', String.valueOf(eachResFamille.Id), '', 'SUCCESS'));  
            
        }
        
        try{
            update ressourceFamilleList;
            
            insert newactiveList;
            
        }catch(Exception ex){
            
            PAD.log('APB019_AutomateRessourceFamille','execute','Exception : '+ex.getMessage());
            errorMsg = String.valueOf(ex);
        }
        finally {
            
            if (String.isNotBlank(errorMsg)) {
                UM001_LogManager.writeLogActivityWithoutFuture('Automating Ressource Famille', 'APB019_AutomateRessourceFamille', 'Batch', '',  'Error:' + errorMsg, UM010_Constant.ERROR);  
            }
            else {
                insert listOfLog;
            }
            
        }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
    global void execute(SchedulableContext sc) {
        Datetime dt = Datetime.now().addMinutes(30);  // i.e. 30 mins
        String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
        
        APB019_AutomateRessourceFamille sc1 = new APB019_AutomateRessourceFamille();
        
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB019_AutomateRessourceFamille');
        
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB019_AutomateRessourceFamille();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 30 mins
                Id schedId = System.Schedule('APB019_AutomateRessourceFamille'+timeForScheduler,timeForScheduler,new APB019_AutomateRessourceFamille());
            }
        }  
        
    } 
}