mdapiEYH/objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutJeudi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutJeudi__c</fullName>
    <label>Heure de début jeudi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutLundi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutLundi__c</fullName>
    <label>Heure de début lundi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutMardi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutMardi__c</fullName>
    <label>Heure de début mardi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutMercredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutMercredi__c</fullName>
    <label>Heure de début mercredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureDebutVendredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureDebutVendredi__c</fullName>
    <label>Heure de début vendredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinJeudi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinJeudi__c</fullName>
    <label>Heure de fin jeudi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinLundi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinLundi__c</fullName>
    <label>Heure de fin lundi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinMardi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinMardi__c</fullName>
    <label>Heure de fin mardi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinMercredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinMercredi__c</fullName>
    <label>Heure de fin mercredi</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LPCR_HeureFinVendredi__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HeureFinVendredi__c</fullName>
    <label>Heure de fin vendredi</label>
    <type>Time</type>
</CustomField>

mdapiEYH/objects/LPCR_PlanningPrevisionnel__c.object
<CustomObject>
    <label>Planning Prévisionnel</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plannings Prévisionnels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Contrat__c</fullName>
        <label>Contrat</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Plannings Prévisionnels</relationshipLabel>
        <relationshipName>Plannings_Pr_visionnels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutJeudi__c</fullName>
        <label>Heure de début jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutLundi__c</fullName>
        <label>Heure de début lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMardi__c</fullName>
        <label>Heure de début mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMercredi__c</fullName>
        <label>Heure de début mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutVendredi__c</fullName>
        <label>Heure de début vendredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinJeudi__c</fullName>
        <label>Heure de fin jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinLundi__c</fullName>
        <label>Heure de fin lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMardi__c</fullName>
        <label>Heure de fin mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMercredi__c</fullName>
        <label>Heure de fin mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinVendredi__c</fullName>
        <label>Heure de fin vendredi</label>
        <type>Time</type>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_ContactEnfant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Enfant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Devis (Contact Enfant)</relationshipLabel>
        <relationshipName>Devis</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Creche</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Crèche)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_RessourcesMensuelles__c</fullName>
        <label>Ressources Mensuelles</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LPCR_TypePlanning__c</fullName>
        <label>Type de planning</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Classique</fullName>
                </value>
                <value>
                    <fullName>Tournant</fullName>
                </value>
                <value>
                    <fullName>Multi-planning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/classes/EM006_QuoteEntity.cls
/**
* @author Ayoub Ouarti
* @date 26/02/2020
* @Description Queries about SBQQ__Quote__c
*/
public with sharing class EM006_QuoteEntity extends EM001_AbstractObjectEntity{

    public EM006_QuoteEntity(){
        super('SBQQ__Quote__c');
    }
    public static List<SBQQ__Quote__c> saveOrUpdte(List<SBQQ__Quote__c> quotes){
        if(UM003_TypeManager.isNotNullAndNotEmpty(quotes) ){
            upsert quotes;
        }
     return  quotes; 
    }

    public static SBQQ__Quote__c saveOrUpdte(SBQQ__Quote__c quote){
        if(UM003_TypeManager.isNotNull(quote)){
            upsert quote;
        }
     return  quote; 
    }
	public static SBQQ__Quote__c getQuoteById(Id quoteId){
            return  [Select Id, 
                     SBQQ__StartDate__c,
                     SBQQ__EndDate__c, 
                     LPCR_ContactEnfant__r.FirstName,
                     LPCR_ContactEnfant__r.LastName,
                     LPCR_Creche__r.ShippingCity, 
                     LPCR_TypePlanning__c,
                     LPCR_RessourcesMensuelles__c,
                     (Select Id, 
                      LPCR_Contrat__c,
                      LPCR_HeureDebutLundi__c, 
                      LPCR_HeureFinLundi__c , 
                      LPCR_HeureDebutMardi__c, 
                      LPCR_HeureFinMardi__c, 
                      LPCR_HeureDebutMercredi__c, 
                      LPCR_HeureFinMercredi__c ,
                      LPCR_HeureDebutJeudi__c, 
                      LPCR_HeureFinJeudi__c , 
                      LPCR_HeureDebutVendredi__c, 
                      LPCR_HeureFinVendredi__c 
                      FROM Plannings_Pr_visionnels__r )
                     From SBQQ__Quote__c 
                     WHERE Id=:quoteId];
            
        }
}