mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Devis à partir duquel ce contrat a été créé.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Le taux du prix de renouvellement augmente.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_DateRevisionPrix__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateRevisionPrix__c</fullName>
    <inlineHelpText>Si Révision de prix (%) non renseigné, la facturation de la commande sera suspendue à cette date.</inlineHelpText>
    <label>Date de révision de prix</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/LPCR_UpliftNow__c.field-meta.xml
<CustomField>
    <fullName>LPCR_UpliftNow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uplift Now</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_IndexationConvenue__c</fullName>
        <label>Indexation Convenue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oui</fullName>
                </value>
                <value>
                    <fullName>Non</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeAvenant__c</fullName>
        <label>Type d&apos;avenant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Changement de Prix</fullName>
                </value>
                <value>
                    <fullName>Résiliation</fullName>
                </value>
                <value>
                    <fullName>Ajout/Suppression Berceau</fullName>
                </value>
                <value>
                    <fullName>Modification des termes du contrat</fullName>
                </value>
                <value>
                    <fullName>Modification du type/fréquence de facturation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__RenewalUpliftRate__c</fullName>
        <description>Rate of renewal price increases.</description>
        <inlineHelpText>Rate of renewal price increases.</inlineHelpText>
        <label>Renewal Uplift (%)</label>
        <precision>11</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_DateRevisionPrix__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateRevisionPrix__c</fullName>
    <label>Date de révision de prix</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_UpliftNow__c.field-meta.xml
<CustomField>
    <fullName>LPCR_UpliftNow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uplift Now</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/APC013_UpliftNow.cls
/**
 * @description       : Controller class for LWC015_UpliftNow
 * @author            : Rakshak Rajjoo
 * @last modified on  : 14/10/2021
 * @last modified by  : Rakshak Rajjoo
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   12/10/2021   Rakshak Rajjoo   Initial Version
 **/
public with sharing class APC013_UpliftNow {
    @AuraEnabled
    public static void doUplift(String contractId) {
        try {
            Contract con = [SELECT Id, LPCR_IndexationConvenue__c, SBQQ__RenewalUpliftRate__c, LPCR_DateRevisionPrix__c FROM Contract WHERE Id = :contractId];

            List<SBQQ__Quote__c> lstQuoteUpdate = new List<SBQQ__Quote__c>();

            // if (con.SBQQ__RenewalUpliftRate__c != null || con.LPCR_DateRevisionPrix__c == null){
            //     throw new CustomException('Ce devis n\'est éligible pour l\'uplift');
            // }
            // ' WHERE LPCR_IndexationConvenue__c = \'Non\' ';
            // ' AND SBQQ__RenewalUpliftRate__c = NULL ';
            // ' AND LPCR_DateRevisionPrix__c != NULL ';
            // ' AND LPCR_UpliftNow__c = False ';

            UM006_ContractAmender amender = new UM006_ContractAmender();

            WRP001_QuoteModel quote = amender.load(con.Id);
            UM007_QuoteReader reader = new UM007_QuoteReader();
            WRP001_QuoteModel quoteModel = reader.read(quote.record.id);
            APC006_CloneQuoteLinesIndexation.cloneAndResetQL(quoteModel.record.id, con.SBQQ__RenewalUpliftRate__c, con.LPCR_DateRevisionPrix__c);
            lstQuoteUpdate.add(
                new SBQQ__Quote__c(
                    Id = quoteModel.record.id,
                    SBQQ__RenewalUpliftRate__c = con.SBQQ__RenewalUpliftRate__c,
                    LPCR_DateRevisionPrix__c = con.LPCR_DateRevisionPrix__c.addYears(1),
                    LPCR_TypeAvenant__c = 'Amendement d\'indexation'
                )
            );

            if (lstQuoteUpdate.size() > 0) {
                update lstQuoteUpdate;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }

    public class CustomException extends Exception {
    }
}