mdapiEYH/objects/Contract.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract/fields/LPCR_NombreDeBerceaux__c.field-meta.xml
<CustomField>
    <fullName>LPCR_NombreDeBerceaux__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Nombre de berceaux</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

mdapiEYH/objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductName__c</fullName>
        <description>Pulls in the Product Name</description>
        <formula>SBQQ__Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulls in the Product Name</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SM027_SubscriptionService.cls
/**
* @author  PDO
* @created 19/03/2021
* @description Trigger on SBQQ__Subscription__c Object
*/
public class SM027_SubscriptionService {
    //Nombre de berceau sur contrat B2B pour calcul l'ARPU journalier
    public static void updateContratNombreBerceau(Map<Id, SBQQ__Subscription__c> newSubscriptionMap){
        Map<Id,Integer> mapContratIDNombreBerceau=new Map<Id,Integer>();
        List<Contract> lstContractUpdate=new List<Contract>();
        for(Id key : newSubscriptionMap.keyset()){
            if(newSubscriptionMap.get(key).SBQQ__ProductName__c.startsWith(Label.LPCR_ProduitBerceauNom)){
                if(!mapContratIDNombreBerceau.containsKey(newSubscriptionMap.get(key).SBQQ__Contract__c)){
                mapContratIDNombreBerceau.put(newSubscriptionMap.get(key).SBQQ__Contract__c,1);
                }else{
                    mapContratIDNombreBerceau.put(newSubscriptionMap.get(key).SBQQ__Contract__c,mapContratIDNombreBerceau.get(newSubscriptionMap.get(key).SBQQ__Contract__c)+1);
                }
            }
            
        }
        for(Id key : mapContratIDNombreBerceau.keyset()){
            lstContractUpdate.add(new Contract(Id=key,LPCR_NombreDeBerceaux__c=mapContratIDNombreBerceau.get(key)));
        }
        if(lstContractUpdate.size() > 0 )update lstContractUpdate;
        
        
    }

}