mdapiEYH/objects/LPCR_Preinscription__c.object
<CustomObject>
    <description>Objet servant à stocker les réponses aux formulaires de préinscription remplis par les familles par l&apos;intermédiare de FormAssembly</description>
    <label>Préinscription</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Numéro de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Préinscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Statut__c</fullName>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nouveau</fullName>
                    <default>true</default>
                    <label>Nouveau</label>
                </value>
                <value>
                    <fullName>Liste d’attente</fullName>
                </value>
                <value>
                    <fullName>Option</fullName>
                </value>
                <value>
                    <fullName>Recommandation</fullName>
                </value>
                <value>
                    <fullName>Recommandation validée</fullName>
                </value>
                <value>
                    <fullName>Proposition</fullName>
                </value>
                <value>
                    <fullName>Confirmé</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/LPCR_StatutInscription.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Nouveau</fullName>
        <default>true</default>
        <label>Nouveau</label>
    </customValue>
    <customValue>
        <fullName>Liste attente</fullName>
        <label>Liste d’attente</label>
    </customValue>
    <customValue>
        <fullName>Option</fullName>
    </customValue>
    <customValue>
        <fullName>Recommandation</fullName>
    </customValue>
    <customValue>
        <fullName>Recommandation validée</fullName>
    </customValue>
    <customValue>
        <fullName>Attribuée</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmé</fullName>
    </customValue>
    <customValue>
        <fullName>Inscrit</fullName>
    </customValue>
    <customValue>
        <fullName>Annulé</fullName>
    </customValue>
    <masterLabel>Statut Inscription</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LWC003_LWC_UpdateStatusController.cls
public with sharing class LWC003_LWC_UpdateStatusController {


    /*public class CustomSelectOptions{
            @AuraEnabled public String label {get;set;}
            @AuraEnabled public String value {get;set;}
            public CustomSelectOptions() {
                this.label = '';
                this.value = '';
            }
            public CustomSelectOptions(String lab, String val) {
                this.label = lab;
                this.value = val;
            }
        }
        



            @AuraEnabled
        public static List<CustomSelectOptions> getPicklistValues(String sObj, String field) {
    
            List<CustomSelectOptions> options = new List<CustomSelectOptions>();
            Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get(sObj).getDescribe().fields.getMap();
            Schema.SObjectField sObjfield = fieldMap.get(field);
            Schema.DescribeFieldResult fieldDesc = sObjfield.getDescribe();
            List<Schema.PicklistEntry> ple = fieldDesc.getPicklistValues();
                for( Schema.PicklistEntry f : ple) {
                options.add(new CustomSelectOptions(f.getLabel(), f.getValue()));
               }       
               return options;
        }*/

       @AuraEnabled 
        public static List<String> getPicklistvalues(){
        
        List<String> lstPicklistValue = new List<String>();
        Schema.DescribeFieldResult describeFieldRslt = LPCR_Preinscription__c.LPCR_Statut__c.getDescribe();
        List<Schema.PicklistEntry> pickListEntries = describeFieldRslt.getPicklistValues();
        
        for(Schema.PicklistEntry eachEntry : pickListEntries ) {
            lstPicklistValue.add(eachEntry.getValue());
        }
       
        return lstPicklistValue;
        
    }


}