mdapiEYH/objects/LPCR_Structure_AO__c.object
<CustomObject>
    <label>Structure AO</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Structures AO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Structures AO</relationshipLabel>
        <relationshipName>Structures_AO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunité</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Structures AO</relationshipLabel>
        <relationshipName>Structures_AO</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/EM009_StructureAOEntity.cls
/**
* @author Achraf ABOUL
* @date 20/03/2020
* @Description Entity class for LPCR_Structure_AO__c
*/
public with sharing class EM009_StructureAOEntity extends DM000_SObject {
    
    @TestVisible
    protected override String getDataManagerClassName() {
        return EM002_LeadEntity.class.getName();
    }

   
    @TestVisible
    protected override String getObjectName() {
        return Schema.sObjectType.Lead.name;
    }
    
    public static List<LPCR_Structure_AO__c> getStructuresAOByLeads(Set<Id> leadsIds){
        return [SELECT Id,LPCR_Lead__c, Opportunite__c FROM LPCR_Structure_AO__c WHERE LPCR_Lead__c IN :leadsIds];
    }
}