mdapiEYH/objects/LPCR_Log__c.object
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Nom de Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_ActionName__c</fullName>
        <label>Action Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_Message__c</fullName>
        <label>Message</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LPCR_Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Purgé</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TargetObject__c</fullName>
        <label>Target Object</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_Type__c</fullName>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/UM001_LogManager.cls
/*
@Author : Erwan Yhuellou
@Date : 13/01/2020
@Descr : Method used to log critical information. Can be used by critical apex business rules, callin, callout, etc.
*/
public with sharing class UM001_LogManager {
    
    // Method used to trace activty 
    
    @future
    public static void writeLogActivity(String title, String callIdentifier, String typeOfInfo, String parentObjectId, String content, String result) {
         
        LPCR_Log__c tmpLog = new LPCR_Log__c();
        tmpLog.Name = title;
        tmpLog.LPCR_ActionName__c = callIdentifier;
        tmpLog.LPCR_Message__c = content!= null ? content.Left(130000): '';
        tmpLog.LPCR_TargetObject__c = parentObjectId;
        tmpLog.LPCR_Type__c = typeOfInfo;
        tmpLog.LPCR_Result__c = result;
        insert tmpLog;
    }
    public static void writeLogActivityWithoutFuture(String title, String callIdentifier, String typeOfInfo, String parentObjectId, String content, String result) {
         
        LPCR_Log__c tmpLog = new LPCR_Log__c();
        tmpLog.Name = title;
        tmpLog.LPCR_ActionName__c = callIdentifier;
        tmpLog.LPCR_Message__c = content!= null ? content.Left(130000): '';
        tmpLog.LPCR_TargetObject__c = parentObjectId;
        tmpLog.LPCR_Type__c = typeOfInfo;
        tmpLog.LPCR_Result__c = result;
        insert tmpLog;
    }
    // added by Saurabh
    public static void writeLogActivityNow(String title, String callIdentifier, String typeOfInfo, Id parentObjectId, String content, String result) {
         
        LPCR_Log__c tmpLog = new LPCR_Log__c();
        tmpLog.Name = title;
        tmpLog.LPCR_ActionName__c = callIdentifier;
        tmpLog.LPCR_Message__c = content!= null ? content.Left(130000): '';
        tmpLog.LPCR_TargetObject__c = parentObjectId;
        tmpLog.LPCR_Type__c = typeOfInfo;
        tmpLog.LPCR_Result__c = result;
        insert tmpLog;
    }
    
}