mdapiEYH/objects/LPCR_Preinscription__c.object
<CustomObject>
    <description>Objet servant à stocker les réponses aux formulaires de préinscription remplis par les familles par l&apos;intermédiare de FormAssembly</description>
    <label>Préinscription</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Numéro de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Préinscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_ContactParent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Parent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Préinscriptions (Contact Parent)</relationshipLabel>
        <relationshipName>PreinscriptionsParent</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/APC004_SendMailController.cls
/**
* @author Achraf ABOUL
* @date 06/03/2020
* @Description SendMail component controller
*/
public class APC004_SendMailController {
    
    @AuraEnabled(Cacheable=true)
    public static List<EmailTemplate> getAllMailTemplates(){
        return EM008_EmailTemplateEntity.getAllEmailTemplates();
    }
    @AuraEnabled
    public static void sendMail(String subject, String body, List<Id> preInscriptionIds){
        List<string> toAddress = new List<string>();
        for(LPCR_Preinscription__c eachPreInsc : [SELECT Id,LPCR_ContactParent__r.Email FROM LPCR_Preinscription__c WHERE Id IN :preInscriptionIds]){
            toAddress.add(eachPreInsc.LPCR_ContactParent__r.Email);
        }
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddress);
        mail.setSubject(subject);
        mail.setHTMLBody(body);
        mail.setSaveAsActivity(false);
        mail.setUseSignature(false);
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        allmsg.add(mail);
        Messaging.sendEmail(allmsg,false);
    }
    
}