mdapiEYH/objects/LPCR_PlanningPrevisionnel__c.object
<CustomObject>
    <label>Planning Prévisionnel</label>
    <nameField>
        <displayFormat>PP-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plannings Prévisionnels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Contrat__c</fullName>
        <label>Contrat</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Plannings Prévisionnels</relationshipLabel>
        <relationshipName>Plannings_Pr_visionnels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutJeudi__c</fullName>
        <label>Heure de début jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutLundi__c</fullName>
        <label>Heure de début lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMardi__c</fullName>
        <label>Heure de début mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutMercredi__c</fullName>
        <label>Heure de début mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDebutVendredi__c</fullName>
        <label>Heure de début vendredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinJeudi__c</fullName>
        <label>Heure de fin jeudi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinLundi__c</fullName>
        <label>Heure de fin lundi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMardi__c</fullName>
        <label>Heure de fin mardi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinMercredi__c</fullName>
        <label>Heure de fin mercredi</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureFinVendredi__c</fullName>
        <label>Heure de fin vendredi</label>
        <type>Time</type>
    </fields>
</CustomObject>

force-app/main/default/classes/EM010_PlanningPrEntity.cls
/**
* @ author Hanae Makboub
* @created 19/02/2020
* @description Entity Class for Object LPCR_PlanningPrevisionnel__c
*/
public with sharing class EM010_PlanningPrEntity {
    public static List<LPCR_PlanningPrevisionnel__c> getPlanningsByQuoteId(Id idQuote) {
     /*
        return [SELECT Id,
               		   LPCR_Contrat__c,
                	   LPCR_HeureDebutLundi__c, 
                	   LPCR_HeureFinLundi__c , 
                	   LPCR_HeureDebutMardi__c, 
                       LPCR_HeureFinMardi__c, 
                       LPCR_HeureDebutMercredi__c, 
                       LPCR_HeureFinMercredi__c ,
                       LPCR_HeureDebutJeudi__c, 
                       LPCR_HeureFinJeudi__c , 
                       LPCR_HeureDebutVendredi__c, 
                	   LPCR_HeureFinVendredi__c 
                FROM LPCR_PlanningPrevisionnel__c
                Where LPCR_Contrat__c =: idQuote ];

      */
        return null;
    }
}