mdapiEYH/objects/LPCR_ParametrageScore__c.object
<CustomObject>
    <label>Paramétrage Score</label>
    <nameField>
        <label>Nom de Paramétrage Score</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paramétrages Score</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Paramétrages Score</relationshipLabel>
        <relationshipName>Param_trages_Score</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Score__c</fullName>
        <label>Score</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/LPCR_ParametrageScore__c/fields/LPCR_ApiFieldName__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ApiFieldName__c</fullName>
    <description>De l&apos;objet préinscription</description>
    <label>Nom du champ paramétré</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LPCR_Anciennete__c</fullName>
                <label>Ancienneté (jours)</label>
            </value>
            <value>
                <fullName>LPCR_Commentaire__c</fullName>
                <label>Commentaire</label>
            </value>
            <value>
                <fullName>LPCR_CompteEntreprise__c</fullName>
                <label>Compte Entreprise</label>
            </value>
            <value>
                <fullName>LPCR_CompteFamille__c</fullName>
                <label>Compte Famille</label>
            </value>
            <value>
                <fullName>LPCR_ContactEnfant__c</fullName>
                <label>Contact Enfant</label>
            </value>
            <value>
                <fullName>LPCR_ContactParent__c</fullName>
                <label>Contact Parent</label>
            </value>
            <value>
                <fullName>LPCR_ContactParent2__c</fullName>
                <label>Contact Parent2</label>
            </value>
            <value>
                <fullName>LPCR_Contrat__c</fullName>
                <label>Contrat</label>
            </value>
            <value>
                <fullName>LPCR_DateEntreeEntreprise__c</fullName>
                <label>Date d&apos;entrée dans l&apos;entreprise</label>
            </value>
            <value>
                <fullName>Tech_DateEntreeCreche__c</fullName>
                <label>Date d&apos;entrée en crèche (Mois)</label>
            </value>
            <value>
                <fullName>LPCR_DateSortie__c</fullName>
                <label>Date de sortie</label>
            </value>
            <value>
                <fullName>LPCR_DemandeInscriptionCrecheMunicipal__c</fullName>
                <label>Demande inscription en crèche municipal?</label>
            </value>
            <value>
                <fullName>LPCR_DossierComplet__c</fullName>
                <label>Dossier complet</label>
            </value>
            <value>
                <fullName>LPCR_DetailHandicapEnfant__c</fullName>
                <label>Détail Handicap Enfant</label>
            </value>
            <value>
                <fullName>LPCR_EnfantDateDeNaissance__c</fullName>
                <label>Enfant - Date De Naissance</label>
            </value>
            <value>
                <fullName>LPCR_EnfantNom__c</fullName>
                <label>Enfant - Nom</label>
            </value>
            <value>
                <fullName>LPCR_EnfantPrenom__c</fullName>
                <label>Enfant - Prénom</label>
            </value>
            <value>
                <fullName>LPCR_ExistenceCrecheMunicipale__c</fullName>
                <label>Existence crèche municipale</label>
            </value>
            <value>
                <fullName>LPCR_HandicapEnfantDansLaFraterie__c</fullName>
                <label>Handicap enfant dans la fraterie</label>
            </value>
            <value>
                <fullName>LPCR_Jumeaux__c</fullName>
                <label>Jumeaux</label>
            </value>
            <value>
                <fullName>LPCR_ModeDAccueilDeLEnfant__c</fullName>
                <label>Mode d&apos;accueil de l&apos;enfant</label>
            </value>
            <value>
                <fullName>LPCR_NombreJours__c</fullName>
                <label>Nombre de jours (calculé)</label>
            </value>
            <value>
                <fullName>LPCR_PossedeUnModeDAccueilPourLEnfant__c</fullName>
                <label>Possède un mode d&apos;accueil pour l&apos;enfant</label>
            </value>
            <value>
                <fullName>LPCR_PrecisionMutation__c</fullName>
                <label>Précision mutation</label>
            </value>
            <value>
                <fullName>LPCR_Rep1AutreSituationPro__c</fullName>
                <label>Rep1 - Autre situation pro</label>
            </value>
            <value>
                <fullName>LPCR_Rep1Civilite__c</fullName>
                <label>Rep1 - Civilité</label>
            </value>
            <value>
                <fullName>LPCR_Rep1CodePostal__c</fullName>
                <label>Rep1 - Code Postal</label>
            </value>
            <value>
                <fullName>LPCR_Rep1DetailHandicap__c</fullName>
                <label>Rep1 - Détail Handicap</label>
            </value>
            <value>
                <fullName>LPCR_Rep1Email__c</fullName>
                <label>Rep1 - Email</label>
            </value>
            <value>
                <fullName>LPCR_Rep1Handicap__c</fullName>
                <label>Rep1 - Handicap</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LPCR_ParametrageScore__c/fields/LPCR_Format__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Liste</fullName>
            </value>
            <value>
                <fullName>Numéro</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Nombre</fullName>
            </value>
            <value>
                <fullName>Texte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LPCR_ParametrageScore__c/fields/LPCR_Valeur__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Valeur__c</fullName>
    <label>Valeur</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

mdapiEYH/objects/LPCR_Preinscription__c.object
<CustomObject>
    <description>Objet servant à stocker les réponses aux formulaires de préinscription remplis par les familles par l&apos;intermédiare de FormAssembly</description>
    <label>Préinscription</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Numéro de la demande</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Préinscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_CompteEntreprise__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte Entreprise</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Préinscriptions</relationshipLabel>
        <relationshipName>PreinscriptionsEntreprise</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Score__c</fullName>
        <description>score obtenu suivant les critères définis pour l&apos;entreprise</description>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SM009_ParametrageScoreServices.cls
/**
* @author Ayoub Ouarti
* @date 05/03/2020
* @description Service class for SM009_ParametrageScoreServices
*/
public with sharing class SM009_ParametrageScoreServices {
    
    public static void setScoreOnpreinscriptions(List<LPCR_Preinscription__c> preinscriptions){
        List<String> lstFields = new List<String>();
        
        Set<String> accountIds = UM003_TypeManager.getFieldsOfListObjects(preinscriptions,'LPCR_CompteEntreprise__c');
        Map<id, List<LPCR_ParametrageScore__c>> paramScoreMap = new Map <id, List<LPCR_ParametrageScore__c>>();
        
        for(LPCR_ParametrageScore__c paramScore : [SELECT Id, LPCR_ApiFieldName__c, LPCR_Format__c, LPCR_Valeur__c, LPCR_Score__c, LPCR_Account__c FROM LPCR_ParametrageScore__c where LPCR_Account__c in: accountIds]){
            if(!paramScoreMap.containsKey(paramScore.LPCR_Account__c)){
                List<LPCR_ParametrageScore__c> paramScoreList = new List<LPCR_ParametrageScore__c>();
                paramScoreList.add(paramScore);
                paramScoreMap.put(paramScore.LPCR_Account__c,paramScoreList);
            }
            else{
                List<LPCR_ParametrageScore__c> paramScoreList = paramScoreMap.get(paramScore.LPCR_Account__c);
                paramScoreList.add(paramScore);
                paramScoreMap.put(paramScore.LPCR_Account__c,paramScoreList);
            }
        }
        
        for(LPCR_Preinscription__c eachPreinscription : preinscriptions){
            if(paramScoreMap.containsKey(eachPreinscription.LPCR_CompteEntreprise__c)){
                eachPreinscription.LPCR_Score__c= scoreCalculation(eachPreinscription , paramScoreMap.get(eachPreinscription.LPCR_CompteEntreprise__c));
                
            }
        }        
    }
    
    public static Decimal scoreCalculation(LPCR_Preinscription__c preinscription,List<LPCR_ParametrageScore__c> parametrageScoreList){
        
        map<string, Decimal> mapScore = new Map<string,Decimal>();
        map<string, Decimal> mapValeurNum = new Map<string, Decimal>();
        map<string, Date> mapValeurDate = new Map<string, Date>();

        for(LPCR_ParametrageScore__c eachParam : parametrageScoreList){
            string field = eachParam.LPCR_ApiFieldName__c;
            System.debug('##Score:' + eachParam);

            if(eachParam.LPCR_Format__c != null && eachParam.LPCR_Valeur__c != null && eachParam.LPCR_ApiFieldName__c != null){
                if(eachparam.LPCR_Format__c == 'Nombre'){
                    Decimal ValeurPres = (Decimal)preinscription.get(field);
                    Decimal ValeurParam = Decimal.valueOf(eachParam.LPCR_Valeur__c);

                    if(ValeurPres >= ValeurParam && (!mapValeurNum.containsKey(field) || mapValeurNum.get(field) < ValeurParam)){
                        mapValeurNum.put(field, ValeurParam);
                        mapScore.put(field,eachParam.LPCR_Score__c );
                    }
                }
                
                else if(eachparam.LPCR_Format__c == 'Date'){
                    Date ValeurPres = (Date)preinscription.get(field);
                    String ExtractedDate = eachParam.LPCR_Valeur__c;
                    list<String> lstSplitDate = ExtractedDate.split('/');
                    Date ValeurParam = date.newinstance(Integer.valueOf(lstSplitDate[2]), Integer.valueOf(lstSplitDate[1]), Integer.valueOf(lstSplitDate[0]));
                    
         
                    if(ValeurPres >= ValeurParam && (!mapValeurDate.containsKey(field) || mapValeurDate.get(field) < ValeurParam)){
                        mapValeurDate.put(field, ValeurParam);
                        mapScore.put(field,eachParam.LPCR_Score__c );
                    }
                }
                
                else if(eachparam.LPCR_Format__c == 'Texte'){
                    String ValeurPres = String.valueOf(preinscription.get(field));
                    String ValeurParam = String.valueOf(eachParam.LPCR_Valeur__c);
                    
                    if(ValeurPres == ValeurParam){
                        mapScore.put(field,eachParam.LPCR_Score__c );
                    }
                }
            }
        }
        
        Decimal totalScore = 0;
        for(Decimal score: mapScore.values()){
            totalScore = totalScore + score; 
        }
        return totalScore;
    }
    
}