mdapiEYH/objects/LPCR_BaremeCAF__c.object
<CustomObject>
    <label>Barème CAF</label>
    <nameField>
        <displayFormat>BCAF-{00000}</displayFormat>
        <label>Barème CAF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Barèmes CAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date de début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date de fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_NombresEnfants__c</fullName>
        <label>Nombre d’enfant(s)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LPCR_TauxEffortParEnfant__c</fullName>
        <label>Taux d’effort par enfant(s)</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

mdapiEYH/objects/Order.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Order/fields/LPCR_DateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateDebut__c</fullName>
    <label>Date De Début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/LPCR_DateFin__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateFin__c</fullName>
    <label>Date de fin contractuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EM014_BaremeCafEntity.cls
public with sharing class EM014_BaremeCafEntity {
    public EM014_BaremeCafEntity() {

    }
    public static List<LPCR_BaremeCaf__c> getByDateByNbrEnfHigherOrEqual(Set<Integer> ressFamilleStartDateYears,Decimal minNbrEnfant){
        system.debug('Query ==== SELECT Id, LPCR_NombresEnfants__c ,LPCR_TauxEffortParEnfant__c,LPCR_DateFin__c,LPCR_DateDebut__c FROM LPCR_BaremeCaf__c  WHERE CALENDAR_YEAR(LPCR_DateDebut__c) IN '+ressFamilleStartDateYears+' AND LPCR_NombresEnfants__c>= '+minNbrEnfant+' ORDER BY LPCR_TauxEffortParEnfant__c ASC');
        return [SELECT Id, LPCR_NombresEnfants__c ,LPCR_TauxEffortParEnfant__c,LPCR_DateFin__c,LPCR_DateDebut__c FROM LPCR_BaremeCaf__c 
        WHERE CALENDAR_YEAR(LPCR_DateDebut__c) IN :ressFamilleStartDateYears 
        AND LPCR_NombresEnfants__c>= :minNbrEnfant
        ORDER BY LPCR_NombresEnfants__c ASC];
    }
}