mdapiEYH/objects/LPCR_ModificationEntrante__c.object
<CustomObject>
    <description>Cet objet nous permettra de collecter les données en provenance d&apos;Intranet et de la GTA  concernant des événements et liés à de l&apos;usage sur SF (absences, heures déduites, maladie ...)</description>
    <label>Modification Entrante</label>
    <nameField>
        <displayFormat>ME-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modifications Entrantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_CodePostal__c</fullName>
        <label>Code postal</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_Commentaire__c</fullName>
        <label>Commentaire</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LPCR_Compte__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compte</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteCompte</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enfant, Parent 1 et 2</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contrat Salesforce</description>
        <label>Contrat</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Modifications Entrantes</relationshipLabel>
        <relationshipName>RelationModificationEntranteContrat</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_Evenement__c</fullName>
        <label>Evènement</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Modification Adresse Contact Parent</fullName>
                </value>
                <value>
                    <fullName>Modification Autorité Parentale</fullName>
                </value>
                <value>
                    <fullName>Modification Numéro Allocataire</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Handicapé Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Type Accueil</fullName>
                </value>
                <value>
                    <fullName>Modification Type Planning</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Enfant Fratrie</fullName>
                </value>
                <value>
                    <fullName>Modification Montant Ressource</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Jour Congé</fullName>
                </value>
                <value>
                    <fullName>Date Fin Contrat</fullName>
                </value>
                <value>
                    <fullName>Modification Section</fullName>
                </value>
                <value>
                    <fullName>Date Naissance Enfant</fullName>
                </value>
                <value>
                    <fullName>Modification Mode Garde</fullName>
                </value>
                <value>
                    <fullName>Modification Situation Familiale</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Mois Mensualisé</fullName>
                </value>
                <value>
                    <fullName>Modification Traitement Jour férié</fullName>
                </value>
                <value>
                    <fullName>Modification</fullName>
                </value>
                <value>
                    <fullName>Modification Délai Carence</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Supplémentaire MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Occasionnel MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Nombre Congés MAC</fullName>
                </value>
                <value>
                    <fullName>Modification Heure Déduite MAC</fullName>
                </value>
                <value>
                    <fullName>Validation Contrat Directrice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_HeureDateDebut__c</fullName>
        <label>Date et heure de début</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LPCR_HeureDateFin__c</fullName>
        <label>Date et heure de fin</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LPCR_IDUnique__c</fullName>
        <label>ID Unique</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_OuiNon__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Oui/Non</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LPCR_Pays__c</fullName>
        <label>Pays</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_Quantite__c</fullName>
        <label>Quantité</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LPCR_RessourceFamille__c</fullName>
        <label>Ressource Famille</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LPCR_Rue__c</fullName>
        <label>Rue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LPCR_Section__c</fullName>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bébé</fullName>
                </value>
                <value>
                    <fullName>Moyen</fullName>
                </value>
                <value>
                    <fullName>Grand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypeAccueil__c</fullName>
        <label>Type Accueil</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Tournant</fullName>
                </value>
                <value>
                    <fullName>Multiplanning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_TypePlanning__c</fullName>
        <label>Type de planning</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Classique</fullName>
                </value>
                <value>
                    <fullName>Tournant</fullName>
                </value>
                <value>
                    <fullName>Multi-planning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LPCR_Ville__c</fullName>
        <label>Ville</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/objects/LPCR_ModificationEntrante__c/fields/LPCR_DateEffet__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateEffet__c</fullName>
    <label>DateEffet</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/LPCR_ModificationEntrante__c/fields/LPCR_EtatTraitement__c.field-meta.xml
<CustomField>
    <fullName>LPCR_EtatTraitement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LPCR EtatTraitement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LPCR_ModificationEntrante__c/fields/LPCR_Garde__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Garde__c</fullName>
    <label>Garde</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LPCR_SituationFamiliale__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorité parentale conjointe</fullName>
            </value>
            <value>
                <fullName>Garde alternée</fullName>
            </value>
            <value>
                <fullName>Garde parent unique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LPCR_ModificationEntrante__c/fields/LPCR_Invoice__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>blng__Invoice__c</referenceTo>
    <relationshipLabel>Modifications Entrantes</relationshipLabel>
    <relationshipName>Modifications_Entrantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LPCR_ModificationEntrante__c/fields/LPCR_SituationFamiliale__c.field-meta.xml
<CustomField>
    <fullName>LPCR_SituationFamiliale__c</fullName>
    <label>Situation familiale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En couple</fullName>
            </value>
            <value>
                <fullName>Monoparentale</fullName>
            </value>
            <value>
                <fullName>Marié / Pacsé</fullName>
            </value>
            <value>
                <fullName>Divorcé</fullName>
            </value>
            <value>
                <fullName>Célibataire géographique</fullName>
            </value>
            <value>
                <fullName>Famille recomposée</fullName>
            </value>
            <value>
                <fullName>Veuf / Veuve</fullName>
            </value>
            <value>
                <fullName>Séparé</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

mdapiEYH/objects/LPCR_RessourceFamille__c.object
<CustomObject>
    <label>Ressource Famille</label>
    <nameField>
        <label>Ressource Famille Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ressources Familles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_TypePlanning__c</fullName>
        <label>Type de Planning</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planning Classique</fullName>
                </value>
                <value>
                    <fullName>Multi-Planning</fullName>
                </value>
                <value>
                    <fullName>Planning Tournant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/APB014_TraitementModificationEntrante.cls
/**
* @author Saurabh
* @date 27/05/2021
* @Description Batch for Traitement Modification Entrante
*/

global class APB014_TraitementModificationEntrante implements Database.Batchable<sObject>,Schedulable,Database.Stateful,Database.AllowsCallouts{
    
    global set<id> allSuccessId = new set<id>();
    final String ClassName = APB014_TraitementModificationEntrante.class.getName();

    global APB014_TraitementModificationEntrante() {

    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'start', 'Batch' , null, 'Starting Batch', UM010_Constant.SUCCESS); 

        return Database.getQueryLocator([
                                            SELECT Id,LPCR_EtatTraitement__c,LPCR_Invoice__c,LPCR_TypePlanning__c,LPCR_Garde__c,LPCR_Rue__c,LPCR_Ville__c,LPCR_Pays__c,LPCR_CodePostal__c,LPCR_SituationFamiliale__c,LPCR_TypeAccueil__c,LPCR_DateEffet__c,LPCR_Evenement__c,LPCR_Quantite__c,LPCR_Compte__c,LPCR_RessourceFamille__c,LPCR_IDUnique__c,LPCR_OuiNon__c,LPCR_Contact__c,LPCR_Date__c,LPCR_Section__c,LPCR_Contract__c,LPCR_HeureDateDebut__c,LPCR_HeureDateFin__c,LPCR_Commentaire__c,LPCR_Devis__c,LPCR_Statut__c 
                                            FROM LPCR_ModificationEntrante__c 
                                            WHERE LPCR_DateEffet__c <= TODAY AND LPCR_EtatTraitement__c = false AND 
                                            LPCR_Statut__c = 'Validée' and CreatedBy.Name != 'Integration LPCR' and CreatedBy.Name != 'Recette DEV' 
                                        ]);
    }
    
    global void execute(Database.BatchableContext BC, List<LPCR_ModificationEntrante__c> scope) {

        Exception[] errors = new Exception[0];

        Set<Id> modificationEntranteIds = UM003_TypeManager.getIdsOfListObjects(scope);
        Set<Id> newQuoteIds = new Set<Id>();
        
        try {

            newQuoteIds = SM022_ModificationEntranteServices.updateQuotesFromModifEntrantesBatch(scope);
            PAD.log('APB014_TraitementModificationEntrante', 'execute','quote ids ' + newQuoteIds );
            
            if(newQuoteIds != null && newQuoteIds.size() > 0){
                allSuccessId.addAll(newQuoteIds);
            }
            UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'execute', 'Batch' , null, 'Scope size : '  + scope.size() + '\n Quotes Processed :' + newQuoteIds, UM010_Constant.SUCCESS); 

        } catch(Exception e) {
            errors.add(e);
        }

        if (!errors.isEmpty()) {
            UM001_LogManager.writeLogActivityWithoutFuture(ClassName, 'execute', 'Batch' , null,'Processing with errors occurred : ' + errors, UM010_Constant.ERROR);
        } 
         
    }
    
    global void finish(Database.BatchableContext BC) {

        if (allSuccessId != null && allSuccessId.size() > 0) {

            UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'finish', 'Batch' , null, ClassName + ' Finished. Scheduling APB0016 to run in 2 minutes with quote lines scope :' + String.valueOf(allSuccessId), UM010_Constant.SUCCESS); 

            APB016_QuoteReCalculateProcess sc = new APB016_QuoteReCalculateProcess();
            sc.quoteIds = allSuccessId;
            
            Datetime dt = Datetime.now().addMinutes(2);  // i.e. 2 mins
            String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
            Id schedId = System.Schedule('APB016_QuoteReCalculateProcess'+timeForScheduler,timeForScheduler,sc);
        }  
        
        UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'finish', 'Batch' , null, 'Finished Batch Processing', UM010_Constant.SUCCESS); 
    }
    
    global void execute(SchedulableContext sc) {
        
        APB014_TraitementModificationEntrante sc1 = new APB014_TraitementModificationEntrante();
        Datetime dt = Datetime.now().addMinutes(30);  // i.e. 30 mins
        String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB014_TraitementModificationEntrante');
        
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB014_TraitementModificationEntrante();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 30 mins
                Id schedId = System.Schedule('APB014_TraitementModificationEntrante'+timeForScheduler,timeForScheduler,new APB014_TraitementModificationEntrante());
            }
        }  
        
    }

}