mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/classes/EM006_QuoteEntity_Test.cls
@isTest
public class EM006_QuoteEntity_Test {
    @isTest
    static void EM006_QuoteEntity_Test() {

        EM006_QuoteEntity ent = new EM006_QuoteEntity();    
        
        List<Account> accounts1 = UM002_TestDataFactory.createAccounts(1, 'testAccount_1');
        List<Opportunity> opps1 = UM002_TestDataFactory.createOpportunities(1, 'testOpp_1', 'Prospecting');
        insert accounts1;
        insert opps1;
        SBQQ__Quote__c q = UM002_TestDataFactory.createQuotes(1, accounts1, opps1).get(0);
        insert q;  
        q.SBQQ__StartDate__c = Date.today().addDays(1);
        q = EM006_QuoteEntity.saveOrUpdte(q);
        SBQQ__Quote__c quoteRes = [SELECT id,SBQQ__StartDate__c FROM SBQQ__Quote__c WHERE id=:q.Id ];
        System.assertEquals(Date.today().addDays(1),quoteRes.SBQQ__StartDate__c);

        List<Account> accounts = UM002_TestDataFactory.createAccounts(2, 'testAccount');
        List<Opportunity> opps = UM002_TestDataFactory.createOpportunities(2, 'testOpp', 'Prospecting');
        insert accounts;
        insert opps;
        List<SBQQ__Quote__c> quotes = UM002_TestDataFactory.createQuotes(2, accounts, opps);
        insert quotes;
        quotes.get(0).SBQQ__StartDate__c = Date.today().addDays(2);
        quotes.get(1).SBQQ__StartDate__c = Date.today().addDays(2);
        quotes = EM006_QuoteEntity.saveOrUpdte(quotes);
        System.assertEquals(Date.today().addDays(2),quotes.get(0).SBQQ__StartDate__c);
        System.assertEquals(Date.today().addDays(2),quotes.get(1).SBQQ__StartDate__c);

        SBQQ__Quote__c res = EM006_QuoteEntity.getQuoteById(q.id);
        System.assertNotEquals(null, res);

        //static List<SBQQ__Quote__c> getQuoteModifById (Set<Id> quoteId)
        Set<Id> quoteIds = (new Map<Id,SBQQ__Quote__c>(quotes)).keySet();
        List<SBQQ__Quote__c> res2 = EM006_QuoteEntity.getQuoteModifById(quoteIds);
        System.assertEquals(2, res2.size());
    }
}