mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiEYH/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/LPCR_Quote_Recalculated__c.field-meta.xml
<CustomField>
    <fullName>LPCR_Quote_Recalculated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Recalculated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/APB016_QuoteReCalculateProcess.cls
/**
* @author Saurabh
* @date 26/08/2020
* @Description Batch for QuoteReCalculateProcess call from APB014_TraitementModificationEntrante
*/

global class APB016_QuoteReCalculateProcess implements Database.Batchable<sObject>,Schedulable,Database.Stateful,Database.AllowsCallouts{
    String query;
    global Set<Id> quoteIds = new Set<Id>();  // quoteIds set populate from APB014_TraitementModificationEntrante
    
    global APB016_QuoteReCalculateProcess() {
        
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {    
        PAD.log('APB016_QuoteReCalculateProcess', 'start','quoteIds : '+quoteIds );    
        return Database.getQueryLocator([select id,LPCR_Quote_Recalculated__c from SBQQ__QuoteLine__c where SBQQ__Quote__c IN : quoteIds]);
    }
    
    global void execute(Database.BatchableContext BC, List<SBQQ__QuoteLine__c > scope) {

        PAD.log('APB016_QuoteReCalculateProcess', 'execute','scope to execute : '+scope );
        
        List<SBQQ__QuoteLine__c> updateQLIList = new List<SBQQ__QuoteLine__c>();
        for(SBQQ__QuoteLine__c eachQLI : scope){
            eachQLI.LPCR_Quote_Recalculated__c = true;   
            updateQLIList.add(eachQLI);
        }
        String ErrMsg;
        try {
            // update QLI for autometiclly perform re-calculation
            update updateQLIList;
            UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for QuoteReCalculateProcess call from APB014',
                                                            'APB016_QuoteReCalculateProcess', 'Batch' , null,
                                                            'Successfully updated list of quotes liens : ' + String.valueOf(updateQLIList), 
                                                            UM010_Constant.SUCCESS); 
            PAD.log('APB016_QuoteReCalculateProcess', 'execute','Update success of Quote lines list : ' + updateQLIList );
        } catch (Exception e) {
            ErrMsg = e.getMessage();
        } finally {
            if(ErrMsg != null && String.isNotBlank(ErrMsg)){
                UM001_LogManager.writeLogActivityWithoutFuture( 'Batch for QuoteReCalculateProcess call from APB014','APB013_ProcessYearlyOrderProduct', 'Batch' , null,'Error while updating the quote lines. Error : ' + ErrMsg, UM010_Constant.ERROR);              
            }
        }     
    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
    global void execute(SchedulableContext sc) {
        
        Datetime dtime = Datetime.now().addMinutes(2);
        String format = 's m H d M \'?\' yyyy';
        String timeForScheduler = dtime.format(format);

        APB016_QuoteReCalculateProcess sc1 = new APB016_QuoteReCalculateProcess();
        
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning('APB016_QuoteReCalculateProcess');
                // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB016_QuoteReCalculateProcess();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 2 mins
                Id schedId = System.Schedule('APB016_QuoteReCalculateProcess'+timeForScheduler,timeForScheduler,new APB016_QuoteReCalculateProcess());
            }
        }  
        
    }
    
}