mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <description>Valeurs de Type de Creche recoupere depuis Account Creche</description>
        <label>Type de crèche</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LPCR_TypeCreche</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Ordered__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Internal flag to drive automatic order creation.</description>
        <inlineHelpText>Select this checkbox to automatically create an order from this quote, if it is a primary quote.</inlineHelpText>
        <label>Ordered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Envoi directrice</fullName>
                </value>
                <value>
                    <fullName>Validé directrice</fullName>
                </value>
                <value>
                    <fullName>Prêt à envoyer</fullName>
                </value>
                <value>
                    <fullName>Envoyé pour signature</fullName>
                </value>
                <value>
                    <fullName>Signé</fullName>
                </value>
                <value>
                    <fullName>Actif</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Referencement</fullName>
        <active>true</active>
        <label>Contrat de Référencement</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_BonCommandeEnvoye__c.field-meta.xml
<CustomField>
    <fullName>LPCR_BonCommandeEnvoye__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bon de commande envoyé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/LPCR_RecalculationMACDone__c.field-meta.xml
<CustomField>
    <fullName>LPCR_RecalculationMACDone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recalculation MAC Done?</label>
    <type>Checkbox</type>
</CustomField>

mdapiEYH/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/LPCR_LigneBonCommandeEnvoye__c.field-meta.xml
<CustomField>
    <fullName>LPCR_LigneBonCommandeEnvoye__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ligne de bon de commande envoyée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/LPCR_TypeCreche.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALSH</fullName>
    </customValue>
    <customValue>
        <fullName>MAF</fullName>
    </customValue>
    <customValue>
        <fullName>MAC</fullName>
    </customValue>
    <customValue>
        <fullName>MICRO</fullName>
    </customValue>
    <customValue>
        <fullName>Halte-Garderie</fullName>
    </customValue>
    <customValue>
        <fullName>Jardin d’enfants</fullName>
    </customValue>
    <customValue>
        <fullName>RAM</fullName>
    </customValue>
    <customValue>
        <fullName>Partenaire</fullName>
    </customValue>
    <customValue>
        <fullName>PAJE</fullName>
    </customValue>
    <masterLabel>Type de crèche</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/APB020_EnvoieBonCommande.cls
/**
* @author Erwan Yhuellou
* @date 08/12/2020
* @Description Batch for setting QL Bon de Commande Field to envoyé (only for referencement quote)
*/
global class APB020_EnvoieBonCommande  implements Database.Batchable<sObject>,Schedulable {
    String query;
    final String ClassName = APB020_EnvoieBonCommande.class.getName();
    global APB020_EnvoieBonCommande() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'start', 'Batch' , null, 'Starting Batch', UM010_Constant.SUCCESS);
        PAD.log(ClassName, 'start','Database.BatchableContext BC');        
        query = 'SELECT Id,RecordTypeId,LPCR_BonCommandeEnvoye__c,SBQQ__Status__c ,SBQQ__Ordered__c, LPCR_TypeCreche__c, SBQQ__Type__c, LPCR_RecalculationMACDone__c   FROM SBQQ__Quote__c WHERE SBQQ__Status__c =\'Prêt pour commande\' AND SBQQ__Ordered__c  = false';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<SBQQ__Quote__c> scope) {
        
        UM001_LogManager.writeLogActivityWithoutFuture( ClassName, 'Scope size', 'Batch' , null, String.valueOf(scope.size()), UM010_Constant.SUCCESS); 
        List<Exception> errors = new List<Exception>();
        String ErrMsg;

        try {

            try {
                updateRelatedQuotelines(scope);
                UM001_LogManager.writeLogActivityWithoutFuture( ClassName, 'Updating the quote lines',
                                                                'Batch' , null,
                                                                'Successfully updated (BonCommande) list of quote lines for the Quotes:(' + scope.size() + ')'+ UM003_TypeManager.getIdsOfListObjects(scope), 
                                                                UM010_Constant.SUCCESS);          
            } catch (Exception e) {
                ErrMsg = e.getMessage();
            } finally {
                if(ErrMsg != null && String.isNotBlank(ErrMsg)){
                    UM001_LogManager.writeLogActivityWithoutFuture(ClassName,  'Updating the quote lines','Batch' , null,'Error while updating list of quote lines (LPCR_LigneBonCommandeEnvoye__c=true)' + ErrMsg, UM010_Constant.ERROR);              
                }
            }
            ErrMsg = null;
            PAD.log(ClassName, 'execute','scope :'+ scope.size()+'');        
            
            
        } catch(Exception e) {
            errors.add(e);
        }
        
        if (!errors.isEmpty()) {
            UM001_LogManager.writeLogActivityWithoutFuture(ClassName, 'execute', 'Batch' , null,'Processing with errors occurred : ' + errors, UM010_Constant.ERROR);
        }
            
    }

    global void updateRelatedQuotelines(List<SBQQ__Quote__c> quotes){

        Id referencementRecTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Quote,Label.LPCR_Referencement);
        Id referencementApprRecTypeId = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Quote,Label.LPCR_Referencement_Approuve);

        //Gather refer quotes that their LPCR_BonCommandeEnvoye__c changed to true.
        List<SBQQ__Quote__c> quotesToProcess = new List<SBQQ__Quote__c>();
        for(SBQQ__Quote__c q : quotes){
            
            if( (q.LPCR_BonCommandeEnvoye__c == true) &&
                (q.RecordTypeId == referencementRecTypeId || q.RecordTypeId == referencementApprRecTypeId)                 
                ){
                    quotesToProcess.add(q); 
            }
        }
        //Retrieve their quotesLines having LPCR_LigneBonCommandeEnvoye__c = false and set it to true
        Set<Id> idsQuotes = UM003_TypeManager.getIdsOfListObjects(quotesToProcess);
        List<SBQQ__QuoteLine__c> qLines = [  SELECT id,LPCR_LigneBonCommandeEnvoye__c 
                                            FROM SBQQ__QuoteLine__c 
                                            WHERE SBQQ__Quote__c IN :idsQuotes AND LPCR_LigneBonCommandeEnvoye__c=false];
                                            
        if( !UM003_TypeManager.isNullOrEmpty(qLines)){
            
            for (SBQQ__QuoteLine__c ql : qLines) {
                ql.LPCR_LigneBonCommandeEnvoye__c = true;
            }
            update qLines;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        UM001_LogManager.writeLogActivityWithoutFuture(ClassName,'finish', 'Batch' , null, 'Finished Batch Processing', UM010_Constant.SUCCESS);
    }
    /*
    *   @description : this method execute the batch
    *   @param SchedulableContext sc
    *   @returns void
    */
    global void execute(SchedulableContext sc) {
        PAD.log(ClassName, 'execute','sc ');     
        APB020_EnvoieBonCommande sc1 = new APB020_EnvoieBonCommande();
        Datetime dt = Datetime.now().addMinutes(30);  // i.e. 30 mins
        String timeForScheduler = dt.format('s m H d M \'?\' yyyy');
        // schedule the apex class only if their is not existing job running
        boolean isBatchJobRunning = UM004_BatchUtility.isBatchJobRunning(ClassName);
        
        // check if there is any open place to schedule the class
        boolean isJobQueueFull = UM004_BatchUtility.isBatchJobQueueFull();
        
        if(isBatchJobRunning == UM004_BatchUtility.BOOLEAN_FALSE){
            if (isJobQueueFull == UM004_BatchUtility.BOOLEAN_FALSE) {
                sc1 = new APB020_EnvoieBonCommande();
                Database.executeBatch(this, 1);
            } else {
                //schedule this same schedulable class again in 30 mins
                Id schedId = System.Schedule(ClassName+timeForScheduler,timeForScheduler,new APB020_EnvoieBonCommande());
            }
        }  
        
    } 
}