mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_CloneCancel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clone/Cancel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Number__c</fullName>
        <description>Number indicating this line&apos;s position within its group or quote.</description>
        <inlineHelpText>Number indicating this line&apos;s position within its group or quote.</inlineHelpText>
        <label>Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__RequiredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links this line to another line in the same quote whose product requires this line&apos;s product.</description>
        <inlineHelpText>Indicates which other product on this quote requires it.</inlineHelpText>
        <label>Required By</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/classes/APC006_CloneQuoteLines_Test.cls
/**
*@author Achraf ABOUL(aaboul@salesforce.com)
*@date 21/05/2020
*&description test class for APC006_CloneQuoteLines
*/
@isTest
public with sharing class APC006_CloneQuoteLines_Test {
    @TestSetup
    static void setup(){
        Id standardPricebookId;
        if([SELECT Id FROM Pricebook2 WHERE IsStandard=true].size() > 0){
            standardPricebookId = [SELECT Id FROM Pricebook2 WHERE IsStandard=true].Id;
        }else{
            standardPricebookId = Test.getStandardPricebookId();
        }
        SBQQ__Quote__c quote = UM002_TestDataFactory.createQuote(standardPricebookId, 'Quote');
        quote.SBQQ__Primary__c =true;
        insert quote;
        
        Product2 prod = UM002_TestDataFactory.createProduct('test');
        insert prod;
        
        PricebookEntry priceBookEntry1 = UM002_TestDataFactory.createPricebookEntry(standardPricebookId,prod.Id);
		insert priceBookEntry1;
        
        SBQQ__QuoteLine__c quoteLine1 = UM002_TestDataFactory.createQuoteLine(prod.Id, quote.Id, priceBookEntry1.Id, 200,1);
        quoteLine1.LPCR_CloneCancel__c = true;
        quoteLine1.SBQQ__Number__c = 1;
        insert quoteLine1;

        SBQQ__QuoteLine__c quoteLine2 = UM002_TestDataFactory.createQuoteLine(prod.Id, quote.Id, priceBookEntry1.Id, 200,1);
        quoteLine2.SBQQ__RequiredBy__c = quoteLine1.Id;
        quoteLine2.LPCR_CloneCancel__c = true;
        quoteLine2.SBQQ__Number__c = 2;
        insert quoteLine2;
       
    }
    @IsTest
    static void cloneAndResetQL_Test(){
        Id quoteId = [SELECT Id from SBQQ__Quote__c limit 1].get(0).Id;
        Test.startTest(); 
        APC006_CloneQuoteLines.cloneAndResetQL(quoteId);
        Test.stopTest();
    }

    @IsTest
    static void cloneAndResetQL_Exception1_Test(){
        Id quoteId = [SELECT Id from SBQQ__Quote__c limit 1].get(0).Id;
        Test.startTest(); 
        APC006_CloneQuoteLines.testRunningFlag1 = true;
        APC006_CloneQuoteLines.cloneAndResetQL(quoteId);
        Test.stopTest();
    }
    @IsTest
    static void cloneAndResetQL_Exception2_Test(){
        Id quoteId = [SELECT Id from SBQQ__Quote__c limit 1].get(0).Id;
        Test.startTest(); 
        APC006_CloneQuoteLines.testRunningFlag2 = true;
        APC006_CloneQuoteLines.cloneAndResetQL(quoteId);
        Test.stopTest();
    }
}