mdapiEYH/objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Creche</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Crèche)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPCR_DateDebut__c</fullName>
        <label>Date De Début</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_DateFin__c</fullName>
        <label>Date De Fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LPCR_TypeCreche__c</fullName>
        <description>Valeurs de Type de Creche recoupere depuis Account Creche</description>
        <label>Type de crèche</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LPCR_TypeCreche</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Envoi directrice</fullName>
                </value>
                <value>
                    <fullName>Validé directrice</fullName>
                </value>
                <value>
                    <fullName>Prêt à envoyer</fullName>
                </value>
                <value>
                    <fullName>Envoyé pour signature</fullName>
                </value>
                <value>
                    <fullName>Signé</fullName>
                </value>
                <value>
                    <fullName>Actif</fullName>
                </value>
                <value>
                    <fullName>Annulé</fullName>
                </value>
                <value>
                    <fullName>Terminé</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapiEYH/objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>LPCR_Creche__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crèche</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Crèche</value>
            </filterItems>
            <filterItems>
                <field>Account.LPCR_Region__c</field>
                <operation>equals</operation>
                <valueField>$Source.LPCR_Region__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__EffectiveStartDate__c</fullName>
        <description>Effective start date for this subscription.</description>
        <formula>IF(ISBLANK(SBQQ__StartDate__c),
  IF(ISBLANK(SBQQ__Group__r.SBQQ__StartDate__c),SBQQ__Quote__r.SBQQ__StartDate__c,SBQQ__Group__r.SBQQ__StartDate__c),
  SBQQ__StartDate__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Effective start date for this subscription.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
        <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__PriorQuantity__c</fullName>
        <description>Combined quantity of this product from prior purchases.</description>
        <inlineHelpText>Combined quantity of this product from prior purchases.</inlineHelpText>
        <label>Prior Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProductCode__c</fullName>
        <description>Code for the product referenced by this line.</description>
        <formula>SBQQ__Product__r.ProductCode</formula>
        <inlineHelpText>Code for the product referenced by this line.</inlineHelpText>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/LPCR_DateDebut__c.field-meta.xml
<CustomField>
    <fullName>LPCR_DateDebut__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/LPCR_HoldBilling__c.field-meta.xml
<CustomField>
    <fullName>LPCR_HoldBilling__c</fullName>
    <label>Hold Billing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LPCR_TypeCreche.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALSH</fullName>
    </customValue>
    <customValue>
        <fullName>MAF</fullName>
    </customValue>
    <customValue>
        <fullName>MAC</fullName>
    </customValue>
    <customValue>
        <fullName>MICRO</fullName>
    </customValue>
    <customValue>
        <fullName>Halte-Garderie</fullName>
    </customValue>
    <customValue>
        <fullName>Jardin d’enfants</fullName>
    </customValue>
    <customValue>
        <fullName>RAM</fullName>
    </customValue>
    <customValue>
        <fullName>Partenaire</fullName>
    </customValue>
    <customValue>
        <fullName>PAJE</fullName>
    </customValue>
    <masterLabel>Type de crèche</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SM013_QuoteLineServices.cls
/**
* @author Dario Correnti
* @date 19/05/2020
* @description Service class for QuoteLine
*/
public with sharing class SM013_QuoteLineServices {
    
    /*
	*	@description : this method check if any registration fee had been alredy applied for a given customer / nursery.
	*	@param List<SBQQ__QuoteLine__c> quoteLineList to process
    *	@returns void
    */
    public static void checkExistingRegistrationFee (List<SBQQ__QuoteLine__c> quoteLineList) {
        PAD.log('SM013_QuoteLineServices', 'checkExistingRegistrationFee', 'start method with quoteLineList: ' + quoteLineList.size());
        Set<Id> quoteIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        Set<Id> customerAccountIds = new Set<Id>();
        Map<String, Asset> assetsByCustomerNurseryYear = new Map<String, Asset> ();

        for (SBQQ__QuoteLine__c ql : quoteLineList) {
            quoteIds.add(ql.SBQQ__Quote__c);
        }

        // Load QL related data
        Map<Id, SBQQ__Quote__c> quotesById = new Map<Id, SBQQ__Quote__c> ([SELECT Id, LPCR_TypeCreche__c, SBQQ__Account__c, LPCR_Creche__c, SBQQ__Status__c FROM SBQQ__Quote__c WHERE Id IN :quoteIds]);
        for (SBQQ__QuoteLine__c ql : quoteLineList) {
            if (quotesById.get(ql.SBQQ__Quote__c).LPCR_TypeCreche__c != 'MAC' 
                || quotesById.get(ql.SBQQ__Quote__c).SBQQ__Status__c != 'Draft' 
                || ql.SBQQ__ProductCode__c != Label.LPCR_RegistrationFeeMac) {
                    continue;
            }
            customerAccountIds.add(quotesById.get(ql.SBQQ__Quote__c).SBQQ__Account__c);
        }
        PAD.log('SM013_QuoteLineServices', 'checkExistingRegistrationFee', 'customerAccountIds: ' + customerAccountIds);

        // Load all Registration Fees for current customers
        List<Asset> assets = [SELECT Id, AccountId, ProductCode, SBQQ__QuoteLine__c, SBQQ__QuoteLine__r.SBQQ__Quote__c,
            SBQQ__QuoteLine__r.SBQQ__Quote__r.LPCR_Creche__c, SBQQ__QuoteLine__r.SBQQ__EffectiveStartDate__c FROM Asset WHERE AccountId IN :customerAccountIds AND ProductCode = :Label.LPCR_RegistrationFeeMac];

        PAD.log('SM013_QuoteLineServices', 'checkExistingRegistrationFee', 'assets: ' + assets);
        for (Asset a : assets) {
            String assetKey = a.AccountId + '-' 
                + a.SBQQ__QuoteLine__r.SBQQ__Quote__r.LPCR_Creche__c + '-' 
                + a.SBQQ__QuoteLine__r.SBQQ__EffectiveStartDate__c.year();

            assetsByCustomerNurseryYear.put (assetKey, a);
        }
        PAD.log('SM013_QuoteLineServices', 'checkExistingRegistrationFee', 'assetsByCustomerNurseryYear: ' + assetsByCustomerNurseryYear.keySet());

        // Check if any QL
        for (SBQQ__QuoteLine__c ql : quoteLineList) {
            if (quotesById.get(ql.SBQQ__Quote__c).LPCR_TypeCreche__c != 'MAC' 
                || quotesById.get(ql.SBQQ__Quote__c).SBQQ__Status__c != 'Draft' 
                || ql.SBQQ__ProductCode__c != Label.LPCR_RegistrationFeeMac) {
                    continue;
            }

            String relatedAssetKey = quotesById.get(ql.SBQQ__Quote__c).SBQQ__Account__c + '-' 
                + quotesById.get(ql.SBQQ__Quote__c).LPCR_Creche__c + '-' 
                + ql.SBQQ__EffectiveStartDate__c.year();
                
            PAD.log('SM013_QuoteLineServices', 'checkExistingRegistrationFee', 'relatedAssetKey: ' + relatedAssetKey);

            if (assetsByCustomerNurseryYear.containsKey(relatedAssetKey)) {
                ql.addError(Label.LPCR_RegistrationFeeErrorMessage);
            }
        }
    }
    /*
	*	@description : Updates startdate and enddate on quotelines
	*	@param List<SBQQ__QuoteLine__c> quoteLineList to process from trigger context
    *	@returns void
    */
    public static void setStartAndEndDates(List<SBQQ__QuoteLine__c> newQuoteLineList){
            //Build set of parent quotes Ids    
            Set<Id> quotesIds = new Set<Id>();
            for(SBQQ__QuoteLine__c eachQuoteLine : newQuoteLineList){
                quotesIds.add(eachQuoteLine.SBQQ__Quote__c);
            }
            //Used to get data about quotes related to quote lines
            Map<Id, SBQQ__Quote__c> quoteIdToQuoteMap = new Map<Id, SBQQ__Quote__c>([SELECT Id, SBQQ__Type__c, RecordTypeId, SBQQ__StartDate__c, SBQQ__EndDate__c FROM SBQQ__Quote__c WHERE Id IN :quotesIds]);
            
            Id quoteReferencementRT = EM003_RecordTypeEntity.getRecTypeIdByObjectAndName(Label.LPCR_Quote, Label.LPCR_Referencement);
            //Will contain the quote record which is parent of the current quoteLine inside the loop
            SBQQ__Quote__c parentQuote;
            for(SBQQ__QuoteLine__c eachQuoteLine : newQuoteLineList){
                parentQuote = quoteIdToQuoteMap.get(eachQuoteLine.SBQQ__Quote__c);

                if(parentQuote != null && parentQuote.RecordTypeId == quoteReferencementRT && parentQuote.SBQQ__Type__c != Label.LPCR_Amendment){
                    //Is the QL supposed to start this year? already started?
                    if(eachQuoteLine.LPCR_DateDebut__c != null && (eachQuoteLine.LPCR_DateDebut__c.year() <= parentQuote.SBQQ__StartDate__c.year())){
                        //Is the QL still alive this year?
                        if(eachQuoteLine.LPCR_DateFin__c != null && (eachQuoteLine.LPCR_DateFin__c.year() >= parentQuote.SBQQ__StartDate__c.year())){
                            //SBQQEndDate logic
                            if(eachQuoteLine.LPCR_DateFin__c.year() == parentQuote.SBQQ__StartDate__c.year()){
                                eachQuoteLine.SBQQ__EndDate__c = eachQuoteLine.LPCR_DateFin__c;
                            }
                            else{
                                eachQuoteLine.SBQQ__EndDate__c = Date.valueOf(''+ parentQuote.SBQQ__StartDate__c.year() + '-12-31');
                            }
                            //SBQQStartDate logic
                            if(eachQuoteLine.LPCR_DateDebut__c.year() == parentQuote.SBQQ__StartDate__c.year()){
                                eachQuoteLine.SBQQ__StartDate__c = eachQuoteLine.LPCR_DateDebut__c;
                            }
                        }               
                        else{
                            //If the QL won't still alive this year set quantity to 0
                            eachQuoteLine.SBQQ__Quantity__c = 0;
                        }
                    }       
                    else{
                        //If the QL won't start this year or it is not already started, set HoldBilling to true
                        eachQuoteLine.LPCR_HoldBilling__c = 'Yes'; //Picklist value
                    }
                }
                //We add this check to not override dates for the cloned line from ‘clone/cancel’ 
                //It will have the exact dates as the original QL
                if(parentQuote != null && parentQuote.RecordTypeId == quoteReferencementRT && parentQuote.SBQQ__Type__c  == Label.LPCR_Amendment
                    && eachQuoteLine.SBQQ__StartDate__c == null){
                    //Not a Newly added QL in the amendment
                    if(eachQuoteLine.SBQQ__PriorQuantity__c != 0){
                        eachQuoteLine.SBQQ__StartDate__c = parentQuote.SBQQ__StartDate__c; 
                        eachQuoteLine.SBQQ__EndDate__c = parentQuote.SBQQ__EndDate__c;
                    }
                    //Newly added QL in the amendment
                    else{
                        if(eachQuoteLine.LPCR_DateDebut__c.year() == parentQuote.SBQQ__StartDate__c.year()){
                            eachQuoteLine.SBQQ__StartDate__c = eachQuoteLine.LPCR_DateDebut__c;
                            if(eachQuoteLine.LPCR_DateFin__c.year() <= parentQuote.SBQQ__StartDate__c.year()){
                                eachQuoteLine.SBQQ__EndDate__c = eachQuoteLine.LPCR_DateFin__c;
                            }
                            else{ 
                                eachQuoteLine.SBQQ__EndDate__c = Date.valueOf(''+ parentQuote.SBQQ__StartDate__c.year() + '-12-31');
                            }
                        }	
                        else{ 
                            eachQuoteLine.LPCR_HoldBilling__c = 'Yes'; //Picklist value
                        }
                    }
                }
            }
    }
}