force-app/main/default/objects/blng__BillingTransaction__c/fields/LPCR_ProcessProrate__c.field-meta.xml
<CustomField>
    <fullName>LPCR_ProcessProrate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permet d&apos;identifier les billing transaction qui seront traités par le batch APB021 afin de reporter le montant sur le revenue transaction associé</description>
    <label>Report Revenue transaction traité</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SM026_BillingTransactionServices.cls
/**
 * @author Erwan Yhuellou
 * @created 26/02/2021
* @description Service class for Billing Transaction Object
*/

public with sharing class SM026_BillingTransactionServices {
    
    public static void setCorrespondingRevenueTransactions(Map<Id, blng__BillingTransaction__c> oldBtMap, Map<Id, blng__BillingTransaction__c> newBtMap){
        
        for(blng__BillingTransaction__c bt : newBtMap.values()){

            if((oldBtMap.get(bt.Id).blng__OverrideAmount__c != bt.blng__OverrideAmount__c) || 
            oldBtMap.get(bt.Id).blng__OverrideBillingTargetDate__c != bt.blng__OverrideBillingTargetDate__c){
                
                PAD.log('SM026_BillingTransactionServices', 'setCorrespondingRevenueTransactions', 'critical value changed - bt' + bt);
                bt.LPCR_ProcessProrate__c = true;
            }
        }
    }
}